include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/api/generated/**'
  errors:
    unnecessary_import: warning
    unnecessary_null_comparison: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    avoid_redundant_argument_values: false
