// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T04:34:25.037Z
// Source: TypeScript parser
// Parser: sanitizer

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../types.dart' show RuleSet;

final communityRule = {'name': 'community', 'maskCategories': ['personal', 'financial', 'contact'], 'minConfidence': 'LOW'};
