// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-11T10:23:29.684Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import '../types.dart' show RuleMode, RuleSet;
import './community.dart' show communityRule;
import './regular.dart' show regularRule;

final Map<String, dynamic> RULE_SETS = {'community': communityRule, 'regular': regularRule};

RuleSet loadRuleSet(RuleMode mode) {
  return RULE_SETS[mode];
}
