// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T14:01:15.948Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../types.dart' show RuleMode, RuleSet;
import './community.dart' show communityRule;
import './regular.dart' show regularRule;

final Map<String, dynamic> RULE_SETS = String, dynamic(community: communityRule, regular: regularRule);

RuleSet loadRuleSet(String mode) {
  return RULE_SETS[mode];
}
