// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T04:34:24.452Z
// Source: TypeScript parser
// Parser: sanitizer

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../types.dart' show RuleMode, RuleSet;
import './community.dart' show communityRule;
import './regular.dart' show regularRule;

final Map<String, dynamic> RULE_SETS = {'community': communityRule, 'regular': regularRule};

RuleSet loadRuleSet(String mode) {
  return RULE_SETS[mode];
}
