// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-11T10:23:29.457Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import '../types.dart' show RuleSet;

final RuleSet regularRule = {'name': 'regular', 'maskCategories': ['personal'], 'skipTypes': ['bank_card_cn'], 'minConfidence': 'MEDIUM'};
