// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T14:01:15.586Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../types.dart' show RuleSet;

final regularRule = {'name': 'regular', 'maskCategories': ['personal'], 'skipTypes': ['bank_card_cn'], 'minConfidence': 'MEDIUM'};
