// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T14:01:18.202Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:math';

String maskName(String value) {
  return value[0] + List.filled(max(value.length - 1, 1), '*').join();
}

String maskAccount(String value) {
  final digits = value.replaceAll(RegExp(r'\D'), '');
  return '****' + digits.substring(digits.length - 4);
}

String maskPhone(String value) {
  return value.substring(0, 3) + '****' + value.substring(value.length - 4);
}

String maskIdCard(String value) {
  return List.filled(max(value.length - 4, 0), '*').join() + value.substring(value.length - 4);
}

String maskEmail(String value) {
  final atIndex = value.indexOf('@');
  if (atIndex < 1) {
  return '***';
  }
  final local = value.substring(0, atIndex);
  final domain = value.substring(atIndex + 1);
  return local[0] + '**@' + domain;
}

String maskAddress(String _value) {
  return '[desensitized]';
}

String maskIban(String value) {
  return List.filled(max(value.length - 4, 0), '*').join() + value.substring(value.length - 4);
}

String maskSsn(String _value) {
  return '***-**-****';
}
