// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T12:52:15.302Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/types.dart' show RawTransaction;

typedef PiiType = String;

typedef Confidence = String;

typedef RuleMode = String;

class PiiPattern {
  final PiiType type;
  final String name;
  final RegExp pattern;
  final bool Function(String)? validator;
  final String Function(String) mask;
  final String category;
  const PiiPattern({required this.type, required this.name, required this.pattern, this.validator, required this.mask, required this.category});
}

class RuleSet {
  final String name;
  final List<dynamic> maskCategories;
  final List<PiiType>? skipTypes;
  final String? minConfidence;
  const RuleSet({required this.name, required this.maskCategories, this.skipTypes, this.minConfidence});
}

class SanitizeSuccess {
  final bool success;
  final List<RawTransaction> data;
  final dynamic report;
  const SanitizeSuccess({required this.success, required this.data, required this.report});
}

class SanitizeError {
  final bool success;
  final String error;
  const SanitizeError({required this.success, required this.error});
}

typedef SanitizeResult = dynamic;

class SanitizeReport {
  final num totalScanned;
  final num totalSanitized;
  final List<dynamic> findings;
  const SanitizeReport({required this.totalScanned, required this.totalSanitized, required this.findings});
}

class PiiFinding {
  final num transactionIndex;
  final String field;
  final PiiType piiType;
  final String confidence;
  final String action;
  const PiiFinding({required this.transactionIndex, required this.field, required this.piiType, required this.confidence, required this.action});
}

class SanitizeEngineOptions {
  final String region;
  final String ruleMode;
  const SanitizeEngineOptions({required this.region, required this.ruleMode});
}
