// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T04:59:57.147Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/types.dart' show RawTransaction;

typedef PiiType = String;

typedef Confidence = String;

typedef RuleMode = String;

abstract class PiiPattern {
  PiiType get type;
  set type(PiiType value);
  String get name;
  set name(String value);
  RegExp get pattern;
  set pattern(RegExp value);
  bool Function(String) get validator;
  String Function(String) get mask;
  set mask(String Function(String) value);
  String get category;
  set category(String value);
}

abstract class RuleSet {
  String get name;
  set name(String value);
  List<dynamic> get maskCategories;
  set maskCategories(List<dynamic> value);
  List<PiiType> get skipTypes;
  String get minConfidence;
}

abstract class SanitizeSuccess {
  bool get success;
  set success(bool value);
  List<RawTransaction> get data;
  set data(List<RawTransaction> value);
  dynamic get report;
  set report(dynamic value);
}

abstract class SanitizeError {
  bool get success;
  set success(bool value);
  String get error;
  set error(String value);
}

typedef SanitizeResult = dynamic;

abstract class SanitizeReport {
  num get totalScanned;
  set totalScanned(num value);
  num get totalSanitized;
  set totalSanitized(num value);
  List<dynamic> get findings;
  set findings(List<dynamic> value);
}

abstract class PiiFinding {
  num get transactionIndex;
  set transactionIndex(num value);
  String get field;
  set field(String value);
  PiiType get piiType;
  set piiType(PiiType value);
  String get confidence;
  set confidence(String value);
  String get action;
  set action(String value);
}

abstract class SanitizeEngineOptions {
  String get region;
  set region(String value);
  String get ruleMode;
  set ruleMode(String value);
}
