// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-11T10:23:31.263Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'package:firela/parser/src/types.dart' show RawTransaction;

typedef PiiType = dynamic;

typedef Confidence = dynamic;

typedef RuleMode = dynamic;

abstract class PiiPattern {
  PiiType get type;
  set type(PiiType value);
  String get name;
  set name(String value);
  RegExp get pattern;
  set pattern(RegExp value);
  (match: string) => boolean get validator;
  (value: string) => string get mask;
  set mask((value: string) => string value);
  dynamic get category;
  set category(dynamic value);
}

abstract class RuleSet {
  RuleMode get name;
  set name(RuleMode value);
  List<PiiPattern['category']> get maskCategories;
  set maskCategories(List<PiiPattern['category']> value);
  List<PiiType> get skipTypes;
  Confidence get minConfidence;
}

abstract class SanitizeSuccess {
  true get success;
  set success(true value);
  List<RawTransaction> get data;
  set data(List<RawTransaction> value);
  SanitizeReport get report;
  set report(SanitizeReport value);
}

abstract class SanitizeError {
  false get success;
  set success(false value);
  String get error;
  set error(String value);
}

typedef SanitizeResult = dynamic;

abstract class SanitizeReport {
  num get totalScanned;
  set totalScanned(num value);
  num get totalSanitized;
  set totalSanitized(num value);
  List<PiiFinding> get findings;
  set findings(List<PiiFinding> value);
}

abstract class PiiFinding {
  num get transactionIndex;
  set transactionIndex(num value);
  String get field;
  set field(String value);
  PiiType get piiType;
  set piiType(PiiType value);
  Confidence get confidence;
  set confidence(Confidence value);
  dynamic get action;
  set action(dynamic value);
}

abstract class SanitizeEngineOptions {
  String get region;
  set region(String value);
  RuleMode get ruleMode;
  set ruleMode(RuleMode value);
}
