// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-14T12:45:08.222Z
// Source: TypeScript parser
// Parser: csv-parser-base

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:firela/parser/src/result.dart';

import './csv-reader.dart' show detectDelimiter;
import './encoding.dart' show detectEncoding, convertEncoding;
import './types.dart' show RawTransaction, ParseResult, ParseSuccess, ParseWarning, DetectionResult, Parser, createParseFailure;

abstract class ColumnDef {
  List<String> get names;
  set names(List<String> value);
  num get fallbackIndex;
  bool get required;
}

typedef RowTransformResult = dynamic;

abstract class CsvParserConfig {
  String get institutionId;
  set institutionId(String value);
  Map<String, dynamic> get columns;
  set columns(Map<String, dynamic> value);
  List<String> get identifyKeywords;
  set identifyKeywords(List<String> value);
  num get minColumns;
  set minColumns(num value);
  String? detectFormat(List<String> headers);
  RowTransformResult<T> transformRow(List<String> row, Map<String, num> columnMap, String? format);
}

abstract class CsvParser extends Parser<T> {
  late final CsvParserConfig<T> config;
  DetectionResult detect(String filename, Uint8List content) {
    final _obj = this.config;
    final institutionId = _obj.institutionId;
    final identifyKeywords = _obj.identifyKeywords;
    final minColumns = _obj.minColumns;
    final decodedContent = this.decodeContent(content);
    final matchedKeywords = identifyKeywords.where((dynamic kw) => decodedContent.contains(kw)).toList();
    if (matchedKeywords.isEmpty) {
    return {'confidence': 0};
    }
    final firstLine = decodedContent.split(RegExp(r'\r?\n'))[0] ?? '';
    final delimiter = detectDelimiter(firstLine);
    final columnCount = firstLine.split(delimiter).length;
    if (matchedKeywords.length == identifyKeywords.length && columnCount >= minColumns) {
    final headers = firstLine.split(delimiter).map((dynamic h) => h.trim()).toList();
    final formatVersion = this.config.detectFormat(headers);
    return {'confidence': 100, ...((formatVersion ? {} : {}) as Map<String, dynamic>)};
    }
    return {'confidence': 50};
  }
  
  Future<ParseResult<T>> parse(Uint8List content) {
    final _obj = this;
    final config = _obj.config;
    final decoded = this.decodeContent(content);
    if (!decoded.trim()) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final delimiter = detectDelimiter(decoded);
    List<List<String>> rows;
    try {
    rows = parseCsv(decoded, {'skip_empty_lines': true, 'relax_column_count': true, 'trim': true});
    } catch (error) {
    final message = error is Exception ? error.toString() : (error).toString();
    return createParseFailure('CSV_PARSE_ERROR', 'CSV parsing failed: $message');
    }
    if (rows.isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'No data rows found in file');
    }
    final headers = rows[0].map((dynamic h) => h.trim()).toList() ?? [];
    final columnMap = this.buildColumnMap(headers);
    for (final entry in (config.columns as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final logicalName = entry.key;
    final def = entry.value;
    if (def.required && !columnMap.containsKey(logicalName)) {
    final nameList = def.names.join(', ');
    return createParseFailure('MISSING_REQUIRED_FIELD', 'Required column not found: $nameList (logical name: $logicalName)');
    }
    }
    final format = config.detectFormat(headers);
    List<T> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 1; i < rows.length; i++) {
    final row = rows[i];
    if (row == null || row.every((dynamic cell) => !cell.trim())) {
    continue;
    }
    final result = config.transformRow(row, columnMap, format);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': i + 1, 'context': result.error.context});
    }
    }
    if (transactions.isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'No valid transactions found in file', {'warningCount': warnings.length});
    }
    ParseSuccess<T> success = ok(transactions);
    if (warnings.isNotEmpty) {
    success.warnings = warnings;
    }
    return success;
  }
  
  Map<String, num> buildColumnMap(List<String> headers) {
    final columnMap = Map();
    for (final entry in (this.config.columns as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final logicalName = entry.key;
    final def = entry.value;
    for (final name in def.names) {
    final index = headers.indexWhere((dynamic header) => header.trim().toLowerCase() == name.trim().toLowerCase());
    if (index != -1) {
    columnMap.set(logicalName, index);
    break;
    }
    }
    if (!columnMap.containsKey(logicalName) && def.fallbackIndex != null) {
    columnMap.set(logicalName, def.fallbackIndex);
    }
    }
    return columnMap;
  }
  
  String getColumnValue(List<String> row, Map<String, num> columnMap, String name, num? fallbackIndex) {
    final index = columnMap['get'](name);
    if (index != null && index < row.length) {
    return row[index] ?? '';
    }
    if (fallbackIndex != null && fallbackIndex < row.length) {
    return row[fallbackIndex] ?? '';
    }
    return '';
  }
  
  num parseEuropeanNumber(String value) {
    if (!value.trim()) {
    return 0;
    }
    var cleaned = value.trim();
    cleaned = cleaned.replaceFirst(RegExp(r'^[A-Z]{3}\s*'), '');
    cleaned = cleaned.replaceFirst(RegExp(r'\s*[A-Z]{3}$'), '');
    if (cleaned.startsWith('(') && cleaned.endsWith(')')) {
    cleaned = '-' + cleaned.substring(1, -1);
    }
    cleaned = cleaned.replaceAll(RegExp(r'\s'), '');
    final lastComma = cleaned.lastIndexOf(',');
    final lastDot = cleaned.lastIndexOf('.');
    if (lastComma > lastDot) {
    cleaned = cleaned.replaceAll(RegExp(r'\.'), '').replaceAll(',', '.');
    } else if (lastDot > lastComma) {
    cleaned = cleaned.replaceAll(RegExp(r','), '');
    }
    final parsed = double.parse(cleaned);
    return parsed.isNaN ? 0 : parsed;
  }
  
  String decodeContent(Uint8List content) {
    final detectResult = detectEncoding(content);
    final sourceEncoding = detectResult.success ? detectResult.value : 'UTF-8';
    if (sourceEncoding.toUpperCase() != 'UTF-8') {
    final conversionResult = convertEncoding(content, sourceEncoding, 'UTF-8');
    if (conversionResult.success != null) {
    return conversionResult.value;
    }
    }
    return utf8.decode(content);
  }
  
}
