// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-14T12:45:08.498Z
// Source: TypeScript parser
// Parser: golden-file

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:math';

import 'package:firela/parser/src/result.dart';

import './types.dart' show Parser, ParseResult, RawTransaction;
// TODO: unmapped import: fs
// TODO: unmapped import: path

abstract class GoldenFileExpected {
  bool get success;
  set success(bool value);
  {
    /** Transaction date as YYYY-MM-DD string */
    date: string;
    /** Decimal string representation of amount */
    amount: string;
    /** ISO 4217 currency code */
    currency: string;
    /** Transaction description/narration */
    description: string;
    /** Payee/counterparty name */
    payee?: string;
    /** Parser-specific custom fields */
    customFields?: Record<string, unknown>;
  }[] get data;
  List<{ type: string; message: string }> get errors;
  List<{ type: string; message: string }> get warnings;
}

abstract class GoldenFileTestResult {
  bool get passed;
  set passed(bool value);
  List<String> get mismatches;
  set mismatches(List<String> value);
}

Future<GoldenFileTestResult> runGoldenFileTest(Parser<T> parser, String fixtureDir) {
  final files = fs.readdirSync(fixtureDir);
  final sampleFile = files.firstWhere((dynamic f) => f.startsWith('sample'));
  final expectedFile = files.firstWhere((dynamic f) => f == 'expected.json');
  if (sampleFile == null || expectedFile == null) {
  return {'passed': false, 'mismatches': ['Missing sample or expected.json in $fixtureDir']};
  }
  final content = fs.readFileSync(path.join(fixtureDir, sampleFile));
  GoldenFileExpected expected = JSON.parse(fs.readFileSync(path.join(fixtureDir, expectedFile), 'utf-8'));
  final result = /* TODO: AwaitExpression: await parser.parse(content) */;
  List<String> mismatches = [];
  if (result.success != expected.success) {
  mismatches.add('success: got ${result.success}, expected ${expected.success}');
  return {'passed': false};
  }
  if (result.success && expected.success && expected.data) {
  final actualData = (result).data;
  if (actualData.length != expected.data.length) {
  mismatches.add('transaction count: got ${actualData.length}, expected ${expected.data.length}');
  }
  final minLen = min(actualData.length, expected.data.length);
  for (var i = 0; i < minLen; i++) {
  final actual = actualData[i];
  final exp = expected.data[i];
  final actualDate = actual.date is DateTime ? actual.date.toISOString().split('T')[0] : (actual.date).toString();
  if (actualDate != exp.date) {
  mismatches.add('tx[$i].date: got $actualDate, expected ${exp.date}');
  }
  final actualAmount = (actual.amount).toString();
  if (actualAmount != exp.amount) {
  mismatches.add('tx[$i].amount: got $actualAmount, expected ${exp.amount}');
  }
  if (actual.currency != exp.currency) {
  mismatches.add('tx[$i].currency: got ${actual.currency}, expected ${exp.currency}');
  }
  if (actual.description != exp.description) {
  mismatches.add('tx[$i].description: got "${actual.description}", expected "${exp.description}"');
  }
  final actualPayee = actual.payee ?? null;
  final expectedPayee = exp.payee ?? null;
  if (actualPayee != expectedPayee) {
  mismatches.add('tx[$i].payee: got "$actualPayee", expected "$expectedPayee"');
  }
  }
  }
  if (!result.success && !expected.success && expected.errors) {
  final actualErrors = (result).errors;
  if (actualErrors.length != expected.errors.length) {
  mismatches.add('error count: got ${actualErrors.length}, expected ${expected.errors.length}');
  }
  final minErrLen = min(actualErrors.length, expected.errors.length);
  for (var i = 0; i < minErrLen; i++) {
  if (actualErrors[i].type != expected.errors[i].type) {
  mismatches.add('error[$i].type: got ${actualErrors[i].type}, expected ${expected.errors[i].type}');
  }
  }
  }
  return {'passed': mismatches.isEmpty};
}

GoldenFileExpected normalizeToExpected(ParseResult<T> result) {
  if (!result.success) {
  final failure = result;
  return ParseFailure(errors: failure.errors.map((dynamic e) => ({'type': e.type, 'message': e.toString()})).toList());
  }
  final success = result;
  return ok(data: success.data.map((dynamic tx) => ({'date': tx.date is DateTime ? tx.date.toISOString().split('T')[0] : (tx.date).toString(), 'amount': (tx.amount).toString(), 'currency': tx.currency, 'description': tx.description, 'payee': tx.payee, 'customFields': tx.customFields})).toList(), warnings: success.warnings.map((dynamic w) => ({'type': w.type, 'message': w.toString()})).toList());
}
