// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-14T12:45:08.787Z
// Source: TypeScript parser
// Parser: pdf-table-reader

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:math';
import './types.dart' show Result, ok, err;

typedef PdfTableErrorType = dynamic;

abstract class PdfTableError {
  PdfTableErrorType get type;
  set type(PdfTableErrorType value);
  String get message;
  set message(String value);
  dynamic get details;
}

abstract class PdfTextItem {
  String get str;
  set str(String value);
  num get x;
  set x(num value);
  num get y;
  set y(num value);
  num get width;
  set width(num value);
  num get height;
  set height(num value);
}

abstract class PdfTextExtraction {
  List<PdfTextItem> get items;
  set items(List<PdfTextItem> value);
  String get fullText;
  set fullText(String value);
}

abstract class PdfTableCell {
  String get content;
  set content(String value);
  num get x;
  set x(num value);
  num get y;
  set y(num value);
}

typedef PdfTableRow = List<PdfTableCell>;

abstract class PdfTableResult {
  List<List<String>> get rows;
  set rows(List<List<String>> value);
  Map<String, dynamic> get metadata;
  String get fullText;
  set fullText(String value);
}

abstract class PdfTableReadOptions {
  dynamic get headerFirstCell;
  num get yTolerance;
  num get xTolerance;
  num get minColumnWidth;
}

typedef PdfTableReadResult = Result<PdfTableResult, PdfTableError>;

Future<Result<PdfTextExtraction, PdfTableError>> extractPdfText(dynamic buffer) {
  try {
  final pdfjsLib = /* TODO: AwaitExpression: await import('pdfjs-dist') */;
  final data = buffer is Uint8List ? Uint8Array(buffer) : buffer;
  final loadingTask = pdfjsLib.getDocument({});
  final pdf = /* TODO: AwaitExpression: await loadingTask.promise */;
  List<PdfTextItem> items = [];
  List<String> textParts = [];
  for (var pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
  final page = /* TODO: AwaitExpression: await pdf.getPage(pageNum) */;
  final textContent = /* TODO: AwaitExpression: await page.getTextContent() */;
  final viewport = page.getViewport({'scale': 1});
  for (final item in textContent.items) {
  if (!('str' in item)) {
  continue;
  }
  final textItem = (item as { str: string; transform: number[]; width: number; height: number });
  final text = textItem.str.trim();
  if (text.isEmpty) {
  continue;
  }
  final x = textItem.transform[4];
  final y = textItem.transform[5];
  final pdfY = viewport.height - y;
  items.add({'str': text, 'y': pdfY, 'width': textItem.width, 'height': textItem.height});
  textParts.add(text);
  }
  }
  items.sort((dynamic a, dynamic b) { final yDiff = b.y - a.y;
  if (abs(yDiff) > 2) {
  return yDiff;
  }
  return a.x - b.x; });
  return ok({'fullText': textParts.join(' ')});
  } catch (error) {
  return err({'type': 'PDF_LOAD_ERROR', 'message': 'Failed to extract PDF text: ${error is Exception ? error.toString() : (error).toString()}', 'details': error});
  }
}

List<PdfTableRow> clusterIntoRows(List<PdfTextItem> items, [num yTolerance = 3]) {
  if (items.isEmpty) {
  return [];
  }
  final sorted = [...items].sort((dynamic a, dynamic b) { final yDiff = b.y - a.y;
  if (abs(yDiff) > yTolerance) {
  return yDiff;
  }
  return a.x - b.x; });
  List<PdfTableRow> rows = [];
  List<PdfTableCell> currentRow = [];
  var currentY = sorted[0].y;
  for (final item in sorted) {
  if (abs(item.y - currentY) <= yTolerance) {
  currentRow.add({'content': item.str, 'x': item.x, 'y': item.y});
  } else {
  if (currentRow.isNotEmpty) {
  currentRow.sort((dynamic a, dynamic b) => a.x - b.x);
  rows.add(currentRow);
  }
  currentRow = [{'content': item.str, 'x': item.x, 'y': item.y}];
  currentY = item.y;
  }
  }
  if (currentRow.isNotEmpty) {
  currentRow.sort((dynamic a, dynamic b) => a.x - b.x);
  rows.add(currentRow);
  }
  return rows;
}

List<List<String>> detectColumns(List<PdfTableRow> rows, [num _xTolerance = 10], [num minColumnWidth = 30]) {
  if (rows.isEmpty) {
  return [];
  }
  final xPositions = Set();
  for (final row in rows) {
  for (final cell in row) {
  xPositions.add(cell.x);
  }
  }
  final sortedX = Array.from(xPositions).sort((dynamic a, dynamic b) => a - b);
  List<num> boundaries = [sortedX[0]];
  for (var i = 1; i < sortedX.length; i++) {
  if (sortedX[i] - sortedX[i - 1] >= minColumnWidth) {
  boundaries.add(sortedX[i]);
  }
  }
  List<List<String>> table = [];
  for (final row in rows) {
  List<String> cells = Array(boundaries.length).fill('');
  for (final cell in row) {
  final colIndex = findColumnIndex(cell.x, boundaries);
  if (colIndex != -1) {
  if (cells[colIndex] != null) {
  cells[colIndex] += ' ' + cell.content;
  } else {
  cells[colIndex] = cell.content;
  }
  }
  }
  final cleaned = cells.map((dynamic c) => c.replaceAll(RegExp(r'\n'), '').trim()).toList();
  table.add(cleaned);
  }
  return table;
}

List<List<String>> filterHeaderRows(List<List<String>> table, dynamic? headerFirstCell) {
  return table.where((dynamic row) { if (row.isEmpty) {
  return false;
  }
  final firstCell = row[0];
  if (headerFirstCell) {
  if (headerFirstCell is String && firstCell == headerFirstCell) {
  return false;
  }
  if (headerFirstCell is RegExp && headerFirstCell.hasMatch(firstCell)) {
  return false;
  }
  }
  return true; }).toList();
}

Future<PdfTableReadResult> readPdfTable(dynamic buffer, [PdfTableReadOptions options = {}]) {
  final _obj = options;
  final headerFirstCell = _obj.headerFirstCell;
  final yTolerance = _obj.yTolerance;
  final xTolerance = _obj.xTolerance;
  final minColumnWidth = _obj.minColumnWidth;
  final textResult = /* TODO: AwaitExpression: await extractPdfText(buffer) */;
  if (!textResult.success) {
  return textResult;
  }
  final _obj = textResult.value;
  final items = _obj.items;
  final fullText = _obj.fullText;
  final rows = clusterIntoRows(items, yTolerance);
  final table = detectColumns(rows, xTolerance, minColumnWidth);
  final filteredTable = filterHeaderRows(table, headerFirstCell);
  return ok({'rows': filteredTable});
}

num findColumnIndex(num x, List<num> boundaries) {
  for (var i = boundaries.length - 1; i >= 0; i--) {
  if (x >= boundaries[i]) {
  return i;
  }
  }
  return -1;
}
