// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.906Z
// Source: TypeScript parser
// Parser: hsbc-hk

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, ParseResult, ParseFailure, ParseError, ParseWarning;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

abstract class HsbcHkCustomFields implements Map<String, dynamic> {
  dynamic get paymentMethod;
  DateTime get postDate;
  String get transactionStatus;
  String get country;
  String get area;
  String get balanceAfter;
}

typedef HsbcHkRawTransaction = RawTransaction<HsbcHkCustomFields>;

typedef FormatType = dynamic;

final List<String> HSBC_HK_KEYWORDS = ['Billing currency', 'Description'];

class HsbcHkParser implements Parser<HsbcHkRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    return HSBC_HK_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
  }
  
  ParseResult<HsbcHkRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final { rows, formatType, dateField } = rowsResult.value;
    List<HsbcHkRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum, formatType, dateField);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': JSON.stringify(row), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic _parseRows(String content) {
    try {
    List<Map<String, dynamic>> rows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'columns': true, 'relax_column_count': true});
    if (rows.isEmpty) {
    List<List<String>> headerRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true});
    if (headerRows.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV file is empty or has no header'});
    }
    final headers = headerRows[0];
    final detectedFormatType = this.detectFormatType(headers);
    final detectedDateField = headers.contains('Transaction date') ? 'Transaction date' : 'Date';
    return ok({'rows': [], 'formatType': detectedFormatType, 'dateField': detectedDateField});
    }
    final columns = Object.keys(rows[0]);
    final formatType = this.detectFormatType(columns);
    final dateField = columns.contains('Transaction date') ? 'Transaction date' : 'Date';
    return ok({});
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  FormatType _detectFormatType(List<String> columns) {
    if (columns.contains('Transaction date')) {
    return 'Credit';
    }
    return 'Debit';
  }
  
  dynamic _transformRow(Map<String, dynamic> row, num _lineNum, FormatType formatType, String dateField) {
    final dateStr = row[dateField];
    if (dateStr.isEmpty) {
    return err({'message': 'Missing date field: $dateField', 'context': {}});
    }
    final dateResult = parseDate(dateStr);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': dateStr}});
    }
    final currency = row['Billing currency'].trim();
    if (currency.isEmpty) {
    return err({'message': 'Missing Billing currency field', 'context': {}});
    }
    final amountStr = row['Billing amount'].trim();
    if (amountStr.isEmpty) {
    return err({'message': 'Missing Billing amount field', 'context': {}});
    }
    Decimal amount;
    try {
    amount = Decimal(amountStr);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr', 'context': {'input': amountStr}});
    }
    final description = row['Description'].trim() ?? '';
    HsbcHkCustomFields customFields = {};
    Map<String, dynamic> metadata = {};
    if (description.toUpperCase().contains('UNIONPAY')) {
    customFields.paymentMethod = 'UnionPay';
    } else if (description.toUpperCase().contains('APPLE PAY')) {
    customFields.paymentMethod = 'Apple Pay';
    }
    String? payee;
    if (formatType == 'Credit') {
    payee = row['Merchant name'].trim() ?? null;
    final status = row['Transaction status'].trim();
    if (status) {
    customFields.transactionStatus = status;
    }
    final postDateStr = row['Post date'].trim();
    if (postDateStr) {
    final postDateResult = parseDate(postDateStr);
    if (postDateResult.success) {
    customFields.postDate = postDateResult.value;
    }
    }
    final country = row['Country / region'].trim();
    if (country) {
    customFields.country = country;
    }
    final area = row['Area / district'].trim();
    if (area) {
    customFields.area = area;
    }
    } else {
    final balanceStr = row['Balance'].trim();
    if (balanceStr) {
    metadata['balanceAfter'] = '$balanceStr $currency';
    }
    }
    HsbcHkRawTransaction transaction = {'date': dateResult.value, 'metadata': Object.keys(metadata).isNotEmpty ? metadata : null, 'customFields': Object.keys(customFields).isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
