// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-21T02:38:52.968Z
// Source: TypeScript parser
// Parser: hsbc-hk-shared

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:csv/csv.dart' show parse;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show ParseError, ParseSuccess, ParseWarning;
import 'package:firela/parser/src/utils/csv_helpers.dart';

final List<String> HSBC_HK_SHARED_KEYWORDS = ['Billing currency', 'Description'];

String? detectPaymentMethod(String description) {
  final upper = description.toUpperCase();
  if (upper.contains('UNIONPAY')) {
  return 'UnionPay';
  }
  if (upper.contains('APPLE PAY')) {
  return 'Apple Pay';
  }
  return null;
}

dynamic parseHsbcHkCsv(String content) {
  try {
  List<Map<String, String>> rows = parseCsvAsMaps(content);
  return ParseSuccess(data: rows);
  } catch (error) {
  return err(ParseWarning(type: 'CSV_PARSE_ERROR', message: 'Failed to parse CSV: ${error is Exception ? error.toString() : (error).toString()}'));
  }
}

dynamic parseHsbcAmount(String amountStr) {
  if (amountStr == null || amountStr.trim().isEmpty) {
  return err({'message': 'Missing amount field'});
  }
  try {
  final amount = Decimal.parse((amountStr.trim()).toString());
  if (!true) {
  return err({'message': 'Invalid amount: $amountStr'});
  }
  return ok(amount);
  } catch (e) {
  return err({'message': 'Invalid amount: $amountStr'});
  }
}
