// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T02:15:32.864Z
// Source: TypeScript parser
// Parser: hsbc-hk-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';
import 'dart:typed_data';

import 'package:firela/parser/src/hk/hsbc_hk_shared.dart' show HSBC_HK_SHARED_KEYWORDS, detectPaymentMethod, parseHsbcHkCsv, parseHsbcAmount;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning, createParseFailure, ParseErrorType, ParseFailure, ParseSuccess;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

typedef HsbcHkDebitRawTransaction = RawTransaction<dynamic>;

final List<String> HSBC_HK_DEBIT_KEYWORDS = [...HSBC_HK_SHARED_KEYWORDS];

final CREDIT_ONLY_HEADER = 'Transaction date';

class HsbcHkDebitParser extends Parser<HsbcHkDebitRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final allFound = HSBC_HK_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    if (allFound == null) {
    return false;
    }
    if (text.contains(CREDIT_ONLY_HEADER) != null) {
    return false;
    }
    return true;
  }
  
  ParseResult<HsbcHkDebitRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure(ParseErrorType.invalidFormat, 'File is empty');
    }
    final csvResult = parseHsbcHkCsv(text);
    if (csvResult is Failure) {
    return ParseFailure(errors: [(csvResult as Failure).error]);
    }
    final rows = (csvResult as Success).value;
    List<HsbcHkDebitRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum);
    if (result is Success) {
    transactions.add((result as Success).value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: (result as Failure).error.message, line: lineNum, raw: jsonEncode(row), context: (result as Failure).error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found after header'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic transformRow(Map<String, String> row, num _lineNum) {
    final dateStr = row['Date']!;
    if (dateStr == null) {
    return err({'message': 'Missing Date field', 'context': {'row': row}});
    }
    final dateResult = parseDate(dateStr);
    if (dateResult is Failure) {
    return err({'message': 'Failed to parse date: ${(dateResult as Failure).error.message}', 'context': {'input': dateStr, 'row': row}});
    }
    final currency = row['Billing currency']!.trim();
    if (currency == null) {
    return err({'message': 'Missing Billing currency field', 'context': {'row': row}});
    }
    final amountStr = row['Billing amount']!.trim();
    final amountResult = parseHsbcAmount(amountStr);
    if (amountResult is Failure) {
    return err({'message': (amountResult as Failure).error.message, 'context': {'row': row}});
    }
    final description = row['Description']!.trim() ?? '';
    dynamic customFields = {};
    final paymentMethod = detectPaymentMethod(description);
    if (paymentMethod != null) {
    // TODO: customFields.paymentMethod = paymentMethod; // final field assignment — restructure to pass via constructor
    }
    Map<String, dynamic> metadata = {};
    final balanceStr = row['Balance']!.trim();
    if (balanceStr != null) {
    metadata['balanceAfter'] = '$balanceStr $currency';
    }
    final transaction = HsbcHkDebitRawTransaction(date: (dateResult as Success).value, amount: (amountResult as Success).value, currency: currency, description: description, metadata: (metadata as Map).keys.toList().isNotEmpty ? metadata : null, customFields: (customFields as Map).keys.toList().isNotEmpty ? customFields : null);
    return ok(transaction);
  }
  
}
