// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T06:41:41.697Z
// Source: TypeScript parser
// Parser: hsbc-hk-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning, createParseFailure;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import '../../types/bank.dart' show HsbcHkCreditCustomFields;
import './hsbc_hk_shared.dart' show HSBC_HK_SHARED_KEYWORDS, detectPaymentMethod, parseHsbcHkCsv, parseHsbcAmount;

typedef HsbcHkCreditRawTransaction = RawTransaction<HsbcHkCreditCustomFields>;

final List<String> HSBC_HK_CREDIT_KEYWORDS = [/* TODO: expression */, 'Transaction date'];

class HsbcHkCreditParser extends Parser<HsbcHkCreditRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final allFound = HSBC_HK_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    if (allFound == null) {
    return false;
    }
    return true;
  }
  
  ParseResult<HsbcHkCreditRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final csvResult = parseHsbcHkCsv(text);
    if (!csvResult.success) {
    return ParseFailure(errors: [csvResult.error]);
    }
    final rows = csvResult.value;
    List<HsbcHkCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: result.error.message, line: lineNum, raw: jsonEncode(row), context: result.error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found after header'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic transformRow(Map<String, dynamic> row, num _lineNum) {
    final dateStr = row['Transaction date'];
    if (dateStr == null) {
    return err({'message': 'Missing Transaction date field', 'context': {}});
    }
    final dateResult = parseDate(dateStr);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': dateStr}});
    }
    final currency = row['Billing currency'].trim();
    if (currency == null) {
    return err({'message': 'Missing Billing currency field', 'context': {}});
    }
    final amountStr = row['Billing amount'].trim();
    final amountResult = parseHsbcAmount(amountStr);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    final description = row['Description'].trim() ?? '';
    final payee = row['Merchant name'].trim() ?? null;
    HsbcHkCreditCustomFields customFields = {};
    final paymentMethod = detectPaymentMethod(description);
    if (paymentMethod) {
    customFields.paymentMethod = paymentMethod;
    }
    final status = row['Transaction status'].trim();
    if (status) {
    customFields.transactionStatus = status;
    }
    final postDateStr = row['Post date'].trim();
    if (postDateStr) {
    final postDateResult = parseDate(postDateStr);
    if (postDateResult.success != null) {
    customFields.postDate = postDateResult.value;
    }
    }
    final country = row['Country / region'].trim();
    if (country) {
    customFields.country = country;
    }
    final area = row['Area / district'].trim();
    if (area) {
    customFields.area = area;
    }
    final transaction = {'date': dateResult.value, 'amount': amountResult.value, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ParseSuccess(data: transaction);
  }
  
}
