// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T02:15:33.143Z
// Source: TypeScript parser
// Parser: hsbc-hk-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';
import 'dart:typed_data';

import 'package:firela/parser/src/hk/hsbc_hk_shared.dart' show HSBC_HK_SHARED_KEYWORDS, detectPaymentMethod, parseHsbcHkCsv, parseHsbcAmount;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning, createParseFailure, ParseErrorType, ParseFailure, ParseSuccess;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

typedef HsbcHkCreditRawTransaction = RawTransaction<dynamic>;

final List<String> HSBC_HK_CREDIT_KEYWORDS = [...HSBC_HK_SHARED_KEYWORDS, 'Transaction date'];

class HsbcHkCreditParser extends Parser<HsbcHkCreditRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final allFound = HSBC_HK_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    if (allFound == null) {
    return false;
    }
    return true;
  }
  
  ParseResult<HsbcHkCreditRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure(ParseErrorType.invalidFormat, 'File is empty');
    }
    final csvResult = parseHsbcHkCsv(text);
    if (csvResult is Failure) {
    return ParseFailure(errors: [(csvResult as Failure).error]);
    }
    final rows = (csvResult as Success).value;
    List<HsbcHkCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum);
    if (result is Success) {
    transactions.add((result as Success).value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: (result as Failure).error.message, line: lineNum, raw: jsonEncode(row), context: (result as Failure).error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found after header'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic transformRow(Map<String, String> row, num _lineNum) {
    final dateStr = row['Transaction date']!;
    if (dateStr == null) {
    return err({'message': 'Missing Transaction date field', 'context': {'row': row}});
    }
    final dateResult = parseDate(dateStr);
    if (dateResult is Failure) {
    return err({'message': 'Failed to parse date: ${(dateResult as Failure).error.message}', 'context': {'input': dateStr, 'row': row}});
    }
    final currency = row['Billing currency']!.trim();
    if (currency == null) {
    return err({'message': 'Missing Billing currency field', 'context': {'row': row}});
    }
    final amountStr = row['Billing amount']!.trim();
    final amountResult = parseHsbcAmount(amountStr);
    if (amountResult is Failure) {
    return err({'message': (amountResult as Failure).error.message, 'context': {'row': row}});
    }
    final description = row['Description']!.trim() ?? '';
    final payee = row['Merchant name']!.trim() ?? null;
    dynamic customFields = {};
    final paymentMethod = detectPaymentMethod(description);
    if (paymentMethod != null) {
    // TODO: customFields.paymentMethod = paymentMethod; // final field assignment — restructure to pass via constructor
    }
    final status = row['Transaction status']!.trim();
    if (status != null) {
    // TODO: customFields.transactionStatus = status; // final field assignment — restructure to pass via constructor
    }
    final postDateStr = row['Post date']!.trim();
    if (postDateStr != null) {
    final postDateResult = parseDate(postDateStr);
    if (postDateResult is Success) {
    // TODO: customFields.postDate = (postDateResult as Success).value; // final field assignment — restructure to pass via constructor
    }
    }
    final country = row['Country / region']!.trim();
    if (country != null) {
    // TODO: customFields.country = country; // final field assignment — restructure to pass via constructor
    }
    final area = row['Area / district']!.trim();
    if (area != null) {
    // TODO: customFields.area = area; // final field assignment — restructure to pass via constructor
    }
    final transaction = HsbcHkCreditRawTransaction(date: (dateResult as Success).value, amount: (amountResult as Success).value, currency: currency, description: description, payee: payee, customFields: (customFields as Map).keys.toList().isNotEmpty ? customFields : null);
    return ok(transaction);
  }
  
}
