// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:39.091Z
// Source: TypeScript parser
// Parser: hsbc-hk-shared

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:csv/csv.dart' show parse;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show ParseError;

final List<String> HSBC_HK_SHARED_KEYWORDS = ['Billing currency', 'Description'];

String? detectPaymentMethod(String description) {
  final upper = description.toUpperCase();
  if (upper.contains('UNIONPAY')) {
  return 'UnionPay';
  }
  if (upper.contains('APPLE PAY')) {
  return 'Apple Pay';
  }
  return null;
}

dynamic parseHsbcHkCsv(String content) {
  try {
  final rows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'columns': true, 'relax_column_count': true});
  return ok(rows);
  } catch (error) {
  return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : (error).toString()}'});
  }
}

dynamic parseHsbcAmount(String amountStr) {
  if (amountStr == null || amountStr.trim().isEmpty) {
  return err({'message': 'Missing amount field'});
  }
  try {
  final amount = Decimal(amountStr.trim());
  if (!amount.isFinite()) {
  return err({'message': 'Invalid amount: $amountStr'});
  }
  return ok(amount);
  } catch (e) {
  return err({'message': 'Invalid amount: $amountStr'});
  }
}
