// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-21T06:23:10.563Z
// Source: TypeScript parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/cn/alipay_custom_fields.dart' show AlipayCustomFields;
import 'package:firela/parser/src/result.dart' show Result;

typedef EncodingErrorType = String;

class EncodingError {
  final EncodingErrorType type;
  final String message;
  final String? details;
  const EncodingError({required this.type, required this.message, this.details});
}

typedef EncodingDetectionResult = Result<String, EncodingError>;

typedef EncodingConversionResult = Result<String, EncodingError>;

typedef DateParseErrorType = String;

class DateParseError {
  final DateParseErrorType type;
  final String message;
  final String input;
  const DateParseError({required this.type, required this.message, required this.input});
}

typedef DateParseResult = Result<DateTime, DateParseError>;

typedef AmountParseErrorType = String;

class AmountParseError {
  final AmountParseErrorType type;
  final String message;
  final String input;
  const AmountParseError({required this.type, required this.message, required this.input});
}

class ParsedAmount {
  final Decimal number;
  final String currency;
  const ParsedAmount({required this.number, required this.currency});
}

typedef AmountParseResult = Result<ParsedAmount, AmountParseError>;

typedef DecimalParseResult = Result<Decimal, AmountParseError>;

class CsvReadOptions {
  final String? encoding;
  final String? delimiter;
  final String? quote;
  final String? escape;
  final num? skipLines;
  final num? skipFooterLines;
  final bool? hasHeader;
  final String? comment;
  final bool? trim;
  final bool? skipEmptyLines;
  const CsvReadOptions({this.encoding, this.delimiter, this.quote, this.escape, this.skipLines, this.skipFooterLines, this.hasHeader, this.comment, this.trim, this.skipEmptyLines});
}

class CsvReadError {
  final String type;
  final String message;
  final num? line;
  const CsvReadError({required this.type, required this.message, this.line});
}
