// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T09:04:30.668Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart' show Result;

class AlipayCustomFields {
  final String status;
  final String? category;
  final String? orderNo;
  final String? merchantOrderNo;
  const AlipayCustomFields({required this.status, this.category, this.orderNo, this.merchantOrderNo});
}

class WeChatCustomFields {
  final String status;
  final String? transactionType;
  final String? orderNo;
  const WeChatCustomFields({required this.status, this.transactionType, this.orderNo});
}

class DetectionResult {
  final num confidence;
  final String? formatVersion;
  final String institutionId;
  const DetectionResult({required this.confidence, this.formatVersion, required this.institutionId});
}

class StructuralFingerprint {
  final num columns;
  final String delimiter;
  final String encoding;
  final String headerHash;
  const StructuralFingerprint({required this.columns, required this.delimiter, required this.encoding, required this.headerHash});
}

typedef EncodingErrorType = String;

class EncodingError {
  final EncodingErrorType type;
  final String message;
  final String? details;
  const EncodingError({required this.type, required this.message, this.details});
}

typedef EncodingDetectionResult = Result<String, EncodingError>;

typedef EncodingConversionResult = Result<String, EncodingError>;

typedef DateParseErrorType = String;

class DateParseError {
  final DateParseErrorType type;
  final String message;
  final String input;
  const DateParseError({required this.type, required this.message, required this.input});
}

typedef DateParseResult = Result<DateTime, DateParseError>;

typedef AmountParseErrorType = String;

class AmountParseError {
  final AmountParseErrorType type;
  final String message;
  final String input;
  const AmountParseError({required this.type, required this.message, required this.input});
}

class ParsedAmount {
  final Decimal number;
  final String currency;
  const ParsedAmount({required this.number, required this.currency});
}

typedef AmountParseResult = Result<ParsedAmount, AmountParseError>;

typedef DecimalParseResult = Result<Decimal, AmountParseError>;

class CsvReadOptions {
  final String? encoding;
  final String? delimiter;
  final String? quote;
  final String? escape;
  final num? skipLines;
  final num? skipFooterLines;
  final bool? hasHeader;
  final String? comment;
  final bool? trim;
  final bool? skipEmptyLines;
  const CsvReadOptions({this.encoding, this.delimiter, this.quote, this.escape, this.skipLines, this.skipFooterLines, this.hasHeader, this.comment, this.trim, this.skipEmptyLines});
}

class CsvReadError {
  final String type;
  final String message;
  final num? line;
  const CsvReadError({required this.type, required this.message, this.line});
}
