// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T09:04:27.026Z
// Source: TypeScript parser
// Parser: degiro-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/core/csv_parser_base.dart' show CsvParser, CsvParserConfig, RowTransformResult;
import 'package:firela/parser/src/eu/types.dart' show DegiroRawTransaction, DegiroCustomFields;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

final MIN_REQUIRED_COLUMNS = 10;

final List<String> DEGIRO_KEYWORDS = ['Date', 'Product', 'ISIN'];

final Map<String, String> TX_TYPE_KEYWORDS = {'BUY': 'BUY', 'SELL': 'SELL', 'PURCHASE': 'BUY', 'SALE': 'SELL', 'DIVIDEND': 'DIVIDEND', 'FEE': 'FEE', 'COMMISSION': 'FEE', 'TAX': 'TAX', 'INTEREST': 'INTEREST', 'DEPOSIT': 'DEPOSIT', 'CREDIT': 'DEPOSIT', 'WITHDRAWAL': 'WITHDRAWAL', 'DEBIT': 'WITHDRAWAL', 'FX': 'FOREX', 'CURRENCY': 'FOREX', 'FOREX': 'FOREX', 'CORPORATE': 'CORPORATE_ACTION', 'MERGER': 'CORPORATE_ACTION'};

class DegiroParser extends CsvParser<DegiroRawTransaction> {
  // ignore: invalid_assignment
  late final config = {'institutionId': 'degiro', 'identifyKeywords': ['Date', 'Product', 'ISIN'], 'minColumns': MIN_REQUIRED_COLUMNS, 'columns': {'date': {'names': ['Date'], 'fallbackIndex': 0, 'required': true}, 'time': {'names': ['Time'], 'fallbackIndex': 1}, 'product': {'names': ['Product'], 'fallbackIndex': 2}, 'isin': {'names': ['ISIN'], 'fallbackIndex': 3}, 'reference': {'names': ['Reference'], 'fallbackIndex': 4}, 'venue': {'names': ['Venue'], 'fallbackIndex': 5}, 'quantity': {'names': ['Quantity'], 'fallbackIndex': 6}, 'price': {'names': ['Price'], 'fallbackIndex': 7}, 'localValue': {'names': ['Local Value'], 'fallbackIndex': 8}, 'value': {'names': ['Value'], 'fallbackIndex': 9}, 'exchangeRate': {'names': ['Exchange Rate'], 'fallbackIndex': 10}, 'transactionType': {'names': ['Transaction and/or third'], 'fallbackIndex': 11}, 'total': {'names': ['Total'], 'fallbackIndex': 12}, 'orderId': {'names': ['Order ID'], 'fallbackIndex': 13}}, 'transformRow': (dynamic row, dynamic columnMap) {
  return this.doTransformRow(row, columnMap);
}};
  RowTransformResult doTransformRow(List<String> row, Map<String, num> columnMap) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {'row': row}});
    }
    final dateStr = this.getColumnValue(row, columnMap, 'date') ?? '';
    final timeStr = this.getColumnValue(row, columnMap, 'time') ?? '';
    final product = this.getColumnValue(row, columnMap, 'product') ?? '';
    final isin = this.getColumnValue(row, columnMap, 'isin') ?? '';
    final reference = this.getColumnValue(row, columnMap, 'reference') ?? '';
    final venue = this.getColumnValue(row, columnMap, 'venue') ?? '';
    final quantityStr = this.getColumnValue(row, columnMap, 'quantity') ?? '';
    final priceStr = this.getColumnValue(row, columnMap, 'price') ?? '';
    final localValueStr = this.getColumnValue(row, columnMap, 'localValue') ?? '';
    final valueStr = this.getColumnValue(row, columnMap, 'value') ?? '';
    final exchangeRateStr = this.getColumnValue(row, columnMap, 'exchangeRate') ?? '';
    final transactionType = this.getColumnValue(row, columnMap, 'transactionType') ?? '';
    final totalStr = this.getColumnValue(row, columnMap, 'total') ?? '';
    final orderId = this.getColumnValue(row, columnMap, 'orderId') ?? null;
    final combinedDateStr = '$dateStr $timeStr';
    final dateResult = parseDate(combinedDateStr);
    if (dateResult is Failure) {
    return err({'message': 'Failed to parse date: $combinedDateStr', 'context': {'input': dateStr, 'timeStr': timeStr, 'row': row}});
    }
    num? quantity = null;
    if (quantityStr != null) {
    quantity = this.parseEuropeanNumber(quantityStr);
    if (quantity == null || (quantity).toDouble().isNaN != null) {
    return err({'message': 'Failed to parse quantity: $quantityStr', 'context': {'input': quantityStr, 'row': row}});
    }
    }
    num? price;
    if (priceStr != null) {
    price = this.parseEuropeanNumber(priceStr);
    if ((price).toDouble().isNaN != null) {
    price = null;
    }
    }
    num? localValue;
    if (localValueStr != null) {
    localValue = this.parseEuropeanNumber(localValueStr);
    if ((localValue).toDouble().isNaN != null) {
    localValue = null;
    }
    }
    num? value;
    if (valueStr != null) {
    value = this.parseEuropeanNumber(valueStr);
    if ((value).toDouble().isNaN != null) {
    return err({'message': 'Failed to parse value: $valueStr', 'context': {'input': valueStr, 'row': row}});
    }
    }
    num? exchangeRate;
    if (exchangeRateStr != null) {
    exchangeRate = this.parseEuropeanNumber(exchangeRateStr);
    if ((exchangeRate).toDouble().isNaN != null) {
    exchangeRate = null;
    }
    }
    num? total;
    if (totalStr != null) {
    total = this.parseEuropeanNumber(totalStr);
    if ((total).toDouble().isNaN != null) {
    return err({'message': 'Failed to parse total: $totalStr', 'context': {'input': totalStr, 'row': row}});
    }
    }
    final customFields = DegiroCustomFields(product: product, isin: isin, reference: reference, venue: venue, orderId: orderId, localValue: localValue, exchangeRate: exchangeRate, transactionType: transactionType, price: price);
    final type = this.detectTransactionType(transactionType);
    if (type != null) {
    // TODO: customFields.transactionType = type; // final field assignment — restructure to pass via constructor
    } else {
    // TODO: customFields.transactionType = 'UNKNOWN'; // final field assignment — restructure to pass via constructor
    }
    Map<String, dynamic> metadata = {};
    if (quantity != null) {
    metadata['quantity'] = quantity.toString();
    }
    if (orderId != null) {
    metadata['orderId'] = orderId;
    }
    if (price != null) {
    metadata['price'] = price.toString();
    }
    if (localValue != null) {
    metadata['localValue'] = localValue.toString();
    }
    if (exchangeRate != null) {
    metadata['exchangeRate'] = exchangeRate.toString();
    }
    if (transactionType != null) {
    metadata['transactionType'] = transactionType;
    }
    final transaction = DegiroRawTransaction(date: (dateResult as Success).value, amount: Decimal.parse((total ?? 0).toString()), currency: 'EUR', description: '$product ${transactionType ?? ''}'.trim(), metadata: (metadata as Map).keys.toList().isNotEmpty ? metadata : null, customFields: customFields);
    return ok(transaction);
  }
  
  String? detectTransactionType(String transactionType) {
    if (transactionType == null) {
    return null;
    }
    final upperType = transactionType.toUpperCase();
    for (final entry in (TX_TYPE_KEYWORDS as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final keyword = entry.key;
    final type = entry.value;
    if (upperType.contains(keyword) != null) {
    return type;
    }
    }
    return null;
  }
  
}
