// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T05:26:41.769Z
// Source: TypeScript parser
// Parser: types

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/types.dart' show RawTransaction;

final DEGIRO_COLUMNS = {'DATE': 'Date', 'TIME': 'Time', 'PRODUCT': 'Product', 'ISIN': 'ISIN', 'REFERENCE': 'Reference', 'VENUE': 'Venue', 'QUANTITY': 'Quantity', 'PRICE': 'Price', 'LOCAL_VALUE': 'Local Value', 'VALUE': 'Value', 'EXCHANGE_RATE': 'Exchange Rate', 'TRANSACTION_TYPE': 'Transaction and/or third', 'TOTAL': 'Total', 'ORDER_ID': 'Order ID'};

final DEGIRO_COLUMN_INDICES = {'DATE': 0, 'TIME': 1, 'PRODUCT': 2, 'ISIN': 3, 'REFERENCE': 4, 'VENUE': 5, 'QUANTITY': 6, 'PRICE': 7, 'LOCAL_VALUE': 8, 'VALUE': 9, 'EXCHANGE_RATE': 10, 'TRANSACTION_TYPE': 11, 'TOTAL': 12, 'ORDER_ID': 13};

class DegiroCustomFields {
  final String product;
  final String isin;
  final String reference;
  final String venue;
  final String? orderId;
  final num? localValue;
  final num? exchangeRate;
  final String? transactionType;
  final num? price;
  const DegiroCustomFields({required this.product, required this.isin, required this.reference, required this.venue, this.orderId, this.localValue, this.exchangeRate, this.transactionType, this.price});
}

typedef DegiroRawTransaction = RawTransaction<DegiroCustomFields>;
