// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T06:00:15.198Z
// Source: TypeScript parser
// Parser: degiro-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/csv_parser_base.dart' show CsvParser, CsvParserConfig, RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import './types.dart' show DegiroRawTransaction, DegiroCustomFields;

final MIN_REQUIRED_COLUMNS = 10;

final List<String> DEGIRO_KEYWORDS = ['Date', 'Product', 'ISIN'];

final Map<String, dynamic> TX_TYPE_KEYWORDS = {'BUY': 'BUY', 'SELL': 'SELL', 'PURCHASE': 'BUY', 'SALE': 'SELL', 'DIVIDEND': 'DIVIDEND', 'FEE': 'FEE', 'COMMISSION': 'FEE', 'TAX': 'TAX', 'INTEREST': 'INTEREST', 'DEPOSIT': 'DEPOSIT', 'CREDIT': 'DEPOSIT', 'WITHDRAWAL': 'WITHDRAWAL', 'DEBIT': 'WITHDRAWAL', 'FX': 'FOREX', 'CURRENCY': 'FOREX', 'FOREX': 'FOREX', 'CORPORATE': 'CORPORATE_ACTION', 'MERGER': 'CORPORATE_ACTION'};

class DegiroParser extends CsvParser<DegiroRawTransaction> {
  final config = {'institutionId': 'degiro', 'identifyKeywords': ['Date', 'Product', 'ISIN'], 'minColumns': MIN_REQUIRED_COLUMNS, 'columns': {'date': {'names': ['Date'], 'fallbackIndex': 0, 'required': true}, 'time': {'names': ['Time'], 'fallbackIndex': 1}, 'product': {'names': ['Product'], 'fallbackIndex': 2}, 'isin': {'names': ['ISIN'], 'fallbackIndex': 3}, 'reference': {'names': ['Reference'], 'fallbackIndex': 4}, 'venue': {'names': ['Venue'], 'fallbackIndex': 5}, 'quantity': {'names': ['Quantity'], 'fallbackIndex': 6}, 'price': {'names': ['Price'], 'fallbackIndex': 7}, 'localValue': {'names': ['Local Value'], 'fallbackIndex': 8}, 'value': {'names': ['Value'], 'fallbackIndex': 9}, 'exchangeRate': {'names': ['Exchange Rate'], 'fallbackIndex': 10}, 'transactionType': {'names': ['Transaction and/or third'], 'fallbackIndex': 11}, 'total': {'names': ['Total'], 'fallbackIndex': 12}, 'orderId': {'names': ['Order ID'], 'fallbackIndex': 13}}, 'transformRow': (dynamic row, dynamic columnMap) {
  // TODO: Handle CallExpression
}};
  RowTransformResult<DegiroRawTransaction> doTransformRow(List<String> row, Map<String, num> columnMap) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final dateStr = this.getColumnValue(row, columnMap, 'date') ?? '';
    final timeStr = this.getColumnValue(row, columnMap, 'time') ?? '';
    final product = this.getColumnValue(row, columnMap, 'product') ?? '';
    final isin = this.getColumnValue(row, columnMap, 'isin') ?? '';
    final reference = this.getColumnValue(row, columnMap, 'reference') ?? '';
    final venue = this.getColumnValue(row, columnMap, 'venue') ?? '';
    final quantityStr = this.getColumnValue(row, columnMap, 'quantity') ?? '';
    final priceStr = this.getColumnValue(row, columnMap, 'price') ?? '';
    final localValueStr = this.getColumnValue(row, columnMap, 'localValue') ?? '';
    final valueStr = this.getColumnValue(row, columnMap, 'value') ?? '';
    final exchangeRateStr = this.getColumnValue(row, columnMap, 'exchangeRate') ?? '';
    final transactionType = this.getColumnValue(row, columnMap, 'transactionType') ?? '';
    final totalStr = this.getColumnValue(row, columnMap, 'total') ?? '';
    final orderId = this.getColumnValue(row, columnMap, 'orderId') ?? null;
    final combinedDateStr = '$dateStr $timeStr';
    final dateResult = parseDate(combinedDateStr);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: $combinedDateStr', 'context': {'input': dateStr}});
    }
    num? quantity = null;
    if (quantityStr) {
    quantity = this.parseEuropeanNumber(quantityStr);
    if (quantity == null || quantity.isNaN) {
    return err({'message': 'Failed to parse quantity: $quantityStr', 'context': {'input': quantityStr}});
    }
    }
    num? price;
    if (priceStr) {
    price = this.parseEuropeanNumber(priceStr);
    if (price.isNaN) {
    price = null;
    }
    }
    num? localValue;
    if (localValueStr) {
    localValue = this.parseEuropeanNumber(localValueStr);
    if (localValue.isNaN) {
    localValue = null;
    }
    }
    num? value;
    if (valueStr) {
    value = this.parseEuropeanNumber(valueStr);
    if (value.isNaN) {
    return err({'message': 'Failed to parse value: $valueStr', 'context': {'input': valueStr}});
    }
    }
    num? exchangeRate;
    if (exchangeRateStr) {
    exchangeRate = this.parseEuropeanNumber(exchangeRateStr);
    if (exchangeRate.isNaN) {
    exchangeRate = null;
    }
    }
    num? total;
    if (totalStr) {
    total = this.parseEuropeanNumber(totalStr);
    if (total.isNaN) {
    return err({'message': 'Failed to parse total: $totalStr', 'context': {'input': totalStr}});
    }
    }
    DegiroCustomFields customFields = {};
    final type = this.detectTransactionType(transactionType);
    if (type) {
    customFields.transactionType = type;
    } else {
    customFields.transactionType = 'UNKNOWN';
    }
    Map<String, dynamic> metadata = {};
    if (quantity) {
    metadata['quantity'] = quantity.toString();
    }
    if (orderId) {
    metadata['orderId'] = orderId;
    }
    if (price) {
    metadata['price'] = price.toString();
    }
    if (localValue) {
    metadata['localValue'] = localValue.toString();
    }
    if (exchangeRate) {
    metadata['exchangeRate'] = exchangeRate.toString();
    }
    if (transactionType) {
    metadata['transactionType'] = transactionType;
    }
    final transaction = {'date': dateResult.value, 'amount': Decimal.parse(total ?? 0), 'currency': 'EUR', 'description': '$product ${transactionType ?? ''}'.trim(), 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  String? detectTransactionType(String transactionType) {
    if (transactionType == null) {
    return null;
    }
    final upperType = transactionType.toUpperCase();
    for (final entry in (TX_TYPE_KEYWORDS as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final keyword = entry.key;
    final type = entry.value;
    if (upperType.contains(keyword)) {
    return type;
    }
    }
    return null;
  }
  
}
