// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.489Z
// Source: TypeScript parser
// Parser: degiro

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:csv/csv.dart' show detectDelimiter;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, ParseResult, ParseFailure, ParseError, ParseWarning;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import './types.dart' show DegiroRawTransaction, DegiroCustomFields, DEGIRO_COLUMNS, DEGIRO_COLUMN_INDICES;

final List<String> DEGIRO_KEYWORDS = [DEGIRO_COLUMNS.DATE, DEGIRO_COLUMNS.PRODUCT, DEGIRO_COLUMNS.ISIN];

final MIN_REQUIRED_COLUMNS = 10;

class DegiroParser implements Parser<DegiroRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    return DEGIRO_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
  }
  
  ParseResult<DegiroRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final delimiter = detectDelimiter(text);
    final rowsResult = this.parseRows(text, delimiter);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final { rows, columnMap } = rowsResult.value;
    List<DegiroRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum, columnMap);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': JSON.stringify(row), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic _parseRows(String content, String delimiter) {
    try {
    List<List<String>> rows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'columns': false});
    if (rows.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV file is empty'});
    }
    final headers = rows[0] ?? [];
    final dataRows = rows.slice(1);
    final columnMap = this.buildColumnMap(headers);
    if (columnMap.has(DEGIRO_COLUMNS.DATE).isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'Missing required column: ${DEGIRO_COLUMNS.DATE}'});
    }
    return ok({'rows': dataRows});
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  Map<String, num> _buildColumnMap(List<String> headers) {
    final columnNames = (Object.values(DEGIRO_COLUMNS) as List<String>);
    final map = Map();
    headers.forEach((dynamic header, dynamic index) { final trimmedHeader = header.trim();
    if (trimmedHeader && columnNames.contains(trimmedHeader)) {
    map.set(trimmedHeader, index);
    } });
    return map;
  }
  
  String _getColumnValue(List<String> row, Map<String, num> columnMap, String name, num? fallbackIndex) {
    final index = columnMap.get(name);
    if (index != null) {
    return row[index] ?? '';
    }
    if (fallbackIndex != null && fallbackIndex < row.length) {
    return row[fallbackIndex] ?? '';
    }
    return '';
  }
  
  dynamic _transformRow(List<String> row, num _lineNum, Map<String, num> columnMap) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final dateStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.DATE, DEGIRO_COLUMN_INDICES.DATE) ?? '';
    final timeStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.TIME, DEGIRO_COLUMN_INDICES.TIME) ?? '';
    final product = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.PRODUCT, DEGIRO_COLUMN_INDICES.PRODUCT) ?? '';
    final isin = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.ISIN, DEGIRO_COLUMN_INDICES.ISIN) ?? '';
    final reference = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.REFERENCE, DEGIRO_COLUMN_INDICES.REFERENCE) ?? '';
    final venue = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.VENUE, DEGIRO_COLUMN_INDICES.VENUE) ?? '';
    final quantityStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.QUANTITY, DEGIRO_COLUMN_INDICES.QUANTITY) ?? '';
    final priceStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.PRICE, DEGIRO_COLUMN_INDICES.PRICE) ?? '';
    final localValueStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.LOCAL_VALUE, DEGIRO_COLUMN_INDICES.LOCAL_VALUE) ?? '';
    final valueStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.VALUE, DEGIRO_COLUMN_INDICES.VALUE) ?? '';
    final exchangeRateStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.EXCHANGE_RATE, DEGIRO_COLUMN_INDICES.EXCHANGE_RATE) ?? '';
    final transactionType = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.TRANSACTION_TYPE, DEGIRO_COLUMN_INDICES.TRANSACTION_TYPE) ?? '';
    final totalStr = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.TOTAL, DEGIRO_COLUMN_INDICES.TOTAL) ?? '';
    final orderId = this.getColumnValue(row, columnMap, DEGIRO_COLUMNS.ORDER_ID, DEGIRO_COLUMN_INDICES.ORDER_ID) ?? null;
    final combinedDateStr = '$dateStr $timeStr';
    final dateResult = parseDate(combinedDateStr);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: $combinedDateStr', 'context': {'input': dateStr}});
    }
    num? quantity = null;
    if (quantityStr) {
    quantity = this.parseEuropeanNumber(quantityStr);
    if (quantity == null || isNaN(quantity)) {
    return err({'message': 'Failed to parse quantity: $quantityStr', 'context': {'input': quantityStr}});
    }
    }
    num? price;
    if (priceStr) {
    price = this.parseEuropeanNumber(priceStr);
    if (isNaN(price)) {
    price = null;
    }
    }
    num? localValue;
    if (localValueStr) {
    localValue = this.parseEuropeanNumber(localValueStr);
    if (isNaN(localValue)) {
    localValue = null;
    }
    }
    num? value;
    if (valueStr) {
    value = this.parseEuropeanNumber(valueStr);
    if (isNaN(value)) {
    return err({'message': 'Failed to parse value: $valueStr', 'context': {'input': valueStr}});
    }
    }
    num? exchangeRate;
    if (exchangeRateStr) {
    exchangeRate = this.parseEuropeanNumber(exchangeRateStr);
    if (isNaN(exchangeRate)) {
    exchangeRate = null;
    }
    }
    num? total;
    if (totalStr) {
    total = this.parseEuropeanNumber(totalStr);
    if (isNaN(total)) {
    return err({'message': 'Failed to parse total: $totalStr', 'context': {'input': totalStr}});
    }
    }
    DegiroCustomFields customFields = {};
    final type = this.detectTransactionType(transactionType);
    if (type) {
    customFields.transactionType = type;
    } else {
    customFields.transactionType = 'UNKNOWN';
    }
    Map<String, dynamic> metadata = {};
    if (quantity) {
    metadata['quantity'] = quantity.toString();
    }
    if (orderId) {
    metadata['orderId'] = orderId;
    }
    if (price) {
    metadata['price'] = price.toString();
    }
    if (localValue) {
    metadata['localValue'] = localValue.toString();
    }
    if (exchangeRate) {
    metadata['exchangeRate'] = exchangeRate.toString();
    }
    if (transactionType) {
    metadata['transactionType'] = transactionType;
    }
    DegiroRawTransaction transaction = {'date': dateResult.value, 'amount': Decimal(total ?? 0), 'currency': 'EUR', 'description': '$product ${transactionType ?? ''}'.trim(), 'metadata': Object.keys(metadata).isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  num _parseEuropeanNumber(String value) {
    if (value.isEmpty || value.trim() == '') {
    return NaN;
    }
    final withoutCurrency = value.replaceFirst(RegExp(r'^[A-Z]{3}\s*', 'i'), '');
    final normalized = withoutCurrency.replaceAll(RegExp(r'\s'), '').replaceAll(RegExp(r','), '.').replaceAll(RegExp(r'\.(?=.*\.)'), '');
    return parseFloat(normalized);
  }
  
  String? _detectTransactionType(String transactionType) {
    if (transactionType.isEmpty) {
    return null;
    }
    final upperType = transactionType.toUpperCase();
    if (upperType.contains('BUY') || upperType.contains('PURCHASE')) {
    return 'BUY';
    }
    if (upperType.contains('SELL') || upperType.contains('SALE')) {
    return 'SELL';
    }
    if (upperType.contains('DIVIDEND')) {
    return 'DIVIDEND';
    }
    if (upperType.contains('FEE') || upperType.contains('COMMISSION')) {
    return 'FEE';
    }
    if (upperType.contains('TAX')) {
    return 'TAX';
    }
    if (upperType.contains('INTEREST')) {
    return 'INTEREST';
    }
    if (upperType.contains('DEPOSIT') || upperType.contains('CREDIT')) {
    return 'DEPOSIT';
    }
    if (upperType.contains('WITHDRAWAL') || upperType.contains('DEBIT')) {
    return 'WITHDRAWAL';
    }
    if (upperType.contains('FX') || upperType.contains('CURRENCY') || upperType.contains('FOREX')) {
    return 'FOREX';
    }
    if (upperType.contains('CORPORATE') || upperType.contains('MERGER')) {
    return 'CORPORATE_ACTION';
    }
    return null;
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
