// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T06:41:36.505Z
// Source: TypeScript parser
// Parser: deutsche-bank-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:math';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/core/csv_parser_base.dart' show CsvParser, CsvParserConfig, RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart';
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import './types.dart' show DeutscheBankRawTransaction, DeutscheBankCustomFields, DB_COLUMNS_EN, DB_COLUMNS_DE, DB_COLUMN_INDICES, DetectedFormat;

final MIN_REQUIRED_COLUMNS = 10;

final List<String> DB_KEYWORDS_EN = [DB_COLUMNS_EN.BOOKING_DATE, DB_COLUMNS_EN.DEBIT, DB_COLUMNS_EN.CREDIT];

final List<String> DB_KEYWORDS_DE = [DB_COLUMNS_DE.BOOKING_DATE, DB_COLUMNS_DE.DEBIT, DB_COLUMNS_DE.CREDIT];

class DeutscheBankParser extends CsvParser<DeutscheBankRawTransaction> {
  final config = {'institutionId': 'deutsche-bank', 'identifyKeywords': [DB_COLUMNS_EN.BOOKING_DATE, DB_COLUMNS_EN.DEBIT, DB_COLUMNS_EN.CREDIT, DB_COLUMNS_DE.BOOKING_DATE, DB_COLUMNS_DE.DEBIT, DB_COLUMNS_DE.CREDIT], 'minColumns': MIN_REQUIRED_COLUMNS, 'detectFormat': (List<String> headers) {
  final enCols = ((DB_COLUMNS_EN as Map).values.toList() as List<String>);
  final deCols = ((DB_COLUMNS_DE as Map).values.toList() as List<String>);
  var englishCount = 0;
  var germanCount = 0;
  for (final h in headers) {
  final trimmed = h.trim();
  if (enCols.contains(trimmed)) {
  englishCount++;
  }
  if (deCols.contains(trimmed)) {
  germanCount++;
  }
  }
  if (englishCount > germanCount) {
  return 'english';
  }
  if (germanCount > englishCount) {
  return 'german';
  }
  return null;
}, 'columns': {'bookingDate': {'names': [DB_COLUMNS_EN.BOOKING_DATE, DB_COLUMNS_DE.BOOKING_DATE], 'fallbackIndex': DB_COLUMN_INDICES.BOOKING_DATE, 'required': true}, 'valueDate': {'names': [DB_COLUMNS_EN.VALUE_DATE, DB_COLUMNS_DE.VALUE_DATE], 'fallbackIndex': DB_COLUMN_INDICES.VALUE_DATE}, 'transactionType': {'names': [DB_COLUMNS_EN.TRANSACTION_TYPE, DB_COLUMNS_DE.TRANSACTION_TYPE], 'fallbackIndex': DB_COLUMN_INDICES.TRANSACTION_TYPE}, 'beneficiary': {'names': [DB_COLUMNS_EN.BENEFICIARY, DB_COLUMNS_DE.BENEFICIARY], 'fallbackIndex': DB_COLUMN_INDICES.BENEFICIARY}, 'paymentDetails': {'names': [DB_COLUMNS_EN.PAYMENT_DETAILS, DB_COLUMNS_DE.PAYMENT_DETAILS], 'fallbackIndex': DB_COLUMN_INDICES.PAYMENT_DETAILS}, 'iban': {'names': [DB_COLUMNS_EN.IBAN, DB_COLUMNS_DE.IBAN], 'fallbackIndex': DB_COLUMN_INDICES.IBAN}, 'bic': {'names': [DB_COLUMNS_EN.BIC, DB_COLUMNS_DE.BIC], 'fallbackIndex': DB_COLUMN_INDICES.BIC}, 'customerRef': {'names': [DB_COLUMNS_EN.CUSTOMER_REF, DB_COLUMNS_DE.CUSTOMER_REF], 'fallbackIndex': DB_COLUMN_INDICES.CUSTOMER_REF}, 'debit': {'names': [DB_COLUMNS_EN.DEBIT, DB_COLUMNS_DE.DEBIT], 'fallbackIndex': DB_COLUMN_INDICES.DEBIT}, 'credit': {'names': [DB_COLUMNS_EN.CREDIT, DB_COLUMNS_DE.CREDIT], 'fallbackIndex': DB_COLUMN_INDICES.CREDIT}, 'currency': {'names': [DB_COLUMNS_EN.CURRENCY, DB_COLUMNS_DE.CURRENCY], 'fallbackIndex': DB_COLUMN_INDICES.CURRENCY}}, 'transformRow': (dynamic row, dynamic columnMap, dynamic format) {
  return this.doTransformRow(row, columnMap, format);
}};
  RowTransformResult<DeutscheBankRawTransaction> doTransformRow(List<String> row, Map<String, num> columnMap, String? format) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final bookingDateStr = this.getColumnValue(row, columnMap, 'bookingDate');
    final valueDateStr = this.getColumnValue(row, columnMap, 'valueDate');
    final transactionType = this.getColumnValue(row, columnMap, 'transactionType');
    final beneficiary = this.getColumnValue(row, columnMap, 'beneficiary');
    final paymentDetails = this.getColumnValue(row, columnMap, 'paymentDetails');
    final iban = this.getColumnValue(row, columnMap, 'iban');
    final bic = this.getColumnValue(row, columnMap, 'bic');
    final customerRef = this.getColumnValue(row, columnMap, 'customerRef');
    final debitStr = this.getColumnValue(row, columnMap, 'debit');
    final creditStr = this.getColumnValue(row, columnMap, 'credit');
    final currency = this.getColumnValue(row, columnMap, 'currency');
    if (bookingDateStr == null) {
    return err({'message': 'Empty row: missing booking date', 'context': {}});
    }
    final detectedFormat = ((format ?? 'unknown') as DetectedFormat);
    DateTime? parsedDate;
    final dateResult = this.parseDateByFormat(bookingDateStr, detectedFormat);
    if (dateResult.success != null) {
    parsedDate = dateResult.value;
    } else {
    final fallbackResult = parseDate(bookingDateStr);
    if (fallbackResult.success != null) {
    parsedDate = fallbackResult.value;
    } else {
    return err({'message': 'Failed to parse booking date: $bookingDateStr', 'context': {'input': bookingDateStr, 'format': detectedFormat}});
    }
    }
    DateTime? valueDate;
    if (valueDateStr) {
    final valueDateResult = this.parseDateByFormat(valueDateStr, detectedFormat);
    if (valueDateResult.success != null) {
    valueDate = valueDateResult.value;
    } else {
    final fallbackResult = parseDate(valueDateStr);
    if (fallbackResult.success != null) {
    valueDate = fallbackResult.value;
    }
    }
    }
    num amount;
    final debit = this.parseEuropeanNumber(debitStr);
    final credit = this.parseEuropeanNumber(creditStr);
    if (!(debit).toDouble().isNaN && debit != 0) {
    amount = -abs(debit);
    } else if (!(credit).toDouble().isNaN && credit != 0) {
    amount = abs(credit);
    } else {
    return err({'message': 'Row has no valid amount (both debit and credit are empty or zero)', 'context': {}});
    }
    final description = [transactionType, beneficiary, paymentDetails].where(Boolean).toList().join(' - ');
    final customFields = {'iban': iban ?? null, 'bic': bic ?? null, 'customerReference': customerRef ?? null};
    Map<String, dynamic> metadata = {};
    if (transactionType) {
    metadata['transactionType'] = transactionType;
    }
    if (iban) {
    metadata['iban'] = iban;
    }
    if (bic) {
    metadata['bic'] = bic;
    }
    if (customerRef) {
    metadata['customerReference'] = customerRef;
    }
    final transaction = {'date': parsedDate, 'amount': Decimal.parse(amount), 'currency': currency ?? 'EUR', 'payee': beneficiary ?? null, 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ParseSuccess(data: transaction);
  }
  
  dynamic parseDateByFormat(String dateStr, DetectedFormat format) {
    if (dateStr == null || dateStr.trim() == '') {
    return {'success': false};
    }
    final trimmed = dateStr.trim();
    try {
    if (format == 'english') {
    final match = RegExp(r'^(\d{2})\/(\d{2})\/(\d{4})$').firstMatch(trimmed);
    if (match) {
    final month = match[1];
    final day = match[2];
    final year = match[3];
    final date = DateTime(int.parse(year), int.parse(month) - 1 + 1, int.parse(day));
    if (!(date.millisecondsSinceEpoch).toDouble().isNaN) {
    return ParseSuccess(data: date);
    }
    }
    } else if (format == 'german') {
    final match = RegExp(r'^(\d{2})\.(\d{2})\.(\d{4})$').firstMatch(trimmed);
    if (match) {
    final day = match[1];
    final month = match[2];
    final year = match[3];
    final date = DateTime(int.parse(year), int.parse(month) - 1 + 1, int.parse(day));
    if (!(date.millisecondsSinceEpoch).toDouble().isNaN) {
    return ParseSuccess(data: date);
    }
    }
    }
    return {'success': false};
    } catch (e) {
    return {'success': false};
    }
  }
  
}
