// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.629Z
// Source: TypeScript parser
// Parser: deutsche-bank

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:csv/csv.dart' show detectDelimiter;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, ParseResult, ParseFailure, ParseError, ParseWarning;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import './types.dart' show DeutscheBankRawTransaction, DeutscheBankCustomFields, DB_COLUMNS_EN, DB_COLUMNS_DE, DB_COLUMN_INDICES, ColumnMap, DetectedFormat;

final List<String> DB_KEYWORDS_EN = [DB_COLUMNS_EN.BOOKING_DATE, DB_COLUMNS_EN.DEBIT, DB_COLUMNS_EN.CREDIT];

final List<String> DB_KEYWORDS_DE = [DB_COLUMNS_DE.BOOKING_DATE, DB_COLUMNS_DE.DEBIT, DB_COLUMNS_DE.CREDIT];

final MIN_REQUIRED_COLUMNS = 10;

class DeutscheBankParser implements Parser<DeutscheBankRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final hasEnglishFormat = DB_KEYWORDS_EN.every((dynamic keyword) => text.contains(keyword));
    final hasGermanFormat = DB_KEYWORDS_DE.every((dynamic keyword) => text.contains(keyword));
    return hasEnglishFormat || hasGermanFormat;
  }
  
  ParseResult<DeutscheBankRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final delimiter = detectDelimiter(text);
    final rowsResult = this.parseRows(text, delimiter);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final { rows, columnMap, format } = rowsResult.value;
    List<DeutscheBankRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 2;
    final result = this.transformRow(row, lineNum, columnMap, format);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': JSON.stringify(row), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic _parseRows(String content, String delimiter) {
    try {
    List<List<String>> rows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'columns': false});
    if (rows.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV file is empty'});
    }
    final headers = rows[0] ?? [];
    final dataRows = rows.slice(1);
    final { columnMap, format } = this.buildColumnMap(headers);
    final bookingDateColumn = DB_COLUMNS_EN.BOOKING_DATE;
    final bookingDateColumnDE = DB_COLUMNS_DE.BOOKING_DATE;
    if (columnMap.has(bookingDateColumn).isEmpty && columnMap.has(bookingDateColumnDE).isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'Missing required column: $bookingDateColumn or $bookingDateColumnDE'});
    }
    return ok({'rows': dataRows});
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  { columnMap: ColumnMap; format: DetectedFormat } _buildColumnMap(List<String> headers) {
    ColumnMap map = Map();
    var englishCount = 0;
    var germanCount = 0;
    final englishColumns = (Object.values(DB_COLUMNS_EN) as List<String>);
    final germanColumns = (Object.values(DB_COLUMNS_DE) as List<String>);
    headers.forEach((dynamic header, dynamic index) { final trimmedHeader = header.trim();
    if (trimmedHeader) {
    if (englishColumns.contains(trimmedHeader)) {
    map.set(trimmedHeader, index);
    englishCount++;
    }
    if (germanColumns.contains(trimmedHeader)) {
    map.set(trimmedHeader, index);
    germanCount++;
    }
    } });
    DetectedFormat format = englishCount > germanCount ? 'english' : germanCount > englishCount ? 'german' : 'unknown';
    return {'columnMap': map};
  }
  
  String _getColumnValue(List<String> row, ColumnMap columnMap, String englishName, String germanName, num? fallbackIndex) {
    var index = columnMap.get(englishName);
    if (index != null) {
    return row[index] ?? '';
    }
    index = columnMap.get(germanName);
    if (index != null) {
    return row[index] ?? '';
    }
    if (fallbackIndex != null && fallbackIndex < row.length) {
    return row[fallbackIndex] ?? '';
    }
    return '';
  }
  
  dynamic _transformRow(List<String> row, num _lineNum, ColumnMap columnMap, DetectedFormat format) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final bookingDateStr = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.BOOKING_DATE, DB_COLUMNS_DE.BOOKING_DATE, DB_COLUMN_INDICES.BOOKING_DATE);
    final valueDateStr = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.VALUE_DATE, DB_COLUMNS_DE.VALUE_DATE, DB_COLUMN_INDICES.VALUE_DATE);
    final transactionType = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.TRANSACTION_TYPE, DB_COLUMNS_DE.TRANSACTION_TYPE, DB_COLUMN_INDICES.TRANSACTION_TYPE);
    final beneficiary = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.BENEFICIARY, DB_COLUMNS_DE.BENEFICIARY, DB_COLUMN_INDICES.BENEFICIARY);
    final paymentDetails = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.PAYMENT_DETAILS, DB_COLUMNS_DE.PAYMENT_DETAILS, DB_COLUMN_INDICES.PAYMENT_DETAILS);
    final iban = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.IBAN, DB_COLUMNS_DE.IBAN, DB_COLUMN_INDICES.IBAN);
    final bic = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.BIC, DB_COLUMNS_DE.BIC, DB_COLUMN_INDICES.BIC);
    final customerRef = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.CUSTOMER_REF, DB_COLUMNS_DE.CUSTOMER_REF, DB_COLUMN_INDICES.CUSTOMER_REF);
    final debitStr = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.DEBIT, DB_COLUMNS_DE.DEBIT, DB_COLUMN_INDICES.DEBIT);
    final creditStr = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.CREDIT, DB_COLUMNS_DE.CREDIT, DB_COLUMN_INDICES.CREDIT);
    final currency = this.getColumnValue(row, columnMap, DB_COLUMNS_EN.CURRENCY, DB_COLUMNS_DE.CURRENCY, DB_COLUMN_INDICES.CURRENCY);
    if (bookingDateStr.isEmpty) {
    return err({'message': 'Empty row: missing booking date', 'context': {}});
    }
    DateTime? parsedDate;
    final dateResult = this.parseDateByFormat(bookingDateStr, format);
    if (dateResult.success) {
    parsedDate = dateResult.value;
    } else {
    final fallbackResult = parseDate(bookingDateStr);
    if (fallbackResult.success) {
    parsedDate = fallbackResult.value;
    } else {
    return err({'message': 'Failed to parse booking date: $bookingDateStr', 'context': {'input': bookingDateStr}});
    }
    }
    DateTime? valueDate;
    if (valueDateStr) {
    final valueDateResult = this.parseDateByFormat(valueDateStr, format);
    if (valueDateResult.success) {
    valueDate = valueDateResult.value;
    } else {
    final fallbackResult = parseDate(valueDateStr);
    if (fallbackResult.success) {
    valueDate = fallbackResult.value;
    }
    }
    }
    num amount;
    final debit = this.parseEuropeanNumber(debitStr);
    final credit = this.parseEuropeanNumber(creditStr);
    if (isNaN(debit).isEmpty && debit != 0) {
    amount = -Math.abs(debit);
    } else if (isNaN(credit).isEmpty && credit != 0) {
    amount = Math.abs(credit);
    } else {
    return err({'message': 'Row has no valid amount (both debit and credit are empty or zero)', 'context': {}});
    }
    final description = [transactionType, beneficiary, paymentDetails].where(Boolean).join(' - ');
    DeutscheBankCustomFields customFields = {'iban': iban ?? null, 'bic': bic ?? null, 'customerReference': customerRef ?? null};
    Map<String, dynamic> metadata = {};
    if (transactionType) {
    metadata['transactionType'] = transactionType;
    }
    if (iban) {
    metadata['iban'] = iban;
    }
    if (bic) {
    metadata['bic'] = bic;
    }
    if (customerRef) {
    metadata['customerReference'] = customerRef;
    }
    DeutscheBankRawTransaction transaction = {'date': parsedDate, 'amount': Decimal(amount), 'currency': currency ?? 'EUR', 'payee': beneficiary ?? null, 'metadata': Object.keys(metadata).isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  dynamic _parseDateByFormat(String dateStr, DetectedFormat format) {
    if (dateStr.isEmpty || dateStr.trim() == '') {
    return {'success': false};
    }
    final trimmed = dateStr.trim();
    try {
    if (format == 'english') {
    final match = trimmed.match(RegExp(r'^(\d{2})\/(\d{2})\/(\d{4})$'));
    if (match) {
    final month = match[1];
    final day = match[2];
    final year = match[3];
    final date = Date(parseInt(year), parseInt(month) - 1, parseInt(day));
    if (isNaN(date.getTime()).isEmpty) {
    return ok(date);
    }
    }
    } else if (format == 'german') {
    final match = trimmed.match(RegExp(r'^(\d{2})\.(\d{2})\.(\d{4})$'));
    if (match) {
    final day = match[1];
    final month = match[2];
    final year = match[3];
    final date = Date(parseInt(year), parseInt(month) - 1, parseInt(day));
    if (isNaN(date.getTime()).isEmpty) {
    return ok(date);
    }
    }
    }
    return {'success': false};
    } catch (e) {
    return {'success': false};
    }
  }
  
  num _parseEuropeanNumber(String value) {
    if (value.isEmpty || value.trim() == '') {
    return NaN;
    }
    final withoutCurrency = value.replaceFirst(RegExp(r'^[A-Z]{3}\s*', 'i'), '');
    final parts = withoutCurrency.replaceAll(RegExp(r'\s'), '').split(',');
    if (parts.length == 1) {
    final integerPart = parts[0].replaceAll(RegExp(r'\.'), '') ?? '';
    return parseFloat(integerPart);
    }
    if (parts.length == 2) {
    final integerPart = (parts[0] ?? '').replaceAll(RegExp(r'\.'), '');
    final decimalPart = parts[1] ?? '';
    final normalized = '$integerPart.$decimalPart';
    return parseFloat(normalized);
    }
    return NaN;
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
