// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T11:59:46.299Z
// Source: TypeScript parser
// Parser: types

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/types.dart' show RawTransaction;

final DB_COLUMNS_EN = {'BOOKING_DATE': 'Booking date', 'VALUE_DATE': 'Value date', 'TRANSACTION_TYPE': 'Transaction Type', 'BENEFICIARY': 'Beneficiary / Originator', 'PAYMENT_DETAILS': 'Payment Details', 'IBAN': 'IBAN', 'BIC': 'BIC', 'CUSTOMER_REF': 'Customer Reference', 'DEBIT': 'Debit', 'CREDIT': 'Credit', 'CURRENCY': 'Currency'};

final DB_COLUMNS_DE = {'BOOKING_DATE': 'Buchungstag', 'VALUE_DATE': 'Valuta', 'TRANSACTION_TYPE': 'Buchungstext', 'BENEFICIARY': 'Begünstigter/Zahlungspflichtiger', 'PAYMENT_DETAILS': 'Verwendungszweck', 'IBAN': 'Kontonummer/IBAN', 'BIC': 'BIC', 'CUSTOMER_REF': 'Kundenreferenz', 'DEBIT': 'Soll', 'CREDIT': 'Haben', 'CURRENCY': 'Währung'};

final DB_COLUMN_INDICES = {'BOOKING_DATE': 0, 'VALUE_DATE': 1, 'TRANSACTION_TYPE': 2, 'BENEFICIARY': 3, 'PAYMENT_DETAILS': 4, 'IBAN': 5, 'BIC': 6, 'CUSTOMER_REF': 7, 'DEBIT': 8, 'CREDIT': 9, 'CURRENCY': 10};

class DeutscheBankCustomFields {
  final String transactionType;
  final String beneficiary;
  final String paymentDetails;
  final String? iban;
  final String? bic;
  final String? customerReference;
  final DateTime? valueDate;
  const DeutscheBankCustomFields({required this.transactionType, required this.beneficiary, required this.paymentDetails, this.iban, this.bic, this.customerReference, this.valueDate});
}

typedef DeutscheBankRawTransaction = RawTransaction<DeutscheBankCustomFields>;

typedef ColumnMap = Map<String, num>;

typedef DetectedFormat = String;
