// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.770Z
// Source: TypeScript parser
// Parser: ib

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, ParseResult, ParseFailure, ParseError, ParseWarning;

import './types.dart' show IBRawTransaction, IBCustomFields, IBSectionType, IB_KEYWORDS, IB_SECTION_PATTERNS, IB_TRADES_COLUMNS, IB_CASH_COLUMNS;

final MIN_REQUIRED_COLUMNS = 5;

class InteractiveBrokersParser implements Parser<IBRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final hasSectionHeader = Object.values(IB_SECTION_PATTERNS).some((dynamic pattern) => pattern.hasMatch(text));
    final hasKeywords = IB_KEYWORDS.some((dynamic keyword) => text.contains(keyword));
    return hasSectionHeader || hasKeywords;
  }
  
  ParseResult<IBRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final { sections } = rowsResult.value;
    List<IBRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (final section in sections) {
    final result = this.transformSection(section);
    if (result.success) {
    transactions.addAll(result.value);
    if (result.warnings) {
    warnings.addAll(result.warnings);
    }
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'Failed to parse section ${section.type}: ${result.error.message}'});
    }
    }
    if (transactions.isEmpty && sections.isNotEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No transactions parsed from any section'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic _parseRows(String content) {
    try {
    List<List<String>> rows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'delimiter': ',', 'columns': false});
    if (rows.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV file is empty'});
    }
    final sections = this.identifySections(rows);
    return ok({});
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  List<IBSection> _identifySections(List<List<String>> rows) {
    List<IBSection> sections = [];
    IBSection? currentSection = null;
    List<String>? headerRow = null;
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    if (row.isEmpty || row.isEmpty) {
    continue;
    }
    final sectionType = this.detectSectionType(row);
    if (sectionType) {
    if (currentSection && headerRow) {
    currentSection.columnMap = this.buildColumnMap(headerRow);
    sections.add(currentSection);
    }
    currentSection = {'type': sectionType, 'headerRow': -1, 'dataRows': [], 'columnMap': Map()};
    headerRow = null;
    continue;
    }
    if (currentSection) {
    if (headerRow.isEmpty && this.looksLikeHeaderRow(row)) {
    headerRow = row;
    currentSection.headerRow = i;
    continue;
    }
    if (headerRow) {
    currentSection.dataRows.add({'lineNum': i + 1});
    }
    }
    }
    if (currentSection && headerRow) {
    currentSection.columnMap = this.buildColumnMap(headerRow);
    sections.add(currentSection);
    }
    return sections;
  }
  
  IBSectionType? _detectSectionType(List<String> row) {
    if (row.isEmpty || row.isEmpty) {
    return null;
    }
    final rowText = row.join(' ').trim();
    for (final [type, pattern] in Object.entries(IB_SECTION_PATTERNS)) {
    if (pattern.hasMatch(rowText)) {
    return (type as IBSectionType);
    }
    }
    return null;
  }
  
  bool _looksLikeHeaderRow(List<String> row) {
    if (row.isEmpty || row.length < 3) {
    return false;
    }
    final headerKeywords = ['Symbol', 'Date', 'DateTime', 'Quantity', 'Currency', 'Description', 'Amount', 'Type'];
    final matchCount = row.where((dynamic cell) => headerKeywords.some((dynamic keyword) => cell.contains(keyword))).length;
    return matchCount >= 2;
  }
  
  Map<String, num> _buildColumnMap(List<String> headers) {
    final map = Map();
    headers.forEach((dynamic header, dynamic index) { final trimmedHeader = header.trim();
    if (trimmedHeader) {
    map.set(trimmedHeader, index);
    } });
    return map;
  }
  
  String _getColumnValue(List<String> row, Map<String, num> columnMap, String name) {
    final index = columnMap.get(name);
    if (index != null && index < row.length) {
    return row[index] ?? '';
    }
    return '';
  }
  
  dynamic _transformSection(IBSection section) {
    List<IBRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (final { row, lineNum } in section.dataRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'line': lineNum});
    continue;
    }
    dynamic result;
    switch (section.type) {
    case 'Trades':
    result = this.transformTradeRow(row, section.columnMap, lineNum);
    break;
    break;
    case 'CashTransactions':
    result = this.transformCashRow(row, section.columnMap, lineNum);
    break;
    break;
    default:
    continue;
    break;
    }
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'context': result.error.context});
    }
    }
    return ok(transactions);
  }
  
  dynamic _transformTradeRow(List<String> row, Map<String, num> columnMap, num _lineNum) {
    final symbol = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.SYMBOL);
    final dateTimeStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.DATE_TIME);
    final quantityStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.QUANTITY);
    final tradePriceStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.TRADE_PRICE);
    final commFeeStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.COMM_FEE);
    final proceedsStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.PROCEEDS);
    final currency = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.CURRENCY);
    final description = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.DESCRIPTION);
    final assetCategory = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.ASSET_CATEGORY);
    final tradeId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.TRADE_ID);
    final orderId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.ORDER_ID);
    final ibOrderId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.IB_ORDER_ID);
    final openCloseIndicator = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.OPEN_CLOSE_INDICATOR);
    final code = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.CODE);
    final dateResult = this.parseIBDate(dateTimeStr);
    if (dateResult.isEmpty) {
    return err({'message': 'Failed to parse date: $dateTimeStr', 'context': {'input': dateTimeStr}});
    }
    final quantity = parseFloat(quantityStr);
    if (isNaN(quantity)) {
    return err({'message': 'Failed to parse quantity: $quantityStr', 'context': {'input': quantityStr}});
    }
    final tradePrice = parseFloat(tradePriceStr);
    final fees = parseFloat(commFeeStr) ?? 0;
    final proceeds = parseFloat(proceedsStr);
    IBCustomFields customFields = {'sectionType': 'Trades', 'currency': currency ?? 'USD', 'tradePrice': isNaN(tradePrice) ? null : tradePrice, 'proceeds': isNaN(proceeds) ? null : proceeds};
    Map<String, dynamic> metadata = {};
    if (quantity) {
    metadata['quantity'] = quantity;
    }
    if (tradePrice) {
    metadata['tradePrice'] = tradePrice;
    }
    if (fees) {
    metadata['fees'] = fees;
    }
    if (tradeId) {
    metadata['tradeId'] = tradeId;
    }
    final amount = isNaN(proceeds) ? Decimal(0) : Decimal(proceeds).plus(fees);
    final action = quantity >= 0 ? 'BUY' : 'SELL';
    final desc = '$action ${Math.abs(quantity)} $symbol'.trim();
    IBRawTransaction transaction = {'date': dateResult, 'currency': currency ?? 'USD', 'description': desc, 'metadata': Object.keys(metadata).isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  dynamic _transformCashRow(List<String> row, Map<String, num> columnMap, num _lineNum) {
    final currency = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.CURRENCY);
    final dateTimeStr = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.DATE_TIME);
    final amountStr = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.AMOUNT);
    final type = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.TYPE);
    final description = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.DESCRIPTION);
    final symbol = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.SYMBOL);
    final code = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.CODE);
    final assetCategory = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.ASSET_CATEGORY);
    final dateResult = this.parseIBDate(dateTimeStr);
    if (dateResult.isEmpty) {
    return err({'message': 'Failed to parse date: $dateTimeStr', 'context': {'input': dateTimeStr}});
    }
    final amount = parseFloat(amountStr);
    if (isNaN(amount)) {
    return err({'message': 'Failed to parse amount: $amountStr', 'context': {'input': amountStr}});
    }
    IBCustomFields customFields = {'sectionType': 'CashTransactions', 'currency': currency ?? 'USD', 'cashType': type};
    Map<String, dynamic> metadata = {};
    if (type) {
    metadata['cashType'] = type;
    }
    final desc = '$type: ${description ?? symbol ?? 'Cash Transaction'}'.trim();
    IBRawTransaction transaction = {'date': dateResult, 'amount': Decimal(amount), 'currency': currency ?? 'USD', 'description': desc, 'metadata': Object.keys(metadata).isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  DateTime? _parseIBDate(String dateStr) {
    if (dateStr.isEmpty || dateStr.trim() == '') {
    return null;
    }
    final trimmed = dateStr.trim();
    final yyyymmdd = RegExp(r'^(\d{4})(\d{2})(\d{2})$');
    final match1 = yyyymmdd.firstMatch(trimmed);
    if (match1) {
    final year = parseInt(match1[1], 10);
    final month = parseInt(match1[2], 10) - 1;
    final day = parseInt(match1[3], 10);
    return Date(year, month, day);
    }
    final yyyymmddhhmmss = RegExp(r'^(\d{4})(\d{2})(\d{2});(\d{2})(\d{2})(\d{2})$');
    final match2 = yyyymmddhhmmss.firstMatch(trimmed);
    if (match2) {
    final year = parseInt(match2[1], 10);
    final month = parseInt(match2[2], 10) - 1;
    final day = parseInt(match2[3], 10);
    final hour = parseInt(match2[4], 10);
    final minute = parseInt(match2[5], 10);
    final second = parseInt(match2[6], 10);
    return Date(year, month, day, hour, minute, second);
    }
    final isoLike = RegExp(r'^(\d{4})-(\d{2})-(\d{2})[ ,](\d{2}):(\d{2}):(\d{2})');
    final match3 = isoLike.firstMatch(trimmed);
    if (match3) {
    final year = parseInt(match3[1], 10);
    final month = parseInt(match3[2], 10) - 1;
    final day = parseInt(match3[3], 10);
    final hour = parseInt(match3[4], 10);
    final minute = parseInt(match3[5], 10);
    final second = parseInt(match3[6], 10);
    return Date(year, month, day, hour, minute, second);
    }
    final parsed = Date(trimmed);
    if (isNaN(parsed.getTime()).isEmpty) {
    return parsed;
    }
    return null;
  }
  
}

abstract class IBSection {
  IBSectionType get type;
  set type(IBSectionType value);
  num get headerRow;
  set headerRow(num value);
  List<List<{ row: string[]; lineNum: number }>> get dataRows;
  set dataRows(List<List<{ row: string[]; lineNum: number }>> value);
  Map<String, num> get columnMap;
  set columnMap(Map<String, num> value);
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
