// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T06:00:15.497Z
// Source: TypeScript parser
// Parser: ib-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';
import 'dart:math';

import 'package:csv/csv.dart' show parse;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, ParseResult, ParseError, ParseWarning, createParseFailure;
import 'package:firela/parser/src/utils/csv_helpers.dart';

import './types.dart' show IBRawTransaction, IBCustomFields, IBSectionType, IB_KEYWORDS, IB_SECTION_PATTERNS, IB_TRADES_COLUMNS, IB_CASH_COLUMNS;

final MIN_REQUIRED_COLUMNS = 5;

class InteractiveBrokersParser extends Parser<IBRawTransaction> {
  DetectionResult detect(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final hasSectionHeader = (IB_SECTION_PATTERNS as Map).values.toList().any((dynamic pattern) => pattern.hasMatch(text));
    final hasKeywords = IB_KEYWORDS.any((dynamic keyword) => text.contains(keyword));
    if (hasSectionHeader || hasKeywords) {
    return {'confidence': 100, 'institutionId': 'interactive-brokers'};
    }
    return {'confidence': 0, 'institutionId': 'interactive-brokers'};
  }
  
  Future<ParseResult<IBRawTransaction>> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final _obj = rowsResult.value;
    final sections = _obj.sections;
    List<IBRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (final section in sections) {
    final result = this.transformSection(section);
    if (result.success != null) {
    transactions.addAll(result.value);
    if (result.warnings != null) {
    warnings.addAll(result.warnings);
    }
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'Failed to parse section ${section.type}: ${result.error.message}'});
    }
    }
    if (transactions.isEmpty && sections.isNotEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No transactions parsed from any section'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic parseRows(String content) {
    try {
    List<List<String>> rows = parseCsvAsArrays(content);
    if (rows.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV file is empty'});
    }
    final sections = this.identifySections(rows);
    return ok({});
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String.fromCharCode(error)}'});
    }
  }
  
  List<IBSection> identifySections(List<List<String>> rows) {
    List<IBSection> sections = [];
    IBSection? currentSection = null;
    List<String>? headerRow = null;
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    if (row == null || row.isEmpty) {
    continue;
    }
    final sectionType = this.detectSectionType(row);
    if (sectionType) {
    if (currentSection && headerRow) {
    currentSection.columnMap = this.buildColumnMap(headerRow);
    sections.add(currentSection);
    }
    currentSection = {'type': sectionType, 'headerRow': -1, 'dataRows': [], 'columnMap': Map()};
    headerRow = null;
    continue;
    }
    if (currentSection) {
    if (headerRow == null && this.looksLikeHeaderRow(row)) {
    headerRow = row;
    currentSection.headerRow = i;
    continue;
    }
    if (headerRow) {
    currentSection.dataRows.add({'lineNum': i + 1});
    }
    }
    }
    if (currentSection && headerRow) {
    currentSection.columnMap = this.buildColumnMap(headerRow);
    sections.add(currentSection);
    }
    return sections;
  }
  
  IBSectionType? detectSectionType(List<String> row) {
    if (row == null || row.isEmpty) {
    return null;
    }
    final rowText = row.join(' ').trim();
    for (final entry in (IB_SECTION_PATTERNS as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final type = entry.key;
    final pattern = entry.value;
    if (pattern.hasMatch(rowText)) {
    return (type as IBSectionType);
    }
    }
    return null;
  }
  
  bool looksLikeHeaderRow(List<String> row) {
    if (row == null || row.length < 3) {
    return false;
    }
    final headerKeywords = ['Symbol', 'Date', 'DateTime', 'Quantity', 'Currency', 'Description', 'Amount', 'Type'];
    final matchCount = row.where((dynamic cell) => headerKeywords.any((dynamic keyword) => cell.contains(keyword))).toList().length;
    return matchCount >= 2;
  }
  
  Map<String, num> buildColumnMap(List<String> headers) {
    final map = Map();
    headers.forEach((dynamic header, dynamic index) { final trimmedHeader = header.trim();
    if (trimmedHeader) {
    map.set(trimmedHeader, index);
    } });
    return map;
  }
  
  String getColumnValue(List<String> row, Map<String, num> columnMap, String name) {
    final index = columnMap['get'](name);
    if (index != null && index < row.length) {
    return row[index] ?? '';
    }
    return '';
  }
  
  dynamic transformSection(IBSection section) {
    List<IBRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (final _item in section.dataRows) {
    final row = _item['row']!;
    final lineNum = _item['lineNum']!;
    if (row.length < MIN_REQUIRED_COLUMNS) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'line': lineNum});
    continue;
    }
    dynamic result;
    switch (section.type) {
    case 'Trades':
    result = this.transformTradeRow(row, section.columnMap, lineNum);
    break;
    break;
    case 'CashTransactions':
    result = this.transformCashRow(row, section.columnMap, lineNum);
    break;
    break;
    default:
    continue;
    break;
    }
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'context': result.error.context});
    }
    }
    return ok(transactions);
  }
  
  dynamic transformTradeRow(List<String> row, Map<String, num> columnMap, num _lineNum) {
    final symbol = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.SYMBOL);
    final dateTimeStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.DATE_TIME);
    final quantityStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.QUANTITY);
    final tradePriceStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.TRADE_PRICE);
    final commFeeStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.COMM_FEE);
    final proceedsStr = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.PROCEEDS);
    final currency = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.CURRENCY);
    final description = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.DESCRIPTION);
    final assetCategory = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.ASSET_CATEGORY);
    final tradeId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.TRADE_ID);
    final orderId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.ORDER_ID);
    final ibOrderId = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.IB_ORDER_ID);
    final openCloseIndicator = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.OPEN_CLOSE_INDICATOR);
    final code = this.getColumnValue(row, columnMap, IB_TRADES_COLUMNS.CODE);
    final dateResult = this.parseIBDate(dateTimeStr);
    if (dateResult == null) {
    return err({'message': 'Failed to parse date: $dateTimeStr', 'context': {'input': dateTimeStr}});
    }
    final quantity = double.parse(quantityStr);
    if (quantity.isNaN) {
    return err({'message': 'Failed to parse quantity: $quantityStr', 'context': {'input': quantityStr}});
    }
    final tradePrice = double.parse(tradePriceStr);
    final fees = double.parse(commFeeStr) ?? 0;
    final proceeds = double.parse(proceedsStr);
    final customFields = {'sectionType': 'Trades', 'currency': currency ?? 'USD', 'tradePrice': tradePrice.isNaN ? null : tradePrice, 'proceeds': proceeds.isNaN ? null : proceeds};
    Map<String, dynamic> metadata = {};
    if (quantity) {
    metadata['quantity'] = quantity;
    }
    if (tradePrice) {
    metadata['tradePrice'] = tradePrice;
    }
    if (fees) {
    metadata['fees'] = fees;
    }
    if (tradeId) {
    metadata['tradeId'] = tradeId;
    }
    final amount = proceeds.isNaN ? Decimal.parse(0) : Decimal.parse(proceedsStr).plus(Decimal.parse(commFeeStr ?? '0'));
    final action = quantity >= 0 ? 'BUY' : 'SELL';
    final desc = '$action ${abs(quantity)} $symbol'.trim();
    final transaction = {'date': dateResult, 'currency': currency ?? 'USD', 'description': desc, 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  dynamic transformCashRow(List<String> row, Map<String, num> columnMap, num _lineNum) {
    final currency = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.CURRENCY);
    final dateTimeStr = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.DATE_TIME);
    final amountStr = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.AMOUNT);
    final type = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.TYPE);
    final description = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.DESCRIPTION);
    final symbol = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.SYMBOL);
    final code = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.CODE);
    final assetCategory = this.getColumnValue(row, columnMap, IB_CASH_COLUMNS.ASSET_CATEGORY);
    final dateResult = this.parseIBDate(dateTimeStr);
    if (dateResult == null) {
    return err({'message': 'Failed to parse date: $dateTimeStr', 'context': {'input': dateTimeStr}});
    }
    final amount = Decimal.parse(amountStr);
    if (!amount.isFinite()) {
    return err({'message': 'Failed to parse amount: $amountStr', 'context': {'input': amountStr}});
    }
    final customFields = {'sectionType': 'CashTransactions', 'currency': currency ?? 'USD', 'cashType': type};
    Map<String, dynamic> metadata = {};
    if (type) {
    metadata['cashType'] = type;
    }
    final desc = '$type: ${description ?? symbol ?? 'Cash Transaction'}'.trim();
    final transaction = {'date': dateResult, 'amount': amount, 'currency': currency ?? 'USD', 'description': desc, 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  DateTime? parseIBDate(String dateStr) {
    if (dateStr == null || dateStr.trim() == '') {
    return null;
    }
    final trimmed = dateStr.trim();
    final yyyymmdd = RegExp(r'^(\d{4})(\d{2})(\d{2})$');
    final match1 = yyyymmdd.firstMatch(trimmed);
    if (match1) {
    final year = int.parse(match1[1]);
    final month = int.parse(match1[2]) - 1;
    final day = int.parse(match1[3]);
    return DateTime(year, month + 1, day);
    }
    final yyyymmddhhmmss = RegExp(r'^(\d{4})(\d{2})(\d{2});(\d{2})(\d{2})(\d{2})$');
    final match2 = yyyymmddhhmmss.firstMatch(trimmed);
    if (match2) {
    final year = int.parse(match2[1]);
    final month = int.parse(match2[2]) - 1;
    final day = int.parse(match2[3]);
    final hour = int.parse(match2[4]);
    final minute = int.parse(match2[5]);
    final second = int.parse(match2[6]);
    return DateTime(year, month + 1, day, hour, minute, second);
    }
    final isoLike = RegExp(r'^(\d{4})-(\d{2})-(\d{2})[ ,](\d{2}):(\d{2}):(\d{2})');
    final match3 = isoLike.firstMatch(trimmed);
    if (match3) {
    final year = int.parse(match3[1]);
    final month = int.parse(match3[2]) - 1;
    final day = int.parse(match3[3]);
    final hour = int.parse(match3[4]);
    final minute = int.parse(match3[5]);
    final second = int.parse(match3[6]);
    return DateTime(year, month + 1, day, hour, minute, second);
    }
    final parsed = DateTime.fromMillisecondsSinceEpoch(trimmed);
    if (!parsed.millisecondsSinceEpoch.isNaN) {
    return parsed;
    }
    return null;
  }
  
}

abstract class IBSection {
  IBSectionType get type;
  set type(IBSectionType value);
  num get headerRow;
  set headerRow(num value);
  List<List<{ row: string[]; lineNum: number }>> get dataRows;
  set dataRows(List<List<{ row: string[]; lineNum: number }>> value);
  Map<String, num> get columnMap;
  set columnMap(Map<String, num> value);
}
