// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-21T06:23:07.729Z
// Source: TypeScript parser
// Parser: types

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/types.dart' show RawTransaction;

typedef IBSectionType = String;

final IB_TRADES_COLUMNS = {'SYMBOL': 'Symbol', 'DATE_TIME': 'Date/Time', 'QUANTITY': 'Quantity', 'TRADE_PRICE': 'T. Price', 'CLOSE_PRICE': 'C. Price', 'PROCEEDS': 'Proceeds', 'COMM_FEE': 'Comm/Fee', 'BASIS': 'Basis', 'REALIZED_PNL': 'Realized P/L', 'MTM_PNL': 'MTM P/L', 'CODE': 'Code', 'ASSET_CATEGORY': 'Asset Category', 'DESCRIPTION': 'Description', 'CURRENCY': 'Currency', 'TRADE_ID': 'TradeID', 'ORDER_ID': 'OrderID', 'IB_ORDER_ID': 'IBOrderId', 'OPEN_CLOSE_INDICATOR': 'O/C'};

final IB_CASH_COLUMNS = {'CURRENCY': 'Currency', 'DATE_TIME': 'Date/Time', 'AMOUNT': 'Amount', 'TYPE': 'Type', 'DESCRIPTION': 'Description', 'SYMBOL': 'Symbol', 'CODE': 'Code', 'ASSET_CATEGORY': 'Asset Category'};

class IBCustomFields {
  final IBSectionType sectionType;
  final String? symbol;
  final String? assetCategory;
  final String? description;
  final String? currency;
  final num? quantity;
  final num? tradePrice;
  final String? tradeId;
  final String? orderId;
  final String? ibOrderId;
  final String? openCloseIndicator;
  final String? cashType;
  final String? code;
  final num? fees;
  final num? proceeds;
  final num? basis;
  const IBCustomFields({required this.sectionType, this.symbol, this.assetCategory, this.description, this.currency, this.quantity, this.tradePrice, this.tradeId, this.orderId, this.ibOrderId, this.openCloseIndicator, this.cashType, this.code, this.fees, this.proceeds, this.basis});
}

typedef IBRawTransaction = RawTransaction<IBCustomFields>;

final List<String> IB_KEYWORDS = ['ClientAccountID', 'Currency', 'Asset Category', 'Symbol'];

final Map<String, RegExp> IB_SECTION_PATTERNS = {'Trades': RegExp(r'^Trades'), 'CorporateActions': RegExp(r'^CorporateActions|^Corporate Actions'), 'CashTransactions': RegExp(r'^CashTransactions|^Cash Transactions'), 'Transfers': RegExp(r'^Transfers'), 'Interest': RegExp(r'^Interest'), 'FxTransactions': RegExp(r'^FxTransactions|^FX Transactions'), 'Fees': RegExp(r'^Fees'), 'ChangeInDividendAccruals': RegExp(r'^ChangeInDividendAccruals'), 'OpenDividendAccruals': RegExp(r'^OpenDividendAccruals'), 'WithholdingTax': RegExp(r'^WithholdingTax|^Withholding Tax'), 'Symbols': RegExp(r'^Symbols')};
