// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Stub file for IB parser types

// ignore_for_file: type=lint

/// Custom fields for Interactive Brokers transactions.
class IBCustomFields {
  final String? sectionType;
  final String? currency;
  final double? tradePrice;
  final double? proceeds;
  final String? cashType;

  const IBCustomFields({
    this.sectionType,
    this.currency,
    this.tradePrice,
    this.proceeds,
    this.cashType,
  });
}

/// Raw transaction type for Interactive Brokers.
typedef IBRawTransaction = dynamic;

/// Section types in IB statements.
enum IBSectionType {
  Trades,
  CashTransactions,
  Dividends,
  WithholdingTax,
  Fees,
}

/// Keywords for IB detection.
final List<String> IB_KEYWORDS = [
  'Interactive Brokers',
  'IBKR',
  'Account Statement',
  'Flex Query',
];

/// Patterns for identifying IB statement sections.
final Map<IBSectionType, RegExp> IB_SECTION_PATTERNS = {
  IBSectionType.Trades: RegExp(r'Trades|Order Trades|Execution'),
  IBSectionType.CashTransactions: RegExp(r'Cash Transactions|CashTransactions'),
  IBSectionType.Dividends: RegExp(r'Dividends'),
  IBSectionType.WithholdingTax: RegExp(r'Withholding Tax|WithholdingTax'),
  IBSectionType.Fees: RegExp(r'Fees|Commissions'),
};

/// Column name mappings for Trades section.
class IBTradesColumns {
  static const String SYMBOL = 'Symbol';
  static const String DATE_TIME = 'Date/Time';
  static const String QUANTITY = 'Quantity';
  static const String TRADE_PRICE = 'Trade Price';
  static const String COMM_FEE = 'Comm/Fee';
  static const String PROCEEDS = 'Proceeds';
  static const String CURRENCY = 'Currency';
  static const String DESCRIPTION = 'Description';
  static const String ASSET_CATEGORY = 'Asset Category';
  static const String TRADE_ID = 'Trade ID';
  static const String ORDER_ID = 'Order ID';
  static const String IB_ORDER_ID = 'IB Order ID';
  static const String OPEN_CLOSE_INDICATOR = 'Open/Close Indicator';
  static const String CODE = 'Code';
}

final IB_TRADES_COLUMNS = IBTradesColumns();

/// Column name mappings for Cash Transactions section.
class IBCashColumns {
  static const String CURRENCY = 'Currency';
  static const String DATE_TIME = 'Date/Time';
  static const String AMOUNT = 'Amount';
  static const String TYPE = 'Type';
  static const String DESCRIPTION = 'Description';
  static const String SYMBOL = 'Symbol';
  static const String CODE = 'Code';
  static const String ASSET_CATEGORY = 'Asset Category';
}

final IB_CASH_COLUMNS = IBCashColumns();
