// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T04:34:27.463Z
// Source: TypeScript parser
// Parser: sanitizer

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../masks.dart' show maskPhone, maskIdCard, maskAccount;
import '../types.dart' show PiiPattern;

final CN_ID_WEIGHTS = [7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2];

final CN_ID_CHECK_CHARS = ['1', '0', 'X', '9', '8', '7', '6', '5', '4', '3', '2'];

bool validateCnIdCard(String id) {
  if (id.length != 18) {
  return false;
  }
  final digits = id.substring(0, 17);
  final checkChar = id[17].toUpperCase();
  var sum = 0;
  for (var i = 0; i < 17; i++) {
  sum += int.parse(digits[i]) * CN_ID_WEIGHTS[i];
  }
  final expected = CN_ID_CHECK_CHARS[sum % 11];
  return checkChar == expected;
}

final List<PiiPattern> cnPatterns = [{'type': 'id_card_cn', 'name': 'Chinese ID Card', 'pattern': RegExp(r'[1-9]\d{5}(?:18|19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[\dXx]'), 'validator': validateCnIdCard, 'mask': maskIdCard, 'category': 'personal'}, {'type': 'phone_cn', 'name': 'Chinese Mobile Phone', 'pattern': RegExp(r'1[3-9]\d{9}'), 'validator': (String match) {
  // TODO: Handle BinaryExpression
}, 'mask': maskPhone, 'category': 'contact'}, {'type': 'passport_cn', 'name': 'Chinese Passport', 'pattern': RegExp(r'E\d{8}', caseSensitive: false), 'mask': maskAccount, 'category': 'personal'}, {'type': 'bank_card_cn', 'name': 'Chinese Bank Card', 'pattern': RegExp(r'(?:62|4|5)\d{15,18}'), 'validator': (String match) {
  // TODO: Handle BinaryExpression
}, 'mask': maskAccount, 'category': 'financial'}];
