// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T04:59:56.577Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../masks.dart' show maskIban;
import '../types.dart' show PiiPattern;

final Map<String, dynamic> IBAN_LENGTHS = {'AL': 28, 'AD': 24, 'AT': 20, 'AZ': 28, 'BH': 22, 'BE': 16, 'BA': 20, 'BR': 29, 'BG': 22, 'HR': 21, 'CY': 28, 'CZ': 24, 'DK': 18, 'EE': 20, 'FO': 18, 'FI': 18, 'FR': 27, 'GE': 22, 'DE': 22, 'GI': 23, 'GR': 27, 'GL': 18, 'HU': 28, 'IS': 26, 'IE': 22, 'IL': 23, 'IT': 27, 'JO': 30, 'KW': 30, 'LV': 21, 'LB': 28, 'LI': 21, 'LT': 20, 'LU': 20, 'MK': 19, 'MT': 31, 'MR': 27, 'MU': 30, 'MC': 27, 'MD': 24, 'ME': 22, 'NL': 18, 'NO': 15, 'PK': 24, 'PS': 29, 'PL': 28, 'PT': 25, 'QA': 29, 'RO': 24, 'SM': 27, 'SA': 24, 'RS': 22, 'SK': 24, 'SI': 19, 'ES': 24, 'SE': 24, 'CH': 21, 'TN': 24, 'TR': 26, 'AE': 23, 'GB': 22, 'VG': 24};

bool validateIban(String iban) {
  final cleaned = iban.replaceAll(RegExp(r'[\s-]'), '');
  final countryCode = cleaned.substring(0, 2);
  final expectedLength = IBAN_LENGTHS[countryCode];
  if (expectedLength == null || cleaned.length != expectedLength) {
  return false;
  }
  final rearranged = cleaned.substring(4) + cleaned.substring(0, 4);
  final numeric = rearranged.replaceAllMapped(RegExp(r'[A-Z]'), (Match m) { final ch = m.group(0)!; return (ch.codeUnitAt(0) - 55).toString(); });
  final remainder = BigInt.parse(numeric) % BigInt.from(97);
  return remainder == BigInt.from(1);
}

final List<PiiPattern> euPatterns = [{'type': 'iban_eu', 'name': 'International Bank Account Number (IBAN)', 'pattern': RegExp(r'\b[A-Z]{2}\d{2}[A-Z0-9]{4,30}\b'), 'validator': validateIban, 'mask': maskIban, 'category': 'financial'}];
