// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T04:59:56.327Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../masks.dart' show maskPhone, maskIdCard;
import '../types.dart' show PiiPattern;

final HKID_WEIGHTS = [9, 8, 7, 6, 5, 4, 3, 2];

bool validateHkHkid(String hkid) {
  final match = RegExp(r'([A-Z]{1,2})(\d{6})\((\d|A)\)', caseSensitive: false).firstMatch(hkid);
  if (match == null) {
  return false;
  }
  final prefix = match[1]!.toUpperCase();
  final digits = match[2]!;
  final checkChar = match[3]!.toUpperCase();
  final prefixChars = (prefix.length == 1 ? ' ' + prefix : prefix).split('');
  var sum = 0;
  sum += (prefixChars[0] == ' ' ? 36 : prefixChars[0].codeUnitAt(0) - 64) * HKID_WEIGHTS[0];
  sum += (prefixChars[1].codeUnitAt(0) - 64) * HKID_WEIGHTS[1];
  for (var i = 0; i < 6; i++) {
  sum += int.parse(digits[i]) * HKID_WEIGHTS[i + 2];
  }
  final remainder = sum % 11;
  final expected = remainder == 0 ? 'A' : (11 - remainder).toString();
  return checkChar == expected;
}

final List<PiiPattern> hkPatterns = [{'type': 'phone_hk', 'name': 'Hong Kong Phone Number', 'pattern': RegExp(r'\b[2-9]\d{7}\b'), 'mask': maskPhone, 'category': 'contact'}, {'type': 'hkid', 'name': 'Hong Kong Identity Card', 'pattern': RegExp(r'[A-Z]{1,2}\d{6}\([\dA]\)', caseSensitive: false), 'validator': validateHkHkid, 'mask': maskIdCard, 'category': 'personal'}];
