// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:13:14.517Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../types.dart' show PiiPattern;
import './cn.dart' show cnPatterns;
import './eu.dart' show euPatterns;
import './hk.dart' show hkPatterns;
import './universal.dart' show universalPatterns;
import './us.dart' show usPatterns;

final EU_REGIONS = ['eu', 'de', 'fr', 'nl', 'be', 'at', 'it', 'es', 'pt', 'ie', 'fi', 'gr', 'sk', 'si', 'ee', 'lv', 'lt', 'lu', 'mt', 'cy', 'hr', 'cz', 'pl', 'hu', 'ro', 'bg', 'se', 'dk', 'no'].toSet();

final Map<String, dynamic> REGION_MAP = {'cn': cnPatterns, 'hk': hkPatterns, 'us': usPatterns};

List<PiiPattern> getRegionPatterns(String region) {
  if (REGION_MAP[region] != null) {
  return REGION_MAP[region];
  }
  if (EU_REGIONS.contains(region)) {
  return euPatterns;
  }
  return [];
}

List<PiiPattern> loadPatterns(String region) {
  return [...getRegionPatterns(region), ...universalPatterns];
}
