// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T04:59:55.834Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../masks.dart' show maskEmail, maskAccount;
import '../types.dart' show PiiPattern;

bool luhnCheck(String cardNumber) {
  final digits = cardNumber.replaceAll(RegExp(r'\D'), '');
  if (digits.length != 16) {
  return false;
  }
  var sum = 0;
  var isEven = false;
  for (var i = digits.length - 1; i >= 0; i--) {
  var digit = int.parse(digits[i]);
  if (isEven) {
  digit *= 2;
  if (digit > 9) {
  digit -= 9;
  }
  }
  sum += digit;
  isEven = !isEven;
  }
  return sum % 10 == 0;
}

final List<PiiPattern> universalPatterns = [{'type': 'email', 'name': 'Email Address', 'pattern': RegExp(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', caseSensitive: false), 'mask': maskEmail, 'category': 'contact'}, {'type': 'credit_card', 'name': 'Credit Card Number', 'pattern': RegExp(r'(?:\d{4}[-\s]?){3}\d{4}'), 'validator': (String match) {
  // TODO: Handle VariableDeclarationList
  // TODO: Handle CallExpression
}, 'mask': maskAccount, 'category': 'financial'}];
