// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T14:01:16.734Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import '../masks.dart' show maskSsn, maskPhone;
import '../types.dart' show PiiPattern;

bool validateUsSsn(String ssn) {
  final digits = ssn.replaceAll(RegExp(r'\D'), '');
  if (digits.length != 9) {
  return false;
  }
  final area = int.parse(digits.substring(0, 3));
  final group = int.parse(digits.substring(3, 5));
  final serial = int.parse(digits.substring(5, 9));
  if (area < 1 || area > 899 || area == 666) {
  return false;
  }
  if (group < 1 || group > 99) {
  return false;
  }
  if (serial < 1 || serial > 9999) {
  return false;
  }
  return true;
}

final List<PiiPattern> usPatterns = [PiiPattern(type: 'ssn_us', name: 'US Social Security Number', pattern: RegExp(r'\b(?!000|666|9\d{2})\d{3}[-\s]?(?!00)\d{2}[-\s]?(?!0000)\d{4}\b'), validator: validateUsSsn, mask: maskSsn, category: 'personal'), PiiPattern(type: 'phone_us', name: 'US Phone Number', pattern: RegExp(r'\b\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4}\b'), mask: maskPhone, category: 'contact')];
