// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-21T06:23:08.040Z
// Source: TypeScript parser
// Parser: alipay-web-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/cn/alipay_custom_fields.dart' show AlipayCustomFields;
import 'package:firela/parser/src/cn/chinese_csv_parser.dart' show ChineseCsvParser;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

typedef AlipayWebRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_WEB_KEYWORDS = ['支付宝交易记录明细查询'];

final MIN_REQUIRED_COLUMNS = 11;

final List<String> SKIP_TYPES = ['其他'];

class AlipayWebParser extends ChineseCsvParser<AlipayWebRawTransaction> {
  final institutionId = 'alipay-web';
  final identifyKeywords = ALIPAY_WEB_KEYWORDS;
  final minColumns = MIN_REQUIRED_COLUMNS;
  var gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == '交易号';
  }
  
  @override
  bool isSeparatorRow(List<String> row) {
    return row[0].startsWith('---') ?? false;
  }
  
  @override
  RowTransformResult transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return RowTransformResult.err('Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', {'row': row});
    }
    final serial = row[0];
    final merchantSerial = row[1];
    final time = row[2];
    final payee = row[7];
    final narration = row[8];
    final amt = row[9];
    final type = row[10];
    final status = row[11] ?? '交易成功';
    final dateResult = parseDate(time);
    if (dateResult is Failure) {
    return RowTransformResult.err('Failed to parse date: ${(dateResult as Failure).error.message}', {'input': time, 'row': row});
    }
    if (SKIP_TYPES.contains(type)) {
    return RowTransformResult.err('Skipped type: $type', {'type': type, 'row': row, 'skip': true});
    }
    final isExpense = type == '支出';
    final isIncome = type == '收入';
    if (!isExpense && !isIncome) {
    return RowTransformResult.err('Unsupported type: $type', {'type': type, 'row': row});
    }
    final amountResult = parseAmount(amt);
    if (amountResult is Failure) {
    return RowTransformResult.err('Failed to parse amount: ${(amountResult as Failure).error.message}', {'input': amt, 'row': row});
    }
    var amount = (amountResult as Success).value.number;
    if (isExpense) {
    amount = -amount;
    }
    final customFields = AlipayCustomFields(status: normalizeStatus(status), orderNo: serial, merchantOrderNo: merchantSerial ?? null);
    final transaction = AlipayWebRawTransaction(date: (dateResult as Success).value, amount: amount, currency: (amountResult as Success).value.currency, description: narration ?? '', payee: payee ?? null, customFields: customFields);
    return RowTransformResult.ok(transaction);
  }
  
  String normalizeStatus(String status) {
    if (status == '交易成功' || status == '交易关闭' || status == '退款') {
    return status;
    }
    return '交易成功';
  }
  
}
