// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:43.939Z
// Source: TypeScript parser
// Parser: alipay-yuebao

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:firela/parser/src/result.dart' show Result;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, AlipayCustomFields, ParseResult, ParseFailure, ParseError, ParseWarning;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;
import 'package:firela/parser/src/utils/encoding.dart' show convertEncoding;

final List<String> ALIPAY_YUEBAO_KEYWORDS = ['本记账单', '记录时间', '收支类型'];

final MIN_REQUIRED_COLUMNS = 8;

final HEADER_IDENTIFIERS = {'time': '记录时间', 'direction': '收支类型'};

final List<String> SKIP_DIRECTIONS = ['不计收支'];

class AlipayYuebaoParser implements Parser {
  bool identify(String filename, Uint8List content) {
    final utf8Text = utf8.decode(content);
    if (ALIPAY_YUEBAO_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    return true;
    }
    final convertResult = convertEncoding(content, 'GBK', 'UTF-8');
    if (convertResult.success) {
    return ALIPAY_YUEBAO_KEYWORDS.every((dynamic keyword) => convertResult.value.contains(keyword));
    }
    return false;
  }
  
  ParseResult parse(Uint8List content) {
    String text;
    final utf8Text = utf8.decode(content);
    if (ALIPAY_YUEBAO_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    text = utf8Text;
    } else {
    final convertResult = convertEncoding(content, 'GBK', 'UTF-8');
    text = convertResult.success ? convertResult.value : utf8Text;
    }
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<RawTransaction<AlipayCustomFields>> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: ((transactions as dynamic) as List<RawTransaction>), warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  Result<List<List<String>>, ParseError> _parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    continue;
    }
    if (row[0] == HEADER_IDENTIFIERS.time && row[2] == HEADER_IDENTIFIERS.direction) {
    headerFound = true;
    continue;
    }
    if (headerFound) {
    dataRows.add(row);
    }
    }
    if (headerFound.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found (expected 记录时间, 收支类型 columns)'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  dynamic _transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final time = row[0];
    final category = row[1];
    final direction = row[2];
    var amt = row[3];
    final narration = row[4];
    final account = row[5];
    final dateResult = parseDate(time);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': time}});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return err({'message': 'Skipped direction: $direction', 'context': {'skip': true}});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (isExpense.isEmpty && isIncome.isEmpty) {
    return err({'message': 'Unsupported direction: $direction', 'context': {}});
    }
    amt = amt.replaceAll(RegExp(r'，'), '');
    final amountResult = parseChineseAmount(amt);
    if (!amountResult.success) {
    return err({'message': 'Failed to parse amount: ${amountResult.error.message}', 'context': {'input': amt}});
    }
    var amount = amountResult.value.number;
    if (isExpense) {
    amount = amount.neg();
    }
    AlipayCustomFields customFields = {'status': '交易成功'};
    Map<String, dynamic> metadata = {};
    if (account) {
    metadata['account'] = account;
    }
    RawTransaction<AlipayCustomFields> transaction = {'date': dateResult.value, 'currency': amountResult.value.currency, 'description': narration ?? ''};
    return ok(transaction);
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
