// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:34.554Z
// Source: TypeScript parser
// Parser: alipay-web-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, AlipayCustomFields;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import '../chinese-csv-parser.dart' show ChineseCsvParser;

typedef AlipayWebRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_WEB_KEYWORDS = ['支付宝交易记录明细查询'];

final MIN_REQUIRED_COLUMNS = 11;

final List<String> SKIP_TYPES = ['其他'];

class AlipayWebParser extends ChineseCsvParser<AlipayWebRawTransaction> {
  final dynamic institutionId = 'alipay-web';
  final dynamic identifyKeywords = ALIPAY_WEB_KEYWORDS;
  final dynamic minColumns = MIN_REQUIRED_COLUMNS;
  dynamic gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == '交易号';
  }
  
  @override
  bool isSeparatorRow(List<String> row) {
    return row[0].startsWith('---') ?? false;
  }
  
  @override
  RowTransformResult<AlipayWebRawTransaction> transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final serial = row[0];
    final merchantSerial = row[1];
    final time = row[2];
    final payee = row[7];
    final narration = row[8];
    final amt = row[9];
    final type = row[10];
    final status = row[11] ?? '交易成功';
    final dateResult = parseDate(time);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': time}});
    }
    if (SKIP_TYPES.contains(type)) {
    return err({'message': 'Skipped type: $type', 'context': {'skip': true}});
    }
    final isExpense = type == '支出';
    final isIncome = type == '收入';
    if (!isExpense && !isIncome) {
    return err({'message': 'Unsupported type: $type', 'context': {}});
    }
    final amountResult = parseChineseAmount(amt);
    if (!amountResult.success) {
    return err({'message': 'Failed to parse amount: ${amountResult.error.message}', 'context': {'input': amt}});
    }
    var amount = amountResult.value.number;
    if (isExpense) {
    amount = amount.neg();
    }
    final customFields = {'status': this.normalizeStatus(status), 'orderNo': serial, 'merchantOrderNo': merchantSerial ?? null};
    final transaction = {'date': dateResult.value, 'currency': amountResult.value.currency, 'description': narration ?? '', 'payee': payee ?? null};
    return ok(transaction);
  }
  
  String normalizeStatus(String status) {
    if (status == '交易成功' || status == '交易关闭' || status == '退款') {
    return status;
    }
    return '交易成功';
  }
  
}
