// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T09:27:49.380Z
// Source: TypeScript parser
// Parser: alipay-mobile-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/cn/alipay_custom_fields.dart' show AlipayCustomFields;
import 'package:firela/parser/src/cn/chinese_csv_parser.dart' show ChineseCsvParser;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;
import 'package:firela/parser/src/utils/parser_helpers.dart' show isValidAlipayDirection;

typedef AlipayMobileRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_MOBILE_KEYWORDS = ['支付宝', '电子客户回单'];

final MIN_REQUIRED_COLUMNS = 10;

final HEADER_IDENTIFIERS = {'time': '交易时间', 'category': '交易分类'};

final List<String> SKIP_DIRECTIONS = ['其他', '不计收支'];

class AlipayMobileParser extends ChineseCsvParser<AlipayMobileRawTransaction> {
  final institutionId = 'alipay-mobile';
  final identifyKeywords = ALIPAY_MOBILE_KEYWORDS;
  final minColumns = MIN_REQUIRED_COLUMNS;
  var gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS['time']! && row[1] == HEADER_IDENTIFIERS['category']!;
  }
  
  @override
  bool isSeparatorRow(List<String> row) {
    return row[0].startsWith('---') ?? false;
  }
  
  @override
  RowTransformResult transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return RowTransformResult.err('Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', {'row': row});
    }
    final time = row[0];
    final category = row[1];
    final payee = row[2];
    final payeeAccount = row[3];
    final narration = row[4];
    final direction = row[5];
    final amt = row[6];
    final method = row[7];
    final status = row[8];
    final serial = row[9];
    final merchantSerial = row[10];
    final remark = row[11];
    final dateResult = parseDate(time);
    if (dateResult is Failure) {
    return RowTransformResult.err('Failed to parse date: ${(dateResult as Failure).error.message}', {'input': time, 'row': row});
    }
    if (isValidAlipayDirection(direction) == null) {
    return RowTransformResult.err('Invalid direction: $direction', {'direction': direction, 'row': row});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return RowTransformResult.err('Skipped direction: $direction', {'direction': direction, 'row': row, 'skip': true});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (!isExpense && !isIncome) {
    return RowTransformResult.err('Unsupported direction: $direction', {'direction': direction, 'row': row});
    }
    final amountResult = parseAmount(amt);
    if (amountResult is Failure) {
    return RowTransformResult.err('Failed to parse amount: ${(amountResult as Failure).error.message}', {'input': amt, 'row': row});
    }
    var amount = (amountResult as Success).value.number;
    if (isExpense) {
    amount = -amount;
    }
    final customFields = AlipayCustomFields(status: normalizeStatus(status), category: category, orderNo: serial, merchantOrderNo: merchantSerial ?? null);
    Map<String, dynamic> txnMetadata = {'method': method};
    if (payeeAccount != null) {
    txnMetadata['payeeAccount'] = payeeAccount;
    }
    if (remark != null) {
    txnMetadata['remark'] = remark;
    }
    final transaction = AlipayMobileRawTransaction(date: (dateResult as Success).value, amount: amount, currency: (amountResult as Success).value.currency, description: narration ?? '', payee: payee ?? null, metadata: txnMetadata, customFields: customFields);
    return RowTransformResult.ok(transaction);
  }
  
  String normalizeStatus(String status) {
    if (status == '交易成功' || status == '交易关闭' || status == '退款') {
    return status;
    }
    return '交易成功';
  }
  
}
