// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T08:59:52.735Z
// Source: TypeScript parser
// Parser: alipay-yuebao-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'package:firela/parser/src/cn/alipay_custom_fields.dart' show AlipayCustomFields;
import 'package:firela/parser/src/cn/chinese_csv_parser.dart' show ChineseCsvParser;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

typedef AlipayYuebaoRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_YUEBAO_KEYWORDS = ['本记账单', '记录时间', '收支类型'];

final MIN_REQUIRED_COLUMNS = 8;

final HEADER_IDENTIFIERS = {'time': '记录时间', 'direction': '收支类型'};

final List<String> SKIP_DIRECTIONS = ['不计收支'];

class AlipayYuebaoParser extends ChineseCsvParser<AlipayYuebaoRawTransaction> {
  final institutionId = 'alipay-yuebao';
  final identifyKeywords = ALIPAY_YUEBAO_KEYWORDS;
  final minColumns = MIN_REQUIRED_COLUMNS;
  var gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS['time']! && row[2] == HEADER_IDENTIFIERS['direction']!;
  }
  
  @override
  RowTransformResult transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return RowTransformResult.err('Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', {'row': row});
    }
    final time = row[0];
    final category = row[1];
    final direction = row[2];
    var amt = row[3];
    final narration = row[4];
    final account = row[5];
    final dateResult = parseDate(time);
    if (dateResult is Failure) {
    return RowTransformResult.err('Failed to parse date: ${(dateResult as Failure).error.message}', {'input': time, 'row': row});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return RowTransformResult.err('Skipped direction: $direction', {'direction': direction, 'row': row, 'skip': true});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (!isExpense && !isIncome) {
    return RowTransformResult.err('Unsupported direction: $direction', {'direction': direction, 'row': row});
    }
    amt = amt.replaceAll(RegExp(r'，'), '');
    final amountResult = parseAmount(amt);
    if (amountResult is Failure) {
    return RowTransformResult.err('Failed to parse amount: ${(amountResult as Failure).error.message}', {'input': amt, 'row': row});
    }
    var amount = (amountResult as Success).value.number;
    if (isExpense) {
    amount = -amount;
    }
    final customFields = AlipayCustomFields(status: '交易成功', category: category);
    Map<String, dynamic> metadata = {};
    if (account != null) {
    metadata['account'] = account;
    }
    final transaction = AlipayYuebaoRawTransaction(date: (dateResult as Success).value, amount: amount, currency: (amountResult as Success).value.currency, description: narration ?? '', metadata: metadata, customFields: customFields);
    return RowTransformResult.ok(transaction);
  }
  
}
