// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:43.803Z
// Source: TypeScript parser
// Parser: alipay-mobile

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:firela/parser/src/result.dart' show Result;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, AlipayCustomFields, ParseResult, ParseFailure, ParseError, ParseWarning;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;
import 'package:firela/parser/src/utils/encoding.dart' show convertEncoding;

import '../types/alipay.dart' show isValidAlipayDirection;

final List<String> ALIPAY_MOBILE_KEYWORDS = ['支付宝', '电子客户回单'];

final MIN_REQUIRED_COLUMNS = 10;

final HEADER_IDENTIFIERS = {'time': '交易时间', 'category': '交易分类'};

final List<String> SKIP_DIRECTIONS = ['其他', '不计收支'];

class AlipayMobileParser implements Parser {
  bool identify(String filename, Uint8List content) {
    final utf8Text = utf8.decode(content);
    if (ALIPAY_MOBILE_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    return true;
    }
    final convertResult = convertEncoding(content, 'GBK', 'UTF-8');
    if (convertResult.success) {
    return ALIPAY_MOBILE_KEYWORDS.every((dynamic keyword) => convertResult.value.contains(keyword));
    }
    return false;
  }
  
  ParseResult parse(Uint8List content) {
    String text;
    final utf8Text = utf8.decode(content);
    if (ALIPAY_MOBILE_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    text = utf8Text;
    } else {
    final convertResult = convertEncoding(content, 'GBK', 'UTF-8');
    text = convertResult.success ? convertResult.value : utf8Text;
    }
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<RawTransaction<AlipayCustomFields>> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: ((transactions as dynamic) as List<RawTransaction>), warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  Result<List<List<String>>, ParseError> _parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    continue;
    }
    if (row[0] == HEADER_IDENTIFIERS.time && row[1] == HEADER_IDENTIFIERS.category) {
    headerFound = true;
    continue;
    }
    if (headerFound && row[0].startsWith('---')) {
    break;
    }
    if (headerFound) {
    dataRows.add(row);
    }
    }
    if (headerFound.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found (expected 交易时间, 交易分类 columns)'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  dynamic _transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final time = row[0];
    final category = row[1];
    final payee = row[2];
    final payeeAccount = row[3];
    final narration = row[4];
    final direction = row[5];
    final amt = row[6];
    final method = row[7];
    final status = row[8];
    final serial = row[9];
    final merchantSerial = row[10];
    final remark = row[11];
    final dateResult = parseDate(time);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': time}});
    }
    if (isValidAlipayDirection(direction).isEmpty) {
    return err({'message': 'Invalid direction: $direction', 'context': {}});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return err({'message': 'Skipped direction: $direction', 'context': {'skip': true}});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (isExpense.isEmpty && isIncome.isEmpty) {
    return err({'message': 'Unsupported direction: $direction', 'context': {}});
    }
    final amountResult = parseChineseAmount(amt);
    if (!amountResult.success) {
    return err({'message': 'Failed to parse amount: ${amountResult.error.message}', 'context': {'input': amt}});
    }
    var amount = amountResult.value.number;
    if (isExpense) {
    amount = amount.neg();
    }
    AlipayCustomFields customFields = {'status': this.normalizeStatus(status), 'orderNo': serial, 'merchantOrderNo': merchantSerial ?? null};
    Map<String, dynamic> txnMetadata = {};
    if (payeeAccount) {
    txnMetadata['payeeAccount'] = payeeAccount;
    }
    if (remark) {
    txnMetadata['remark'] = remark;
    }
    RawTransaction<AlipayCustomFields> transaction = {'date': dateResult.value, 'currency': amountResult.value.currency, 'description': narration ?? '', 'payee': payee ?? null, 'metadata': txnMetadata};
    return ok(transaction);
  }
  
  dynamic _normalizeStatus(String status) {
    if (status == '交易成功' || status == '交易关闭' || status == '退款') {
    return status;
    }
    return '交易成功';
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
