// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:35.133Z
// Source: TypeScript parser
// Parser: alipay-mobile-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, AlipayCustomFields;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import '../chinese-csv-parser.dart' show ChineseCsvParser;
import '../types/alipay.dart' show isValidAlipayDirection;

typedef AlipayMobileRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_MOBILE_KEYWORDS = ['支付宝', '电子客户回单'];

final MIN_REQUIRED_COLUMNS = 10;

final HEADER_IDENTIFIERS = {'time': '交易时间', 'category': '交易分类'};

final List<String> SKIP_DIRECTIONS = ['其他', '不计收支'];

class AlipayMobileParser extends ChineseCsvParser<AlipayMobileRawTransaction> {
  final dynamic institutionId = 'alipay-mobile';
  final dynamic identifyKeywords = ALIPAY_MOBILE_KEYWORDS;
  final dynamic minColumns = MIN_REQUIRED_COLUMNS;
  dynamic gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS.time && row[1] == HEADER_IDENTIFIERS.category;
  }
  
  @override
  bool isSeparatorRow(List<String> row) {
    return row[0].startsWith('---') ?? false;
  }
  
  @override
  RowTransformResult<AlipayMobileRawTransaction> transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final time = row[0];
    final category = row[1];
    final payee = row[2];
    final payeeAccount = row[3];
    final narration = row[4];
    final direction = row[5];
    final amt = row[6];
    final method = row[7];
    final status = row[8];
    final serial = row[9];
    final merchantSerial = row[10];
    final remark = row[11];
    final dateResult = parseDate(time);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': time}});
    }
    if (!isValidAlipayDirection(direction)) {
    return err({'message': 'Invalid direction: $direction', 'context': {}});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return err({'message': 'Skipped direction: $direction', 'context': {'skip': true}});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (!isExpense && !isIncome) {
    return err({'message': 'Unsupported direction: $direction', 'context': {}});
    }
    final amountResult = parseChineseAmount(amt);
    if (!amountResult.success) {
    return err({'message': 'Failed to parse amount: ${amountResult.error.message}', 'context': {'input': amt}});
    }
    var amount = amountResult.value.number;
    if (isExpense) {
    amount = amount.neg();
    }
    final customFields = {'status': this.normalizeStatus(status), 'orderNo': serial, 'merchantOrderNo': merchantSerial ?? null};
    Map<String, dynamic> txnMetadata = {};
    if (payeeAccount) {
    txnMetadata['payeeAccount'] = payeeAccount;
    }
    if (remark) {
    txnMetadata['remark'] = remark;
    }
    final transaction = {'date': dateResult.value, 'currency': amountResult.value.currency, 'description': narration ?? '', 'payee': payee ?? null, 'metadata': txnMetadata};
    return ok(transaction);
  }
  
  String normalizeStatus(String status) {
    if (status == '交易成功' || status == '交易关闭' || status == '退款') {
    return status;
    }
    return '交易成功';
  }
  
}
