// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T06:41:37.634Z
// Source: TypeScript parser
// Parser: alipay-yuebao-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/cn/alipay_custom_fields.dart' show AlipayCustomFields;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction;
import 'package:firela/parser/src/utils/amount_parser.dart' show parseChineseAmount;
import 'package:firela/parser/src/utils/date_parser.dart' show parseDate;

import '../chinese_csv_parser.dart' show ChineseCsvParser;

typedef AlipayYuebaoRawTransaction = RawTransaction<AlipayCustomFields>;

final List<String> ALIPAY_YUEBAO_KEYWORDS = ['本记账单', '记录时间', '收支类型'];

final MIN_REQUIRED_COLUMNS = 8;

final HEADER_IDENTIFIERS = {'time': '记录时间', 'direction': '收支类型'};

final List<String> SKIP_DIRECTIONS = ['不计收支'];

class AlipayYuebaoParser extends ChineseCsvParser<AlipayYuebaoRawTransaction> {
  final dynamic institutionId = 'alipay-yuebao';
  final dynamic identifyKeywords = ALIPAY_YUEBAO_KEYWORDS;
  final dynamic minColumns = MIN_REQUIRED_COLUMNS;
  dynamic gbkFallback = true;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS.time && row[2] == HEADER_IDENTIFIERS.direction;
  }
  
  @override
  RowTransformResult<AlipayYuebaoRawTransaction> transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final time = row[0];
    final category = row[1];
    final direction = row[2];
    var amt = row[3];
    final narration = row[4];
    final account = row[5];
    final dateResult = parseDate(time);
    if (!dateResult.success) {
    return err({'message': 'Failed to parse date: ${dateResult.error.message}', 'context': {'input': time}});
    }
    if (SKIP_DIRECTIONS.contains(direction)) {
    return err({'message': 'Skipped direction: $direction', 'context': {'skip': true}});
    }
    final isExpense = direction == '支出';
    final isIncome = direction == '收入';
    if (!isExpense && !isIncome) {
    return err({'message': 'Unsupported direction: $direction', 'context': {}});
    }
    amt = amt.replaceAll(RegExp(r'，'), '');
    final amountResult = parseChineseAmount(amt);
    if (!amountResult.success) {
    return err({'message': 'Failed to parse amount: ${amountResult.error.message}', 'context': {'input': amt}});
    }
    var amount = amountResult.value.number;
    if (isExpense) {
    amount = amount.negated();
    }
    final customFields = {'status': '交易成功'};
    Map<String, dynamic> metadata = {};
    if (account) {
    metadata['account'] = account;
    }
    final transaction = {'date': dateResult.value, 'currency': amountResult.value.currency, 'description': narration ?? ''};
    return ParseSuccess(data: transaction);
  }
  
}
