// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T05:26:44.730Z
// Source: TypeScript parser
// Parser: boc-credit-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// TODO: This parser uses cheerio for HTML parsing which has no Dart equivalent.
// Manual conversion required.
