// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T02:15:32.575Z
// Source: TypeScript parser
// Parser: boc-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// TODO: This parser uses cheerio for HTML parsing which has no Dart equivalent.
// Manual conversion required.
