// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T12:52:13.371Z
// Source: TypeScript parser
// Parser: boc-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning;

import '../../types/bank.dart' show BocDebitCustomFields;
// TODO: unmapped import: readPdfTable, PdfTableReadResult

typedef BocRawTransaction = RawTransaction<BocDebitCustomFields>;

final List<String> BOC_DEBIT_KEYWORDS = ['中国银行', '交易明细列表'];

final HEADER_FIRST_CELL = '记账日期';

final EXPECTED_COLUMNS = 12;

final CARD_NUMBER_PATTERN = RegExp(r'(\d{19})');

final CUSTOMER_NAME_PATTERN = RegExp(r'(?:客户姓名|客户名称)[：:\s]*([^\s\d]+)');

final Map<String, dynamic> CURRENCY_MAP = String, dynamic('人民币': 'CNY', '美元': 'USD', '欧元': 'EUR', '港币': 'HKD', '日元': 'JPY', '英镑': 'GBP', '澳元': 'AUD');

class BocDebitParser extends Parser<BocRawTransaction> {
  bool identify(String filename, Uint8List content) {
    if (!filename.toLowerCase().endsWith('.pdf')) {
    return false;
    }
    final text = utf8.decode(content);
    final allFound = BOC_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return allFound ? 100 : 0 > 0;
  }
  
  ParseResult<BocRawTransaction> parse(Uint8List content) {
    final tableResult = /* TODO: AwaitExpression: await this.extractTable(content) */;
    if (!tableResult.success) {
    return ParseFailure(errors: [ParseWarning(type: 'FILE_READ_ERROR', message: tableResult.error.message)]);
    }
    final _obj = tableResult.value;
    final rows = _obj.rows;
    final fullText = _obj.fullText;
    final cardNumber = this.extractCardNumber(fullText);
    final customerName = this.extractCustomerName(fullText);
    List<BocRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum, cardNumber, customerName);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: result.error.message, line: lineNum, raw: row.join('|'), context: result.error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found in PDF table'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  PdfTableReadResult extractTable(Uint8List content) {
    return readPdfTable(content, {'headerFirstCell': HEADER_FIRST_CELL, 'yTolerance': 3, 'xTolerance': 10, 'minColumnWidth': 30});
  }
  
  String? extractCardNumber(String fullText) {
    final match = CARD_NUMBER_PATTERN.firstMatch(fullText);
    return match ? match[1]!.substring(match[1]!.length - 4) : null;
  }
  
  String? extractCustomerName(String fullText) {
    final match = CUSTOMER_NAME_PATTERN.firstMatch(fullText);
    return match ? match[1]!.trim() : null;
  }
  
  dynamic transformRow(List<String> row, num _lineNum, String? cardNumber, String? _customerName) {
    if (row.length < EXPECTED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $EXPECTED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final dateStr = row[0];
    final timeStr = row[1];
    final currencyName = row[2];
    final amountStr = row[3];
    final transactionName = row[5];
    final channel = row[6];
    final branchName = row[7];
    final remark = row[8];
    final counterpartyName = row[9];
    final counterpartyAccount = row[10];
    final counterpartyBank = row[11];
    final date = this.parseDateTime(dateStr, timeStr);
    if (date == null) {
    return err({'message': 'Invalid date format: $dateStr $timeStr', 'context': {}});
    }
    final currency = CURRENCY_MAP[currencyName] || currencyName;
    final amountResult = this.parseAmount(amountStr);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    BocDebitCustomFields customFields = {};
    if (cardNumber) {
    customFields.cardNumber = cardNumber;
    }
    if (channel) {
    customFields.channel = channel;
    }
    if (transactionName) {
    customFields.transactionName = transactionName;
    }
    if (counterpartyName) {
    customFields.counterpartyName = counterpartyName;
    }
    if (counterpartyAccount) {
    customFields.counterpartyAccount = counterpartyAccount;
    }
    if (counterpartyBank) {
    customFields.counterpartyBank = counterpartyBank;
    }
    if (remark) {
    customFields.remark = remark;
    }
    if (branchName) {
    customFields.branchName = branchName;
    }
    final transaction = {'amount': amountResult.value, 'description': remark ?? transactionName ?? '', 'payee': counterpartyName ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ParseSuccess(data: transaction);
  }
  
  DateTime? parseDateTime(String dateStr, String timeStr) {
    if (dateStr == null) {
    return null;
    }
    final datePattern = RegExp(r'^(\d{4})-(\d{2})-(\d{2})$');
    final timePattern = RegExp(r'^(\d{2}):(\d{2}):(\d{2})$');
    final dateMatch = datePattern.firstMatch(dateStr.trim());
    if (dateMatch == null) {
    return null;
    }
    final year = int.parse(dateMatch[1]);
    final month = int.parse(dateMatch[2]);
    final day = int.parse(dateMatch[3]);
    var hours = 0;
    var minutes = 0;
    var seconds = 0;
    final timeMatch = timePattern.firstMatch(timeStr.trim());
    if (timeMatch) {
    hours = int.parse(timeMatch[1]);
    minutes = int.parse(timeMatch[2]);
    seconds = int.parse(timeMatch[3]);
    }
    final date = DateTime(year, month - 1 + 1, day, hours, minutes, seconds);
    return date.millisecondsSinceEpoch.isNaN ? null : date;
  }
  
  dynamic parseAmount(String amountStr) {
    if (amountStr == null || amountStr.trim().isEmpty) {
    return err({'message': 'Invalid amount: empty'});
    }
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ParseSuccess(data: amount);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
}
