// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-14T12:45:07.304Z
// Source: TypeScript parser
// Parser: boc-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning, ParseError;

import '../../types/bank.dart' show BocCreditCustomFields;
// TODO: unmapped import: cheerio

typedef BocCreditRawTransaction = RawTransaction<BocCreditCustomFields>;

final List<String> BOC_CREDIT_KEYWORDS = ['\u4e2d\u56fd\u94f6\u884c', '\u4fe1\u7528\u5361'];

final HEADER_FIRST_CELL = '\u4ea4\u6613\u65e5';

final CURRENCY_HEADER = '\u8d27\u5e01';

final EXPECTED_COLUMNS = 7;

class BocCreditParser extends Parser<BocCreditRawTransaction> {
  DetectionResult detect(String filename, Uint8List content) {
    final ext = filename.toLowerCase();
    if (!ext.endsWith('.html') && !ext.endsWith('.htm') && !ext.endsWith('.eml')) {
    return {'confidence': 0, 'institutionId': 'boc-credit'};
    }
    final text = utf8.decode(content);
    final allFound = BOC_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return {'confidence': allFound ? 100 : 0, 'institutionId': 'boc-credit'};
  }
  
  Future<ParseResult<BocCreditRawTransaction>> parse(Uint8List content) {
    final html = utf8.decode(content);
    if (html == null || html.trim().isEmpty) {
    return ParseFailure(errors: [{'type': 'INVALID_FORMAT', 'message': 'File is empty'}]);
    }
    final $ = cheerio.load(html);
    final tableResult = this.findTable($);
    if (!tableResult.success) {
    return ParseFailure(errors: [tableResult.error]);
    }
    final rows = tableResult.value;
    List<BocCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join('|'), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found in HTML table'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic findTable(cheerio.CheerioAPI $) {
    final tables = $('table');
    if (tables.isEmpty) {
    return err({'type': ('INVALID_FORMAT' as const), 'message': 'No HTML table found in content'});
    }
    List<List<String>> dataRows = [];
    tables.each((dynamic _tableIdx, dynamic table) { if (dataRows.isNotEmpty) {
    return;
    }
    final $table = $(table);
    final rows = $table.firstWhere('tr');
    var headerFound = false;
    rows.each((dynamic _rowIdx, dynamic row) { final $row = $(row);
    final cells = $row.firstWhere('td, th');
    List<String> cellValues = [];
    cells.each((dynamic _cellIdx, dynamic cell) { cellValues.add($(cell).text().trim()); });
    if (headerFound == null) {
    if (cellValues.isNotEmpty && (cellValues[0] == HEADER_FIRST_CELL || cellValues[0] == CURRENCY_HEADER || cellValues.any((dynamic c) => c == HEADER_FIRST_CELL))) {
    headerFound = true;
    }
    return;
    }
    if (cellValues.length >= EXPECTED_COLUMNS - 1) {
    dataRows.add(cellValues);
    } }); });
    if (dataRows.isEmpty) {
    return err({'type': ('INVALID_FORMAT' as const), 'message': 'No data rows found (expected header with "$HEADER_FIRST_CELL" or "$CURRENCY_HEADER")'});
    }
    return ok(dataRows);
  }
  
  dynamic transformRow(List<String> row, num _lineNum) {
    if (row.length < EXPECTED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $EXPECTED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final currency = row[0].trim();
    final transDateStr = row[1].trim();
    final postDateStr = row[2].trim();
    final cardLast4 = row[3].trim();
    final description = row[4].trim();
    final deposit = row[5].trim();
    final expenditure = row[6].trim();
    if (transDateStr == null && deposit == null && expenditure == null) {
    return err({'message': 'Empty row (no date or amount)'});
    }
    final date = this.parseDate(transDateStr);
    if (date == null) {
    return err({'message': 'Invalid date format: $transDateStr', 'context': {}});
    }
    final amountResult = this.detectDirectionAndAmount(deposit, expenditure);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    final _obj = amountResult.value;
    final amount = _obj.amount;
    final isExpense = _obj.isExpense;
    final signedAmount = isExpense ? amount.negated() : amount;
    final _obj = this.splitPayeeNarration(description);
    final payee = _obj.payee;
    final narration = _obj.narration;
    final postingDate = this.parseDate(postDateStr);
    BocCreditCustomFields customFields = {};
    if (cardLast4) {
    customFields.cardNumber = cardLast4;
    }
    if (postingDate) {
    customFields.postingDate = postingDate;
    }
    if (description) {
    customFields.narration = description;
    }
    final transaction = {'amount': signedAmount, 'currency': currency ?? 'CNY', 'description': narration ?? description, 'payee': payee ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
  dynamic detectDirectionAndAmount(String deposit, String expenditure) {
    if (expenditure && deposit == null) {
    final amount = this.parseAmount(expenditure);
    if (!amount.success) {
    return amount;
    }
    return ok({'amount': amount.value, 'isExpense': true});
    } else if (deposit && expenditure == null) {
    final amount = this.parseAmount(deposit);
    if (!amount.success) {
    return amount;
    }
    return ok({'amount': amount.value, 'isExpense': false});
    } else if (deposit == null && expenditure == null) {
    return err({'message': 'Both deposit and expenditure are empty'});
    } else {
    return err({'message': 'Both deposit and expenditure have values'});
    }
  }
  
  dynamic splitPayeeNarration(String description) {
    if (description.isEmpty) {
    return {'payee': null, 'narration': ''};
    }
    if (description.contains('-')) {
    final hyphenIdx = description.indexOf('-');
    final narration = description.substring(0, hyphenIdx).trim();
    final payee = description.substring(hyphenIdx + 1).trim();
    return {'payee': payee ?? null};
    }
    return {'payee': null, 'narration': description};
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final match = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})$').firstMatch(dateStr.trim());
    if (match == null) {
    return null;
    }
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!);
    final day = int.parse(match[3]!);
    final date = Date(year, month - 1, day);
    return date.getTime().isNaN ? null : date;
  }
  
  dynamic parseAmount(String amountStr) {
    if (amountStr == null || amountStr.trim().isEmpty) {
    return err({'message': 'Invalid amount: empty'});
    }
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ok(amount);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
}
