// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.077Z
// Source: TypeScript parser
// Parser: ccb-debit

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, ParseResult, ParseFailure, ParseError, ParseWarning;

abstract class CcbCustomFields implements Map<String, dynamic> {
  String get cardNumber;
  String get cashType;
  String get location;
  String get counterpartyAccount;
  String get counterpartyName;
}

typedef CcbRawTransaction = RawTransaction<CcbCustomFields>;

final List<String> CCB_DEBIT_KEYWORDS = ['中国建设银行', '交易明细'];

final MIN_REQUIRED_COLUMNS = 9;

final HEADER_IDENTIFIERS = {'sequence': '序号', 'summary': '摘要'};

final CARD_NUMBER_PATTERN = RegExp(r'卡号\/账号:([0-9]{19})');

final Map<String, dynamic> CURRENCY_MAP = {'人民币元': 'CNY', '人民币': 'CNY', '美元': 'USD', '欧元': 'EUR', '港币': 'HKD', '日元': 'JPY'};

class CcbDebitParser implements Parser<CcbRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    return CCB_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
  }
  
  ParseResult<CcbRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final cardNumber = this.extractCardNumber(text);
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<CcbRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum, cardNumber);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  String? _extractCardNumber(String content) {
    final match = CARD_NUMBER_PATTERN.firstMatch(content);
    return match ? match[1].slice(-4) : null;
  }
  
  dynamic _parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    continue;
    }
    if (row[0] == HEADER_IDENTIFIERS.sequence && row[1] == HEADER_IDENTIFIERS.summary) {
    headerFound = true;
    continue;
    }
    if (headerFound) {
    dataRows.add(row);
    }
    }
    if (headerFound.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found (expected 序号, 摘要 columns)'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  dynamic _transformRow(List<String> row, num _lineNum, String? cardNumber) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final narration = row[1];
    final currencyName = row[2];
    final cashType = row[3];
    final dateStr = row[4];
    final amountStr = row[5];
    final location = row[7];
    final counterpartyInfo = row[8];
    final date = this.parseDate(dateStr);
    if (date.isEmpty) {
    return err({'message': 'Invalid date format: $dateStr', 'context': {'input': dateStr}});
    }
    final currency = CURRENCY_MAP[currencyName] || currencyName;
    if (!CURRENCY_MAP[currencyName] && currencyName.length > 3) {
    return err({'message': 'Unknown currency: $currencyName', 'context': {'input': currencyName}});
    }
    Decimal amount;
    try {
    amount = Decimal(amountStr);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr', 'context': {'input': amountStr}});
    }
    String? counterpartyAccount;
    String? counterpartyName;
    String? payee = counterpartyInfo ?? null;
    if (counterpartyInfo) {
    counterpartyName = counterpartyInfo ?? null;
    }
    CcbCustomFields customFields = {'cardNumber': cardNumber ?? ''};
    if (cashType && cashType != '') {
    customFields.cashType = cashType;
    }
    if (location && location != '') {
    customFields.location = location;
    }
    if (counterpartyAccount) {
    customFields.counterpartyAccount = counterpartyAccount;
    }
    if (counterpartyName) {
    customFields.counterpartyName = counterpartyName;
    }
    CcbRawTransaction transaction = {'description': narration ?? '', 'customFields': Object.keys(customFields).isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
  DateTime? _parseDate(String dateStr) {
    if (dateStr.isEmpty) {
    return null;
    }
    if (RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(dateStr)) {
    final date = Date(dateStr);
    return isNaN(date.getTime()) ? null : date;
    }
    if (RegExp(r'^\d{8}$').hasMatch(dateStr)) {
    final year = parseInt(dateStr.substring(0, 4), 10);
    final month = parseInt(dateStr.substring(4, 6), 10);
    final day = parseInt(dateStr.substring(6, 8), 10);
    final date = Date(year, month - 1, day);
    return isNaN(date.getTime()) ? null : date;
    }
    return null;
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
