// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T08:59:54.200Z
// Source: TypeScript parser
// Parser: ccb-debit-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'dart:typed_data';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/cn/chinese_csv_parser.dart' show ChineseCsvParser;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/types.dart' show ParseResult, createParseFailure, ParseErrorType, RawTransaction;

class CcbCustomFields {
  final String? cardNumber;
  final String? cashType;
  final String? location;
  final String? counterpartyAccount;
  final String? counterpartyName;
  const CcbCustomFields({this.cardNumber, this.cashType, this.location, this.counterpartyAccount, this.counterpartyName});
}

typedef CcbRawTransaction = RawTransaction<CcbCustomFields>;

final List<String> CCB_DEBIT_KEYWORDS = ['中国建设银行', '交易明细'];

final MIN_REQUIRED_COLUMNS = 9;

final HEADER_IDENTIFIERS = {'sequence': '序号', 'summary': '摘要'};

final CARD_NUMBER_PATTERN = RegExp(r'卡号\/账号:([0-9]{19})');

final Map<String, String> CURRENCY_MAP = {'人民币元': 'CNY', '人民币': 'CNY', '美元': 'USD', '欧元': 'EUR', '港币': 'HKD', '日元': 'JPY'};

class CcbDebitParser extends ChineseCsvParser<CcbRawTransaction> {
  final institutionId = 'ccb-debit';
  final identifyKeywords = CCB_DEBIT_KEYWORDS;
  final minColumns = MIN_REQUIRED_COLUMNS;
  String? cardNumber;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS['sequence']! && row[1] == HEADER_IDENTIFIERS['summary']!;
  }
  
  @override
  ParseResult<CcbRawTransaction> parse(Uint8List content) {
    final text = decodeContent(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure(ParseErrorType.invalidFormat, 'File is empty');
    }
    cardNumber = extractCardNumber(text);
    return super.parse(content);
  }
  
  @override
  RowTransformResult transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return RowTransformResult.err('Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', {'row': row});
    }
    final narration = row[1];
    final currencyName = row[2];
    final cashType = row[3];
    final dateStr = row[4];
    final amountStr = row[5];
    final location = row[7];
    final counterpartyInfo = row[8];
    final date = parseDate(dateStr);
    if (date == null) {
    return RowTransformResult.err('Invalid date format: $dateStr', {'input': dateStr, 'row': row});
    }
    final currency = CURRENCY_MAP[currencyName]! ?? currencyName;
    if (CURRENCY_MAP[currencyName]! == null && currencyName.length > 3) {
    return RowTransformResult.err('Unknown currency: $currencyName', {'input': currencyName, 'row': row});
    }
    Decimal amount;
    try {
    amount = Decimal.parse(amountStr);
    } catch (e) {
    return RowTransformResult.err('Invalid amount: $amountStr', {'input': amountStr, 'row': row});
    }
    String? counterpartyName;
    String? payee = counterpartyInfo ?? null;
    if (counterpartyInfo != null) {
    counterpartyName = counterpartyInfo ?? null;
    }
    CcbCustomFields customFields = CcbCustomFields(cardNumber: cardNumber ?? '');
    if (cashType != null && cashType != '') {
    // TODO: customFields.cashType = cashType; // final field assignment — restructure to pass via constructor
    }
    if (location != null && location != '') {
    // TODO: customFields.location = location; // final field assignment — restructure to pass via constructor
    }
    if (counterpartyName != null) {
    // TODO: customFields.counterpartyName = counterpartyName; // final field assignment — restructure to pass via constructor
    }
    final transaction = CcbRawTransaction(date: date, amount: amount, currency: currency, description: narration ?? '', payee: payee, customFields: (customFields as Map).keys.toList().isNotEmpty ? customFields : null);
    return RowTransformResult.ok(transaction);
  }
  
  String? extractCardNumber(String content) {
    final match = CARD_NUMBER_PATTERN.firstMatch(content);
    return match != null ? match[1]!.substring(match[1]!.length - 4) : null;
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    if (RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(dateStr)) {
    final date = DateTime.parse(dateStr);
    return (date.millisecondsSinceEpoch as num).isNaN ? null : date;
    }
    if (RegExp(r'^\d{8}$').hasMatch(dateStr)) {
    final year = int.parse(dateStr.substring(0, 4));
    final month = int.parse(dateStr.substring(4, 6));
    final day = int.parse(dateStr.substring(6, 8));
    final date = DateTime(year.round(), (month - 1 + 1).round(), day.round());
    return (date.millisecondsSinceEpoch as num).isNaN ? null : date;
    }
    return null;
  }
  
}
