// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-14T01:13:10.731Z
// Source: TypeScript parser
// Parser: ccb-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show ParseResult, createParseFailure;
import 'package:firela/parser/src/types.dart' show RawTransaction;

import '../../chinese-csv-parser.dart' show ChineseCsvParser;

abstract class CcbCustomFields implements Map<String, dynamic> {
  String get cardNumber;
  String get cashType;
  String get location;
  String get counterpartyAccount;
  String get counterpartyName;
}

typedef CcbRawTransaction = RawTransaction<CcbCustomFields>;

final List<String> CCB_DEBIT_KEYWORDS = ['中国建设银行', '交易明细'];

final MIN_REQUIRED_COLUMNS = 9;

final HEADER_IDENTIFIERS = {'sequence': '序号', 'summary': '摘要'};

final CARD_NUMBER_PATTERN = RegExp(r'卡号\/账号:([0-9]{19})');

final Map<String, dynamic> CURRENCY_MAP = {'人民币元': 'CNY', '人民币': 'CNY', '美元': 'USD', '欧元': 'EUR', '港币': 'HKD', '日元': 'JPY'};

class CcbDebitParser extends ChineseCsvParser<CcbRawTransaction> {
  final dynamic institutionId = 'ccb-debit';
  final dynamic identifyKeywords = CCB_DEBIT_KEYWORDS;
  final dynamic minColumns = MIN_REQUIRED_COLUMNS;
  String? cardNumber;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIERS.sequence && row[1] == HEADER_IDENTIFIERS.summary;
  }
  
  @override
  Future<ParseResult<CcbRawTransaction>> parse(Uint8List content) {
    final text = this.decodeContent(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    this.cardNumber = this.extractCardNumber(text);
    return /* TODO: SuperKeyword: super */.parse(content);
  }
  
  @override
  RowTransformResult<CcbRawTransaction> transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final narration = row[1];
    final currencyName = row[2];
    final cashType = row[3];
    final dateStr = row[4];
    final amountStr = row[5];
    final location = row[7];
    final counterpartyInfo = row[8];
    final date = this.parseDate(dateStr);
    if (date == null) {
    return err({'message': 'Invalid date format: $dateStr', 'context': {'input': dateStr}});
    }
    final currency = CURRENCY_MAP[currencyName] || currencyName;
    if (!CURRENCY_MAP[currencyName] && currencyName.length > 3) {
    return err({'message': 'Unknown currency: $currencyName', 'context': {'input': currencyName}});
    }
    Decimal amount;
    try {
    amount = Decimal(amountStr);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr', 'context': {'input': amountStr}});
    }
    String? counterpartyName;
    String? payee = counterpartyInfo ?? null;
    if (counterpartyInfo) {
    counterpartyName = counterpartyInfo ?? null;
    }
    final customFields = {'cardNumber': this.cardNumber ?? ''};
    if (cashType && cashType != '') {
    customFields.cashType = cashType;
    }
    if (location && location != '') {
    customFields.location = location;
    }
    if (counterpartyName) {
    customFields.counterpartyName = counterpartyName;
    }
    final transaction = {'description': narration ?? '', 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
  String? extractCardNumber(String content) {
    final match = CARD_NUMBER_PATTERN.firstMatch(content);
    return match ? match[1]!.substring(-4) : null;
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    if (RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(dateStr)) {
    final date = Date(dateStr);
    return date.getTime().isNaN ? null : date;
    }
    if (RegExp(r'^\d{8}$').hasMatch(dateStr)) {
    final year = int.parse(dateStr.substring(0, 4));
    final month = int.parse(dateStr.substring(4, 6));
    final day = int.parse(dateStr.substring(6, 8));
    final date = Date(year, month - 1, day);
    return date.getTime().isNaN ? null : date;
    }
    return null;
  }
  
}
