// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:35.410Z
// Source: TypeScript parser
// Parser: chinese-csv-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:csv/csv.dart' show parse;
import 'package:firela/parser/src/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, ParseResult, ParseSuccess, ParseWarning, ParseError, DetectionResult, Parser, createParseFailure;
import 'package:firela/parser/src/utils/encoding.dart' show convertEncoding;

abstract class ChineseCsvParser extends Parser<T> {
  late final String institutionId;
  late final List<String> identifyKeywords;
  late final num minColumns;
  abstract bool isHeaderRow(List<String> row);
  
  bool isSeparatorRow(List<String> _row) {
    return false;
  }
  
  dynamic gbkFallback = false;
  abstract RowTransformResult<T> transformRow(List<String> row, num lineNum);
  
  DetectionResult detect(String _filename, Uint8List content) {
    final decoded = this.decodeContent(content);
    final allFound = this.identifyKeywords.every((dynamic kw) => decoded.contains(kw));
    return {'confidence': allFound ? 100 : 0, 'institutionId': this.institutionId};
  }
  
  Future<ParseResult<T>> parse(Uint8List content) {
    final text = this.decodeContent(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    return this.transformRows(rows);
  }
  
  String decodeContent(Uint8List content) {
    final utf8Text = utf8.decode(content);
    if (this.identifyKeywords.every((dynamic kw) => utf8Text.contains(kw))) {
    return utf8Text;
    }
    if (this.gbkFallback != null) {
    final convertResult = convertEncoding(content, 'GBK', 'UTF-8');
    if (convertResult.success != null) {
    return convertResult.value;
    }
    }
    return utf8Text;
  }
  
  dynamic parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < this.minColumns) {
    continue;
    }
    if (headerFound == null) {
    if (this.isHeaderRow(row)) {
    headerFound = true;
    }
    continue;
    }
    if (this.isSeparatorRow(row)) {
    break;
    }
    dataRows.add(row);
    }
    if (headerFound == null) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : (error).toString()}'});
    }
  }
  
  ParseSuccess<T> transformRows(List<List<String>> rows) {
    List<T> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    ParseSuccess<T> success = ok(transactions);
    if (warnings.isNotEmpty) {
    success.warnings = warnings;
    }
    return success;
  }
  
}
