// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T11:59:48.361Z
// Source: TypeScript parser
// Parser: chinese-csv-parser

// ignore_for_file: unnecessary_null_comparison, unnecessary_cast, dead_null_aware_expression
// ignore_for_file: avoid_redundant_argument_values, avoid_unused_element, unused_local_variable
// ignore_for_file: unused_shown_name, non_constant_identifier_names, annotate_overrides, prefer_const_declarations

import 'dart:convert';
import 'dart:typed_data';

import 'package:csv/csv.dart' show parse;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, ParseResult, ParseSuccess, ParseWarning, ParseError, DetectionResult, Parser, createParseFailure, ParseErrorType, ParseFailure;
import 'package:firela/parser/src/utils/csv_helpers.dart';
import 'package:firela/parser/src/utils/encoding.dart' as encoding;

abstract class ChineseCsvParser<T extends RawTransaction> extends Parser<T> {
  late final String institutionId;
  late final List<String> identifyKeywords;
  late final num minColumns;
  bool isHeaderRow(List<String> row);
  
  bool isSeparatorRow(List<String> _row) {
    return false;
  }
  
  var gbkFallback = false;
  RowTransformResult transformRow(List<String> row, num lineNum);
  
  bool identify(String _filename, Uint8List content) {
    final decoded = decodeContent(content);
    final allFound = identifyKeywords.every((dynamic kw) => decoded.contains(kw));
    return (allFound != null ? 100 : 0) > 0;
  }
  
  ParseResult<T> parse(Uint8List content) {
    final text = decodeContent(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure(ParseErrorType.invalidFormat, 'File is empty');
    }
    final rowsResult = parseRows(text);
    if (rowsResult is Failure) {
    return ParseFailure(errors: [(rowsResult as Failure).error]);
    }
    final rows = (rowsResult as Success).value;
    return transformRows(rows);
  }
  
  String decodeContent(Uint8List content) {
    final utf8Text = utf8.decode(content);
    if (identifyKeywords.every((dynamic kw) => utf8Text.contains(kw))) {
    return utf8Text;
    }
    if (gbkFallback != null) {
    final convertResult = encoding.decodeContent(content);
    if (convertResult is Success) {
    return (convertResult as Success).value;
    }
    }
    return utf8Text;
  }
  
  dynamic parseRows(String content) {
    try {
    final allRows = parseCsvAsArrays(content);
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < minColumns) {
    continue;
    }
    if (headerFound == null) {
    if (isHeaderRow(row) != null) {
    headerFound = true;
    }
    continue;
    }
    if (isSeparatorRow(row) != null) {
    break;
    }
    dataRows.add(row);
    }
    if (headerFound == null) {
    return err(ParseWarning(type: 'INVALID_FORMAT', message: 'CSV header not found'));
    }
    return ParseSuccess(data: dataRows);
    } catch (error) {
    return err(ParseWarning(type: 'CSV_PARSE_ERROR', message: 'Failed to parse CSV: ${error is Exception ? error.toString() : (error).toString()}'));
    }
  }
  
  ParseSuccess<T> transformRows(List<List<String>> rows) {
    List<T> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = transformRow(row, lineNum);
    if (result is Success) {
    transactions.add((result as Success).value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: (result as Failure).error.message, line: lineNum, raw: row.join(','), context: (result as Failure).error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found after header'));
    }
    ParseSuccess<T> success = ParseSuccess(data: transactions);
    if (warnings.isNotEmpty) {
    // TODO: success.warnings = warnings; // final field — restructure to pass warnings via constructor
    }
    return success;
  }
  
}
