// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T12:52:11.362Z
// Source: TypeScript parser
// Parser: cmb-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';
import 'dart:math';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning;

import '../../types/bank.dart' show CmbDebitCustomFields;
// TODO: unmapped import: extractPdfText
// TODO: unmapped import: PdfTextItem

typedef CmbRawTransaction = RawTransaction<CmbDebitCustomFields>;

final List<String> CMB_DEBIT_KEYWORDS = ['\u62db\u5546\u94f6\u884c', '\u4ea4\u6613\u660e\u7ec6'];

final COLUMN_OFFSETS = [30, 50, 100, 200, 280, 350, 400];

final HEADER_KEYWORD = 'Party';

final END_MARKERS = [RegExp(r'^\d+\/\d+$'), '\u5408\u5e76\u7edf\u8ba1', '\u2014\u2014\u2014'];

final CARD_NUMBER_PATTERN = RegExp(r'(\d{16})');

final DATE_PATTERN = RegExp(r'^\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}$');

final Y_TOLERANCE = 3;

class CmbDebitParser extends Parser<CmbRawTransaction> {
  bool identify(String filename, Uint8List content) {
    if (!filename.toLowerCase().endsWith('.pdf')) {
    return false;
    }
    final text = utf8.decode(content);
    final allFound = CMB_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return allFound ? 100 : 0 > 0;
  }
  
  ParseResult<CmbRawTransaction> parse(Uint8List content) {
    final textResult = /* TODO: AwaitExpression: await extractPdfText(content) */;
    if (!textResult.success) {
    return ParseFailure(errors: [ParseWarning(type: 'FILE_READ_ERROR', message: textResult.error.message)]);
    }
    final _obj = textResult.value;
    final items = _obj.items;
    final fullText = _obj.fullText;
    final cardNumber = this.extractCardNumber(fullText);
    final dataItems = this.filterDataRegion(items);
    final rows = this.groupIntoRows(dataItems);
    List<CmbRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum, cardNumber);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: result.error.message, line: lineNum, raw: row.map((dynamic c) => c.content).toList().join('|'), context: result.error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found in PDF table'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  List<PdfTextItem> filterDataRegion(List<PdfTextItem> items) {
    List<PdfTextItem> filtered = [];
    var dataStarted = false;
    for (final item in items) {
    if (dataStarted == null) {
    if (item.str.contains(HEADER_KEYWORD)) {
    dataStarted = true;
    }
    continue;
    }
    final isEndMarker = END_MARKERS.any((dynamic marker) { if (marker is RegExp) {
    return marker.hasMatch(item.str.trim());
    }
    return item.str.contains(marker); });
    if (isEndMarker) {
    break;
    }
    filtered.add(item);
    }
    return filtered;
  }
  
  List<List<{ content: string; colIndex: number }>> groupIntoRows(List<PdfTextItem> items) {
    if (items.isEmpty) {
    return [];
    }
    final sorted = [...items].sort((dynamic a, dynamic b) { final yDiff = b.y - a.y;
    if (abs(yDiff) > Y_TOLERANCE) {
    return yDiff;
    }
    return a.x - b.x; });
    List<List<{ content: string; colIndex: number }>> rows = [];
    List<{ content: string; colIndex: number }> currentRow = [];
    var currentY = sorted[0].y;
    for (final item in sorted) {
    if (abs(item.y - currentY) <= Y_TOLERANCE) {
    final colIndex = this.findColumnIndex(item.x);
    currentRow.add({'content': item.str});
    } else {
    if (currentRow.isNotEmpty) {
    rows.add(currentRow);
    }
    final colIndex = this.findColumnIndex(item.x);
    currentRow = [{'content': item.str}];
    currentY = item.y;
    }
    }
    if (currentRow.isNotEmpty) {
    rows.add(currentRow);
    }
    return rows;
  }
  
  num findColumnIndex(num x) {
    for (var i = COLUMN_OFFSETS.length - 1; i >= 0; i--) {
    if (x >= COLUMN_OFFSETS[i]!) {
    return i;
    }
    }
    return 0;
  }
  
  List<String> rowToArray(List<{ content: string; colIndex: number }> row) {
    final maxCols = COLUMN_OFFSETS.length;
    List<String> cells = Array(maxCols).fill('');
    for (final cell in row) {
    final idx = min(cell.colIndex, maxCols - 1);
    if (cells[idx] != null) {
    cells[idx] += ' ' + cell.content;
    } else {
    cells[idx] = cell.content;
    }
    }
    return cells.map((dynamic c) => c.replaceAll(RegExp(r'\n'), '').trim()).toList();
  }
  
  String? extractCardNumber(String fullText) {
    final match = CARD_NUMBER_PATTERN.firstMatch(fullText);
    return match ? match[1]!.substring(match[1]!.length - 4) : null;
  }
  
  dynamic transformRow(List<{ content: string; colIndex: number }> row, num _lineNum, String? cardNumber) {
    final cells = this.rowToArray(row);
    final dateStr = cells[0];
    if (dateStr == null || !DATE_PATTERN.hasMatch(dateStr)) {
    return err({'message': 'Invalid or missing date: $dateStr', 'context': {}});
    }
    final date = this.parseDate(dateStr);
    if (date == null) {
    return err({'message': 'Invalid date format: $dateStr', 'context': {}});
    }
    final amountStr = cells[2];
    final amountResult = this.parseAmount(amountStr);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    final transactionType = cells[1];
    final summary = cells[4];
    final counterparty = cells[5];
    final customerNote = cells[6];
    final _obj = this.parseCounterparty(counterparty);
    final payee = _obj.payee;
    final description = customerNote ?? summary ?? '';
    CmbDebitCustomFields customFields = {};
    if (cardNumber) {
    customFields.cardNumber = cardNumber;
    }
    if (transactionType) {
    customFields.transactionType = transactionType;
    }
    if (counterparty) {
    customFields.counterparty = counterparty;
    }
    if (customerNote) {
    customFields.customerNote = customerNote;
    }
    final transaction = {'amount': amountResult.value, 'currency': 'CNY', 'payee': payee ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ParseSuccess(data: transaction);
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final normalized = dateStr.replaceAll(RegExp(r'\/'), '-');
    final match = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})$').firstMatch(normalized);
    if (match == null) {
    return null;
    }
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!);
    final day = int.parse(match[3]!);
    final date = DateTime(year, month - 1 + 1, day);
    return date.millisecondsSinceEpoch.isNaN ? null : date;
  }
  
  dynamic parseAmount(String amountStr) {
    if (amountStr == null || amountStr.trim().isEmpty) {
    return err({'message': 'Invalid amount: empty'});
    }
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ParseSuccess(data: amount);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
  dynamic parseCounterparty(String counterparty) {
    if (counterparty == null) {
    return {'payee': '', 'payeeAccount': null};
    }
    final match = RegExp(r'(\D*)(\d+)').firstMatch(counterparty);
    if (match) {
    return {'payee': match[1]!.trim(), 'payeeAccount': match[2]!};
    }
    return {'payee': counterparty.trim(), 'payeeAccount': null};
  }
  
}
