// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:37.418Z
// Source: TypeScript parser
// Parser: cmbc-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:csv/csv.dart' show parse;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseError, ParseWarning, createParseFailure;

abstract class CmbcCreditCustomFields {
  String get cardNumber;
  set cardNumber(String value);
  DateTime get postDate;
  set postDate(DateTime value);
  String get authorizationCode;
  String get originalAmount;
  String get countryCode;
}

typedef CmbcCreditRawTransaction = RawTransaction<CmbcCreditCustomFields>;

final List<String> CMBC_CREDIT_KEYWORDS = ['卡号末四位', '交易日'];

final MIN_REQUIRED_COLUMNS = 6;

final HEADER_IDENTIFIERS = {'cardLast4': '卡号末四位', 'txDate': '交易日'};

final FOREIGN_CURRENCY_PATTERN = RegExp(r'^(.*?)\s*?([A-Z]+)([-\d.]+)\s*([A-Z]+)$');

class CmbcCreditParser extends Parser<CmbcCreditRawTransaction> {
  DetectionResult detect(String filename, Uint8List content) {
    final text = utf8.decode(content);
    final allFound = CMBC_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return {'confidence': allFound ? 100 : 0, 'institutionId': 'cmbc-credit'};
  }
  
  Future<ParseResult<CmbcCreditRawTransaction>> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<CmbcCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    continue;
    }
    if (row[0] == HEADER_IDENTIFIERS.cardLast4 && row[1] == HEADER_IDENTIFIERS.txDate) {
    headerFound = true;
    continue;
    }
    if (headerFound) {
    dataRows.add(row);
    }
    }
    if (headerFound == null) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found (expected 卡号末四位, 交易日 columns)'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : (error).toString()}'});
    }
  }
  
  dynamic transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final cardNumber = row[0];
    final txDateStr = row[1];
    final postDateStr = row[2];
    final authorizationCode = row[3];
    final narration = row[4];
    final amountStr = row[5];
    final postDate = this.parseDate(postDateStr);
    if (postDate == null) {
    return err({'message': 'Invalid post date format: $postDateStr', 'context': {'input': postDateStr}});
    }
    final txDate = this.inferTransactionDate(txDateStr, postDate);
    if (txDate == null) {
    return err({'message': 'Invalid transaction date format: $txDateStr', 'context': {'input': txDateStr}});
    }
    Decimal amount;
    try {
    amount = Decimal(amountStr);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr', 'context': {'input': amountStr}});
    }
    amount = amount.negated();
    final _obj = this.parseNarration(narration);
    final description = _obj.description;
    final payee = _obj.payee;
    final originalAmount = _obj.originalAmount;
    final countryCode = _obj.countryCode;
    CmbcCreditCustomFields customFields = {};
    if (authorizationCode && authorizationCode.trim() != '') {
    customFields.authorizationCode = authorizationCode;
    }
    if (originalAmount) {
    customFields.originalAmount = originalAmount;
    }
    if (countryCode) {
    customFields.countryCode = countryCode;
    }
    final transaction = {'date': txDate, 'currency': 'CNY'};
    return ok(transaction);
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null || !RegExp(r'^\d{8}$').hasMatch(dateStr)) {
    return null;
    }
    final year = int.parse(dateStr.substring(0, 4));
    final month = int.parse(dateStr.substring(4, 6));
    final day = int.parse(dateStr.substring(6, 8));
    final date = Date(year, month - 1, day);
    return date.getTime().isNaN ? null : date;
  }
  
  DateTime? inferTransactionDate(String txDateStr, DateTime postDate) {
    if (txDateStr == null || !RegExp(r'^\d{4}$').hasMatch(txDateStr)) {
    return null;
    }
    final txMonth = int.parse(txDateStr.substring(0, 2));
    final txDay = int.parse(txDateStr.substring(2, 4));
    final postMonth = postDate.getMonth() + 1;
    final postYear = postDate.getFullYear();
    num txYear;
    if (txMonth > postMonth) {
    txYear = postYear - 1;
    } else {
    txYear = postYear;
    }
    final date = Date(txYear, txMonth - 1, txDay);
    return date.getTime().isNaN ? null : date;
  }
  
  dynamic parseNarration(String narration) {
    if (narration == null) {
    return {'description': '', 'payee': null};
    }
    final foreignMatch = FOREIGN_CURRENCY_PATTERN.firstMatch(narration);
    if (foreignMatch) {
    final country = foreignMatch[2];
    final amount = foreignMatch[3];
    final currency = foreignMatch[4];
    return {'description': '', 'payee': narration, 'originalAmount': '$amount $currency', 'countryCode': country};
    }
    if (narration.contains('-')) {
    final hyphenIdx = narration.indexOf('-');
    final description = narration.substring(0, hyphenIdx).trim();
    final payee = narration.substring(hyphenIdx + 1).trim();
    return {'payee': payee ?? null};
    }
    return {'description': narration, 'payee': null};
  }
  
}
