// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.215Z
// Source: TypeScript parser
// Parser: cmbc-credit

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert';

import 'package:csv/csv.dart' show parseCsv;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, ParseResult, ParseFailure, ParseError, ParseWarning;

abstract class CmbcCreditCustomFields implements Map<String, dynamic> {
  String get cardNumber;
  set cardNumber(String value);
  DateTime get postDate;
  set postDate(DateTime value);
  String get authorizationCode;
  String get originalAmount;
  String get countryCode;
}

typedef CmbcCreditRawTransaction = RawTransaction<CmbcCreditCustomFields>;

final List<String> CMBC_CREDIT_KEYWORDS = ['卡号末四位', '交易日'];

final MIN_REQUIRED_COLUMNS = 6;

final HEADER_IDENTIFIERS = {'cardLast4': '卡号末四位', 'txDate': '交易日'};

final FOREIGN_CURRENCY_PATTERN = RegExp(r'^(.*?)\s*?([A-Z]+)([-\d.]+)\s*([A-Z]+)$');

class CmbcCreditParser implements Parser<CmbcCreditRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final text = utf8.decode(content);
    return CMBC_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
  }
  
  ParseResult<CmbcCreditRawTransaction> parse(Uint8List content) {
    final text = utf8.decode(content);
    if (text.isEmpty || text.trim().isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseRows(text);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<CmbcCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join(','), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found after header'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic _parseRows(String content) {
    try {
    final allRows = parseCsv(content, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': true, 'record_delimiter': '\n'});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    continue;
    }
    if (row[0] == HEADER_IDENTIFIERS.cardLast4 && row[1] == HEADER_IDENTIFIERS.txDate) {
    headerFound = true;
    continue;
    }
    if (headerFound) {
    dataRows.add(row);
    }
    }
    if (headerFound.isEmpty) {
    return err({'type': 'INVALID_FORMAT', 'message': 'CSV header not found (expected 卡号末四位, 交易日 columns)'});
    }
    return ok(dataRows);
    } catch (error) {
    return err({'type': 'CSV_PARSE_ERROR', 'message': 'Failed to parse CSV: ${error is Exception ? error.toString() : String(error)}'});
    }
  }
  
  dynamic _transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS+, got ${row.length})', 'context': {}});
    }
    final cardNumber = row[0];
    final txDateStr = row[1];
    final postDateStr = row[2];
    final authorizationCode = row[3];
    final narration = row[4];
    final amountStr = row[5];
    final postDate = this.parseDate(postDateStr);
    if (postDate.isEmpty) {
    return err({'message': 'Invalid post date format: $postDateStr', 'context': {'input': postDateStr}});
    }
    final txDate = this.inferTransactionDate(txDateStr, postDate);
    if (txDate.isEmpty) {
    return err({'message': 'Invalid transaction date format: $txDateStr', 'context': {'input': txDateStr}});
    }
    Decimal amount;
    try {
    amount = Decimal(amountStr);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr', 'context': {'input': amountStr}});
    }
    amount = amount.negated();
    final { description, payee, originalAmount, countryCode } = this.parseNarration(narration);
    CmbcCreditCustomFields customFields = {};
    if (authorizationCode && authorizationCode.trim() != '') {
    customFields.authorizationCode = authorizationCode;
    }
    if (originalAmount) {
    customFields.originalAmount = originalAmount;
    }
    if (countryCode) {
    customFields.countryCode = countryCode;
    }
    CmbcCreditRawTransaction transaction = {'date': txDate, 'currency': 'CNY'};
    return ok(transaction);
  }
  
  DateTime? _parseDate(String dateStr) {
    if (dateStr.isEmpty || RegExp(r'^\d{8}$').hasMatch(dateStr).isEmpty) {
    return null;
    }
    final year = parseInt(dateStr.substring(0, 4), 10);
    final month = parseInt(dateStr.substring(4, 6), 10);
    final day = parseInt(dateStr.substring(6, 8), 10);
    final date = Date(year, month - 1, day);
    return isNaN(date.getTime()) ? null : date;
  }
  
  DateTime? _inferTransactionDate(String txDateStr, DateTime postDate) {
    if (txDateStr.isEmpty || RegExp(r'^\d{4}$').hasMatch(txDateStr).isEmpty) {
    return null;
    }
    final txMonth = parseInt(txDateStr.substring(0, 2), 10);
    final txDay = parseInt(txDateStr.substring(2, 4), 10);
    final postMonth = postDate.getMonth() + 1;
    final postYear = postDate.getFullYear();
    num txYear;
    if (txMonth > postMonth) {
    txYear = postYear - 1;
    } else {
    txYear = postYear;
    }
    final date = Date(txYear, txMonth - 1, txDay);
    return isNaN(date.getTime()) ? null : date;
  }
  
  dynamic _parseNarration(String narration) {
    if (narration.isEmpty) {
    return {'description': '', 'payee': null};
    }
    final foreignMatch = FOREIGN_CURRENCY_PATTERN.firstMatch(narration);
    if (foreignMatch) {
    final country = foreignMatch[2];
    final amount = foreignMatch[3];
    final currency = foreignMatch[4];
    return {'description': '', 'payee': narration, 'originalAmount': '$amount $currency', 'countryCode': country};
    }
    if (narration.contains('-')) {
    final hyphenIdx = narration.indexOf('-');
    final description = narration.substring(0, hyphenIdx).trim();
    final payee = narration.substring(hyphenIdx + 1).trim();
    return {'payee': payee ?? null};
    }
    return {'description': narration, 'payee': null};
  }
  
}

ParseFailure createParseFailure(ParseError['type'] type, String message, Map<String, dynamic>? context) {
  return ParseFailure(errors: [{}]);
}
