// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T06:00:18.891Z
// Source: TypeScript parser
// Parser: cmbc-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';
import 'dart:math';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning;

import '../../types/bank.dart' show CmbcDebitCustomFields;
// TODO: unmapped import: extractPdfText
// TODO: unmapped import: PdfTextItem

typedef CmbcDebitRawTransaction = RawTransaction<CmbcDebitCustomFields>;

final List<String> CMBC_DEBIT_KEYWORDS = ['\u6c11\u751f\u94f6\u884c', '\u4e2a\u4eba\u8d26\u6237\u5bf9\u8d26\u5355'];

final COLUMN_OFFSETS = [22, 56, 97, 173, 335, 413, 448, 482, 533, 568, 696];

final HEADER_KEYWORD = '\u5bf9\u65b9\u884c\u540d';

final END_KEYWORD = '______________';

final DATE_START_PATTERN = RegExp(r'^20\d{2}[\/\-]');

final CARD_NUMBER_PATTERN = RegExp(r'\u5ba2\u6237\u8d26\u53f7:([0-9]+)');

final REFUND_KEYWORD = '\u9000\u6b3e';

final Y_TOLERANCE = 3;

class CmbcDebitParser extends Parser<CmbcDebitRawTransaction> {
  DetectionResult detect(String filename, Uint8List content) {
    if (!filename.toLowerCase().endsWith('.pdf')) {
    return {'confidence': 0, 'institutionId': 'cmbc-debit'};
    }
    final text = utf8.decode(content);
    final allFound = CMBC_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return {'confidence': allFound ? 100 : 0, 'institutionId': 'cmbc-debit'};
  }
  
  Future<ParseResult<CmbcDebitRawTransaction>> parse(Uint8List content) {
    final textResult = /* TODO: AwaitExpression: await extractPdfText(content) */;
    if (!textResult.success) {
    return ParseFailure(errors: [{'type': 'FILE_READ_ERROR', 'message': textResult.error.message}]);
    }
    final _obj = textResult.value;
    final items = _obj.items;
    final fullText = _obj.fullText;
    final cardNumber = this.extractCardNumber(fullText);
    final dataItems = this.filterDataRegion(items);
    final rows = this.groupIntoRows(dataItems);
    List<CmbcDebitRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum, cardNumber);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.map((dynamic c) => c.content).toList().join('|'), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found in PDF table'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  List<PdfTextItem> filterDataRegion(List<PdfTextItem> items) {
    List<PdfTextItem> filtered = [];
    var dataStarted = false;
    for (final item in items) {
    if (dataStarted == null) {
    if (item.str.contains(HEADER_KEYWORD)) {
    dataStarted = true;
    }
    continue;
    }
    if (item.str.contains(END_KEYWORD)) {
    break;
    }
    filtered.add(item);
    }
    return filtered;
  }
  
  List<List<{ content: string; colIndex: number }>> groupIntoRows(List<PdfTextItem> items) {
    if (items.isEmpty) {
    return [];
    }
    final sorted = [...items].sort((dynamic a, dynamic b) { final yDiff = b.y - a.y;
    if (abs(yDiff) > Y_TOLERANCE) {
    return yDiff;
    }
    return a.x - b.x; });
    List<List<{ content: string; colIndex: number }>> rows = [];
    List<{ content: string; colIndex: number }> currentRow = [];
    var currentY = sorted[0].y;
    for (final item in sorted) {
    if (abs(item.y - currentY) <= Y_TOLERANCE) {
    final colIndex = this.findColumnIndex(item.x);
    currentRow.add({'content': item.str});
    } else {
    if (currentRow.isNotEmpty) {
    rows.add(currentRow);
    }
    final colIndex = this.findColumnIndex(item.x);
    currentRow = [{'content': item.str}];
    currentY = item.y;
    }
    }
    if (currentRow.isNotEmpty) {
    rows.add(currentRow);
    }
    return rows;
  }
  
  num findColumnIndex(num x) {
    for (var i = COLUMN_OFFSETS.length - 1; i >= 0; i--) {
    if (x >= COLUMN_OFFSETS[i]!) {
    return i;
    }
    }
    return 0;
  }
  
  List<String> rowToArray(List<{ content: string; colIndex: number }> row) {
    final maxCols = COLUMN_OFFSETS.length;
    List<String> cells = Array(maxCols).fill('');
    for (final cell in row) {
    final idx = min(cell.colIndex, maxCols - 1);
    if (cells[idx] != null) {
    cells[idx] += ' ' + cell.content;
    } else {
    cells[idx] = cell.content;
    }
    }
    final trimmed = cells.map((dynamic c) => c.replaceAll(RegExp(r'\n'), '').trim()).toList();
    if (trimmed[0] && DATE_START_PATTERN.hasMatch(trimmed[0])) {
    return ['', '', ...trimmed.substring(0, maxCols - 2)];
    }
    return trimmed;
  }
  
  String? extractCardNumber(String fullText) {
    final match = CARD_NUMBER_PATTERN.firstMatch(fullText);
    return match ? match[1]!.substring(match[1]!.length - 4) : null;
  }
  
  dynamic transformRow(List<{ content: string; colIndex: number }> row, num _lineNum, String? cardNumber) {
    final cells = this.rowToArray(row);
    final transactionTime = cells[2];
    if (transactionTime == null || transactionTime.trim().isEmpty) {
    return err({'message': /* TODO: FirstTemplateToken: `Missing transaction time` */, 'context': {}});
    }
    final date = this.parseDateTime(transactionTime);
    if (date == null) {
    return err({'message': 'Invalid transaction time format: $transactionTime', 'context': {}});
    }
    final amountStr = cells[4];
    final amountResult = this.parseAmount(amountStr);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    final documentType = cells[0];
    final documentNumber = cells[1];
    final summary = cells[3];
    final balance = cells[5];
    final cashTransferFlag = cells[6];
    final channel = cells[7];
    final institution = cells[8];
    final counterpartyInfo = cells[9];
    final counterpartyBank = cells[10];
    final isRefund = balance.contains(REFUND_KEYWORD);
    final _obj = this.parseCounterparty(counterpartyInfo);
    final payee = _obj.payee;
    CmbcDebitCustomFields customFields = {};
    if (cardNumber) {
    customFields.cardNumber = cardNumber;
    }
    if (documentType) {
    customFields.documentType = documentType;
    }
    if (documentNumber) {
    customFields.documentNumber = documentNumber;
    }
    if (cashTransferFlag) {
    customFields.cashTransferFlag = cashTransferFlag;
    }
    if (channel) {
    customFields.channel = channel;
    }
    if (institution) {
    customFields.institution = institution;
    }
    if (counterpartyInfo) {
    customFields.counterpartyInfo = counterpartyInfo;
    }
    if (counterpartyBank) {
    customFields.counterpartyBank = counterpartyBank;
    }
    if (isRefund) {
    customFields.isRefund = true;
    }
    final transaction = {'amount': amountResult.value, 'currency': 'CNY', 'description': summary ?? '', 'payee': payee ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
  DateTime? parseDateTime(String dateTimeStr) {
    if (dateTimeStr == null) {
    return null;
    }
    final normalized = dateTimeStr.trim().replaceAll(RegExp(r'\/'), '-');
    final fullMatch = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$').firstMatch(normalized);
    if (fullMatch) {
    final y = fullMatch[1];
    final mo = fullMatch[2];
    final d = fullMatch[3];
    final h = fullMatch[4];
    final mi = fullMatch[5];
    final s = fullMatch[6];
    final date = DateTime(int.parse(y), int.parse(mo) - 1 + 1, int.parse(d), int.parse(h), int.parse(mi), int.parse(s));
    return date.millisecondsSinceEpoch.isNaN ? null : date;
    }
    final dateMatch = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})$').firstMatch(normalized);
    if (dateMatch) {
    final y = dateMatch[1];
    final mo = dateMatch[2];
    final d = dateMatch[3];
    final date = DateTime(int.parse(y), int.parse(mo) - 1 + 1, int.parse(d));
    return date.millisecondsSinceEpoch.isNaN ? null : date;
    }
    return null;
  }
  
  dynamic parseAmount(String amountStr) {
    if (amountStr == null || amountStr.trim().isEmpty) {
    return err({'message': 'Invalid amount: empty'});
    }
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ok(amount);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
  dynamic parseCounterparty(String counterpartyInfo) {
    if (counterpartyInfo == null) {
    return {'payee': '', 'payeeAccount': null};
    }
    if (counterpartyInfo.contains('/')) {
    final parts = counterpartyInfo.split('/');
    return {'payee': parts[0].trim(), 'payeeAccount': parts[1].trim() ?? null};
    }
    return {'payee': counterpartyInfo.trim(), 'payeeAccount': null};
  }
  
}
