// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-06T10:05:44.352Z
// Source: TypeScript parser
// Parser: final-verification-bank

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element

import 'dart:convert' show iconv;

import 'package:csv/csv.dart' show parse;
import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/types.dart' show Parser, RawTransaction, ParseResult, ParseErrorType, ParseWarning;

final createError = (ParseErrorType type, String message) => ({'success': false, 'errors': [{'type': type, 'message': message}]});

abstract class FinalVerificationBankCustomFields implements Map<String, dynamic> {
  String get transactionId;
}

typedef FinalVerificationBankTransaction = RawTransaction<FinalVerificationBankCustomFields>;

final IDENTIFIER_KEYWORDS = ['Final Verification Bank'];

final HEADERS = ['date', 'amount', 'currency', 'description'];

final MIN_COLUMNS = 4;

class FinalVerificationBankParser implements Parser<FinalVerificationBankTransaction> {
  bool identify(String filename, Uint8List content) {
    final utf8Text = utf8.decode(content);
    if (IDENTIFIER_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    return true;
    }
    try {
    final gbkText = iconv.decode(content, 'GBK');
    return IDENTIFIER_KEYWORDS.every((dynamic keyword) => gbkText.contains(keyword));
    } catch (e) {
    return false;
    }
  }
  
  ParseResult<FinalVerificationBankTransaction> parse(Uint8List content) {
    String text;
    try {
    final utf8Text = utf8.decode(content);
    if (IDENTIFIER_KEYWORDS.every((dynamic keyword) => utf8Text.contains(keyword))) {
    text = utf8Text;
    } else {
    text = iconv.decode(content, 'GBK');
    }
    } catch (e) {
    return createError('ENCODING_ERROR', 'Failed to decode file content: Unknown encoding');
    }
    if (text.isEmpty || text.trim().isEmpty) {
    return createError('INVALID_FORMAT', 'File is empty');
    }
    List<List<String>> records;
    try {
    records = parse(text, {'skip_empty_lines': true, 'trim': true, 'relax_column_count': false});
    } catch (e) {
    return createError('INVALID_FORMAT', 'Failed to parse CSV: ${e is Exception ? e.toString() : String(e)}');
    }
    if (records.isEmpty) {
    return createError('INVALID_FORMAT', 'No data found in file');
    }
    var headerIndex = -1;
    for (var i = 0; i < records.length; i++) {
    if (records[i].length >= HEADERS.length) {
    final isHeader = HEADERS.every((dynamic header, dynamic index) => records[i][index].toLowerCase() == header.toLowerCase());
    if (isHeader) {
    headerIndex = i;
    break;
    }
    }
    }
    if (headerIndex == -1) {
    return createError('INVALID_FORMAT', 'Invalid CSV header. Expected: date, amount, currency, description');
    }
    List<FinalVerificationBankTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = headerIndex + 1; i < records.length; i++) {
    final row = records[i];
    if (row.isEmpty || (row.length == 1 && row[0] == '')) {
    continue;
    }
    final parseResult = this.transformRow(row, i + 1);
    if (parseResult.success) {
    transactions.add(parseResult.value);
    } else {
    warnings.add({'type': 'UNUSUAL_VALUE', 'message': 'Row ${i + 1}: ${parseResult.error}'});
    }
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  bool _isValidHeader(List<String> row) {
    if (row.length < HEADERS.length) {
    return false;
    }
    return HEADERS.every((dynamic header, dynamic index) => row[index].toLowerCase() == header.toLowerCase());
  }
  
  dynamic _transformRow(List<String> row, num lineNum) {
    if (row.length < MIN_COLUMNS) {
    return err('Insufficient columns (expected $MIN_COLUMNS, got ${row.length})');
    }
    final dateStr = row[0];
    final amountStr = row[1];
    final currency = row[2];
    final description = row[3];
    final date = this.parseDate(dateStr);
    if (date.isEmpty) {
    return err('Invalid date format: $dateStr');
    }
    Decimal amount;
    try {
    final cleanAmountStr = amountStr.replaceFirst(RegExp(r'[+-]'), '');
    amount = Decimal(cleanAmountStr);
    if (amountStr.trim().startsWith('-')) {
    amount = amount.neg();
    }
    } catch (e) {
    return err('Invalid amount format: $amountStr');
    }
    if (currency.isEmpty || currency.length != 3) {
    return err('Invalid currency code: $currency');
    }
    FinalVerificationBankTransaction transaction = {'currency': currency.toUpperCase(), 'description': description ?? '', 'metadata': {'rowNumber': lineNum}};
    return ok(transaction);
  }
  
  DateTime? _parseDate(String dateStr) {
    if (dateStr.isEmpty) {
    return null;
    }
    if (RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(dateStr)) {
    final date = Date(dateStr);
    return isNaN(date.getTime()) ? null : date;
    }
    return null;
  }
  
}
