// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T09:04:28.737Z
// Source: TypeScript parser
// Parser: icbc-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// TODO: This parser uses cheerio for HTML parsing which has no Dart equivalent.
// Manual conversion required.
