// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T06:41:39.387Z
// Source: TypeScript parser
// Parser: icbc-debit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning;

import '../../types/bank.dart' show IcbcDebitCustomFields;
// TODO: unmapped import: readPdfTable, PdfTableReadResult

typedef IcbcRawTransaction = RawTransaction<IcbcDebitCustomFields>;

final List<String> ICBC_DEBIT_KEYWORDS = ['中国工商银行借记账户历史明细'];

final HEADER_FIRST_CELL = '交易日期';

final EXPECTED_COLUMNS = 13;

final CARD_NUMBER_PATTERN = RegExp(r'(\d{19})');

final ACCOUNT_HOLDER_PATTERN = RegExp(r'户名[：:\s]*([^\s\d]+)');

final Map<String, dynamic> CURRENCY_MAP = String, dynamic('人民币': 'CNY', '美元': 'USD', '欧元': 'EUR', '港币': 'HKD', '日元': 'JPY', '英镑': 'GBP', '澳元': 'AUD');

class IcbcDebitParser extends Parser<IcbcRawTransaction> {
  bool identify(String filename, Uint8List content) {
    if (!filename.toLowerCase().endsWith('.pdf')) {
    return false;
    }
    final text = utf8.decode(content);
    final allFound = ICBC_DEBIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return (allFound ? 100 : 0) > 0;
  }
  
  ParseResult<IcbcRawTransaction> parse(Uint8List content) {
    final tableResult = /* TODO: AwaitExpression: await this.extractTable(content) */;
    if (!tableResult.success) {
    return ParseFailure(errors: [ParseWarning(type: 'FILE_READ_ERROR', message: tableResult.error.message)]);
    }
    final _obj = tableResult.value;
    final rows = _obj.rows;
    final fullText = _obj.fullText;
    final cardNumber = this.extractCardNumber(fullText);
    final accountHolder = this.extractAccountHolder(fullText);
    List<IcbcRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum, cardNumber, accountHolder);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: result.error.message, line: lineNum, raw: row.join('|'), context: result.error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found in PDF table'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  PdfTableReadResult extractTable(Uint8List content) {
    return readPdfTable(content, {'headerFirstCell': HEADER_FIRST_CELL, 'yTolerance': 3, 'xTolerance': 10, 'minColumnWidth': 30});
  }
  
  String? extractCardNumber(String fullText) {
    final match = CARD_NUMBER_PATTERN.firstMatch(fullText);
    return match ? match[1]!.substring(match[1]!.length - 4) : null;
  }
  
  String? extractAccountHolder(String fullText) {
    final match = ACCOUNT_HOLDER_PATTERN.firstMatch(fullText);
    return match ? match[1]!.trim() : null;
  }
  
  dynamic transformRow(List<String> row, num _lineNum, String? cardNumber, String? _accountHolder) {
    if (row.length < EXPECTED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $EXPECTED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final dateTimeStr = row[0];
    final accountType = row[2];
    final currencyName = row[4];
    final cashTransferFlag = row[5];
    final summary = row[6];
    final region = row[7];
    final amountStr = row[8];
    final counterpartyName = row[10];
    final counterpartyAccount = row[11];
    final channel = row[12];
    final date = this.parseDateTime(dateTimeStr);
    if (date == null) {
    return err({'message': 'Invalid datetime format: $dateTimeStr', 'context': {}});
    }
    final currency = CURRENCY_MAP[currencyName] || currencyName;
    final amountResult = this.parseAmount(amountStr);
    if (!amountResult.success) {
    return err({'message': amountResult.error.message, 'context': {}});
    }
    IcbcDebitCustomFields customFields = {};
    if (cardNumber) {
    customFields.cardNumber = cardNumber;
    }
    if (accountType) {
    customFields.accountType = accountType;
    }
    if (cashTransferFlag) {
    customFields.cashTransferFlag = cashTransferFlag;
    }
    if (channel) {
    customFields.channel = channel;
    }
    if (region) {
    customFields.region = region;
    }
    if (counterpartyName) {
    customFields.counterpartyName = counterpartyName;
    }
    if (counterpartyAccount) {
    customFields.counterpartyAccount = counterpartyAccount;
    }
    final transaction = {'amount': amountResult.value, 'description': summary ?? '', 'payee': counterpartyName ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ParseSuccess(data: transaction);
  }
  
  DateTime? parseDateTime(String dateTimeStr) {
    if (dateTimeStr == null) {
    return null;
    }
    final trimmed = dateTimeStr.trim();
    final combinedPattern = RegExp(r'^(\d{4})-(\d{2})-(\d{2})(\d{2})(\d{2})(\d{2})$');
    final combinedMatch = combinedPattern.firstMatch(trimmed);
    if (combinedMatch) {
    final year = int.parse(combinedMatch[1]);
    final month = int.parse(combinedMatch[2]);
    final day = int.parse(combinedMatch[3]);
    final hours = int.parse(combinedMatch[4]);
    final minutes = int.parse(combinedMatch[5]);
    final seconds = int.parse(combinedMatch[6]);
    final date = DateTime(year, month - 1 + 1, day, hours, minutes, seconds);
    return (date.millisecondsSinceEpoch).toDouble().isNaN ? null : date;
    }
    final dateOnlyPattern = RegExp(r'^(\d{4})-(\d{2})-(\d{2})$');
    final dateOnlyMatch = dateOnlyPattern.firstMatch(trimmed);
    if (dateOnlyMatch) {
    final year = int.parse(dateOnlyMatch[1]);
    final month = int.parse(dateOnlyMatch[2]);
    final day = int.parse(dateOnlyMatch[3]);
    final date = DateTime(year, month - 1 + 1, day);
    return (date.millisecondsSinceEpoch).toDouble().isNaN ? null : date;
    }
    return null;
  }
  
  dynamic parseAmount(String amountStr) {
    if (amountStr == null || amountStr.trim().isEmpty) {
    return err({'message': 'Invalid amount: empty'});
    }
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ParseSuccess(data: amount);
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
}
