// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-16T05:31:36.858Z
// Source: TypeScript parser
// Parser: icbc-credit-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'dart:convert';

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, ParseResult, ParseWarning, ParseError;

import '../../types/bank.dart' show IcbcCreditCustomFields;
// TODO: unmapped import: cheerio

typedef IcbcCreditRawTransaction = RawTransaction<IcbcCreditCustomFields>;

final List<String> ICBC_CREDIT_KEYWORDS = ['\u5de5\u5546\u94f6\u884c', '\u4fe1\u7528\u5361'];

final HEADER_FIRST_CELL = '\u4ea4\u6613\u65e5';

final EXPENSE_MARKER = '(\u652f\u51fa)';

final INCOME_MARKER = '(\u5b58\u5165)';

final REFUND_KEYWORD = '\u9000\u6b3e';

final EXPECTED_COLUMNS = 6;

final AMOUNT_CURRENCY_PATTERN = RegExp(r'^([0-9,.\-]+)\/([A-Z]{3})$');

class IcbcCreditParser extends Parser<IcbcCreditRawTransaction> {
  DetectionResult detect(String filename, Uint8List content) {
    final ext = filename.toLowerCase();
    if (!ext.endsWith('.html') && !ext.endsWith('.htm') && !ext.endsWith('.eml')) {
    return {'confidence': 0, 'institutionId': 'icbc-credit'};
    }
    final text = utf8.decode(content);
    final allFound = ICBC_CREDIT_KEYWORDS.every((dynamic keyword) => text.contains(keyword));
    return {'confidence': allFound ? 100 : 0, 'institutionId': 'icbc-credit'};
  }
  
  Future<ParseResult<IcbcCreditRawTransaction>> parse(Uint8List content) {
    final html = utf8.decode(content);
    if (html == null || html.trim().isEmpty) {
    return ParseFailure(errors: [{'type': 'INVALID_FORMAT', 'message': 'File is empty'}]);
    }
    final $ = cheerio.load(html);
    final tableResult = this.findTable($);
    if (!tableResult.success) {
    return ParseFailure(errors: [tableResult.error]);
    }
    final rows = tableResult.value;
    List<IcbcCreditRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add({'type': 'SKIPPED_ROW', 'message': result.error.message, 'line': lineNum, 'raw': row.join('|'), 'context': result.error.context});
    }
    }
    if (rows.isEmpty) {
    warnings.add({'type': 'SKIPPED_ROW', 'message': 'No data rows found in HTML table'});
    }
    return ok(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic findTable(cheerio.CheerioAPI $) {
    final tables = $('table');
    if (tables.isEmpty) {
    return err({'type': ('INVALID_FORMAT' as const), 'message': 'No HTML table found in content'});
    }
    List<List<String>> dataRows = [];
    tables.each((dynamic _tableIdx, dynamic table) { if (dataRows.isNotEmpty) {
    return;
    }
    final $table = $(table);
    final rows = $table.firstWhere('tr');
    var headerFound = false;
    rows.each((dynamic _rowIdx, dynamic row) { final $row = $(row);
    final cells = $row.firstWhere('td, th');
    List<String> cellValues = [];
    cells.each((dynamic _cellIdx, dynamic cell) { cellValues.add($(cell).text().trim()); });
    if (headerFound == null) {
    if (cellValues.isNotEmpty && cellValues.any((dynamic c) => c == HEADER_FIRST_CELL)) {
    headerFound = true;
    }
    return;
    }
    if (cellValues.length >= EXPECTED_COLUMNS - 1) {
    dataRows.add(cellValues);
    } }); });
    if (dataRows.isEmpty) {
    return err({'type': ('INVALID_FORMAT' as const), 'message': 'No data rows found (expected header with "$HEADER_FIRST_CELL")'});
    }
    return ok(dataRows);
  }
  
  dynamic transformRow(List<String> row, num _lineNum) {
    if (row.length < EXPECTED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $EXPECTED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final cardLast4 = row[0].trim();
    final dateStr = row[1].trim();
    final txnType = row[2].trim();
    final merchant = row[3].trim();
    final txnAmountStr = row[4].trim();
    final dstAmountStr = row[5].trim();
    if (dateStr == null && dstAmountStr == null) {
    return err({'message': 'Empty row (no date or amount)'});
    }
    final date = this.parseDate(dateStr);
    if (date == null) {
    return err({'message': 'Invalid date format: $dateStr', 'context': {}});
    }
    final dstResult = this.parseAmountWithDirection(dstAmountStr);
    if (!dstResult.success) {
    return err({'message': dstResult.error.message, 'context': {}});
    }
    final _obj = dstResult.value;
    final dstAmount = _obj.amount;
    final currency = _obj.currency;
    final isExpense = _obj.isExpense;
    final signedAmount = isExpense ? dstAmount.negated() : dstAmount;
    final isRefund = txnType.contains(REFUND_KEYWORD);
    String? originalAmount;
    if (txnAmountStr) {
    final txnParsed = this.parseAmountAndCurrency(txnAmountStr);
    if (txnParsed.success && txnParsed.value.currency != currency) {
    originalAmount = '${txnParsed.value.amount.toString()} ${txnParsed.value.currency}';
    }
    }
    IcbcCreditCustomFields customFields = {};
    if (cardLast4) {
    customFields.cardNumber = cardLast4;
    }
    if (txnType) {
    customFields.transactionType = txnType;
    }
    if (originalAmount) {
    customFields.originalAmount = originalAmount;
    }
    if (isRefund) {
    customFields.isRefund = true;
    }
    final transaction = {'amount': signedAmount, 'description': txnType ?? '', 'payee': merchant ?? null, 'customFields': (customFields as Map).keys.toList().isNotEmpty ? customFields : null};
    return ok(transaction);
  }
  
  dynamic parseAmountWithDirection(String text) {
    bool isExpense;
    var cleanedText = text;
    if (text.endsWith(EXPENSE_MARKER)) {
    isExpense = true;
    cleanedText = text.replaceAll(EXPENSE_MARKER, '');
    } else if (text.endsWith(INCOME_MARKER)) {
    isExpense = false;
    cleanedText = text.replaceAll(INCOME_MARKER, '');
    } else {
    isExpense = true;
    }
    final amountResult = this.parseAmountAndCurrency(cleanedText);
    if (!amountResult.success) {
    return err(amountResult.error);
    }
    return ok({'amount': amountResult.value.amount, 'currency': amountResult.value.currency});
  }
  
  dynamic parseAmountAndCurrency(String text) {
    final match = AMOUNT_CURRENCY_PATTERN.firstMatch(text.trim());
    if (match == null) {
    return err({'message': 'Invalid amount/currency format: $text'});
    }
    final amountStr = match[1];
    final currencyStr = match[2];
    try {
    final cleaned = amountStr.replaceAll(RegExp(r','), '').trim();
    final amount = Decimal(cleaned);
    if (!amount.isFinite()) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
    return ok({'currency': currencyStr});
    } catch (e) {
    return err({'message': 'Invalid amount: $amountStr'});
    }
  }
  
  DateTime? parseDate(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final match = RegExp(r'^(\d{4})-(\d{1,2})-(\d{1,2})$').firstMatch(dateStr.trim());
    if (match == null) {
    return null;
    }
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!);
    final day = int.parse(match[3]!);
    final date = Date(year, month - 1, day);
    return date.getTime().isNaN ? null : date;
  }
  
}
