// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-20T02:15:31.409Z
// Source: TypeScript parser
// Parser: wechat-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/cn/chinese_csv_parser.dart' show ChineseCsvParser;
import 'package:firela/parser/src/core/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, WeChatCustomFields;
import 'package:firela/parser/src/utils/parser_helpers.dart' show categorizeWechatStatus, isValidWechatFlowType, WechatStatusCategory;

typedef WechatRawTransaction = RawTransaction<WeChatCustomFields>;

final List<String> WECHAT_CSV_KEYWORDS = ['微信支付', '交易时间'];

final HEADER_IDENTIFIER = '交易时间';

final MIN_REQUIRED_COLUMNS = 11;

final NEUTRAL_FLOW_TYPE = '/';

final CLOSED_STATUS_KEYWORD = '已关闭';

class WechatParser extends ChineseCsvParser<WechatRawTransaction> {
  final institutionId = 'wechat';
  final identifyKeywords = WECHAT_CSV_KEYWORDS;
  final minColumns = MIN_REQUIRED_COLUMNS;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIER && row.length >= MIN_REQUIRED_COLUMNS;
  }
  
  @override
  RowTransformResult transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS, got ${row.length})', 'context': {'row': row}});
    }
    final csvRow = Map<String, String>(transactionTime: row[0], transactionType: row[1], counterparty: row[2], product: row[3], flowType: row[4], amount: row[5], paymentMethod: row[6], status: row[7], transactionId: row[8], merchantOrderId: row[9], remarks: row[10]);
    if (csvRow['flowType']! == NEUTRAL_FLOW_TYPE) {
    return err({'message': 'Skipped neutral flow type: ${csvRow['flowType']!}', 'context': {'flowType': csvRow['flowType']!, 'row': row, 'skip': true}});
    }
    if (csvRow['status']!.contains(CLOSED_STATUS_KEYWORD) != null) {
    return err({'message': 'Skipped closed transaction: ${csvRow['status']!}', 'context': {'status': csvRow['status']!, 'row': row, 'skip': true}});
    }
    if (isValidWechatFlowType(csvRow['flowType']!) == null) {
    return err({'message': 'Invalid flow type: ${csvRow['flowType']!}', 'context': {'flowType': csvRow['flowType']!, 'row': row}});
    }
    final date = this.parseDateTime(csvRow['transactionTime']!);
    if (date == null) {
    return err({'message': 'Invalid date format: ${csvRow['transactionTime']!}', 'context': {'input': csvRow['transactionTime']!, 'row': row}});
    }
    final amount = this.parseAmount(csvRow['amount']!, csvRow['flowType']!);
    if (amount == null) {
    return err({'message': 'Invalid amount: ${csvRow['amount']!}', 'context': {'input': csvRow['amount']!, 'row': row}});
    }
    final statusCategory = categorizeWechatStatus(csvRow['status']!);
    final customStatus = this.mapToCustomStatus(statusCategory, csvRow['status']!);
    final customFields = WeChatCustomFields(status: customStatus, transactionType: csvRow['transactionType']! ?? null, orderNo: csvRow['transactionId']! ?? null);
    Map<String, dynamic> metadata = {};
    if (csvRow['paymentMethod']! != null) {
    metadata['paymentMethod'] = csvRow['paymentMethod']!;
    }
    if (csvRow['merchantOrderId']! != null) {
    metadata['merchantOrderId'] = csvRow['merchantOrderId']!;
    }
    final description = csvRow['product']! ?? csvRow['transactionType']! ?? '';
    final transaction = WechatRawTransaction(date: date, amount: amount, currency: 'CNY', description: description, payee: csvRow['counterparty']! ?? null, metadata: (metadata as Map).keys.toList().isNotEmpty ? metadata : null, customFields: customFields);
    return ok(transaction);
  }
  
  DateTime? parseDateTime(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final trimmed = dateStr.trim();
    final match = RegExp(r'^(\d{4})[-/](\d{1,2})[-/](\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$').firstMatch(trimmed);
    if (match != null) {
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!) - 1;
    final day = int.parse(match[3]!);
    final hour = int.parse(match[4]!);
    final minute = int.parse(match[5]!);
    final second = int.parse(match[6]!);
    final date = DateTime(year.round(), (month + 1).round(), day.round(), hour.round(), minute.round(), second.round());
    return (date.millisecondsSinceEpoch as num).isNaN != null ? null : date;
    }
    return null;
  }
  
  Decimal? parseAmount(String amountStr, String flowType) {
    if (amountStr == null) {
    return null;
    }
    var cleaned = amountStr.trim();
    if (cleaned.startsWith('¥') || cleaned.startsWith('￥')) {
    cleaned = cleaned.substring(1).trim();
    }
    cleaned = cleaned.replaceAll(RegExp(r','), '');
    try {
    final amount = Decimal.parse((cleaned).toString());
    if (true == null) {
    return null;
    }
    if (flowType == '支出') {
    return -amount;
    }
    return amount;
    } catch (e) {
    return null;
    }
  }
  
  String mapToCustomStatus(WechatStatusCategory category, String originalStatus) {
    switch (category) {
    case 'success':
    return '支付成功';
    break;
    case 'refund':
    return '已退款';
    break;
    case 'failed':
    return '已关闭';
    break;
    default:
    if (originalStatus.contains('退款') != null) {
    return '已退款';
    }
    if (originalStatus.contains('关闭') != null || originalStatus.contains('失败') != null) {
    return '已关闭';
    }
    return '支付成功';
    break;
    }
  }
  
}
