// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T06:00:16.878Z
// Source: TypeScript parser
// Parser: wechat-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/csv_parser_base.dart' show RowTransformResult;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show RawTransaction, WeChatCustomFields;

import '../chinese-csv-parser.dart' show ChineseCsvParser;
import '../types/wechat.dart' show WechatCsvRow, categorizeWechatStatus, isValidWechatFlowType;

typedef WechatRawTransaction = RawTransaction<WeChatCustomFields>;

final List<String> WECHAT_CSV_KEYWORDS = ['微信支付', '交易时间'];

final HEADER_IDENTIFIER = '交易时间';

final MIN_REQUIRED_COLUMNS = 11;

final NEUTRAL_FLOW_TYPE = '/';

final CLOSED_STATUS_KEYWORD = '已关闭';

class WechatParser extends ChineseCsvParser<WechatRawTransaction> {
  final dynamic institutionId = 'wechat';
  final dynamic identifyKeywords = WECHAT_CSV_KEYWORDS;
  final dynamic minColumns = MIN_REQUIRED_COLUMNS;
  @override
  bool isHeaderRow(List<String> row) {
    return row[0] == HEADER_IDENTIFIER && row.length >= MIN_REQUIRED_COLUMNS;
  }
  
  @override
  RowTransformResult<WechatRawTransaction> transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final csvRow = {'transactionTime': row[0], 'transactionType': row[1], 'counterparty': row[2], 'product': row[3], 'flowType': row[4], 'amount': row[5], 'paymentMethod': row[6], 'status': row[7], 'transactionId': row[8], 'merchantOrderId': row[9], 'remarks': row[10]};
    if (csvRow.flowType == NEUTRAL_FLOW_TYPE) {
    return err({'message': 'Skipped neutral flow type: ${csvRow.flowType}', 'context': {'flowType': csvRow.flowType, 'skip': true}});
    }
    if (csvRow.status.contains(CLOSED_STATUS_KEYWORD)) {
    return err({'message': 'Skipped closed transaction: ${csvRow.status}', 'context': {'status': csvRow.status, 'skip': true}});
    }
    if (!isValidWechatFlowType(csvRow.flowType)) {
    return err({'message': 'Invalid flow type: ${csvRow.flowType}', 'context': {'flowType': csvRow.flowType}});
    }
    final date = this.parseDateTime(csvRow.transactionTime);
    if (date == null) {
    return err({'message': 'Invalid date format: ${csvRow.transactionTime}', 'context': {'input': csvRow.transactionTime}});
    }
    final amount = this.parseAmount(csvRow.amount, csvRow.flowType);
    if (amount == null) {
    return err({'message': 'Invalid amount: ${csvRow.amount}', 'context': {'input': csvRow.amount}});
    }
    final statusCategory = categorizeWechatStatus(csvRow.status);
    final customStatus = this.mapToCustomStatus(statusCategory, csvRow.status);
    final customFields = {'status': customStatus, 'transactionType': csvRow.transactionType ?? null, 'orderNo': csvRow.transactionId ?? null};
    Map<String, dynamic> metadata = {};
    if (csvRow.paymentMethod != null) {
    metadata['paymentMethod'] = csvRow.paymentMethod;
    }
    if (csvRow.merchantOrderId != null) {
    metadata['merchantOrderId'] = csvRow.merchantOrderId;
    }
    final description = csvRow.product ?? csvRow.transactionType ?? '';
    final transaction = {'currency': 'CNY', 'payee': csvRow.counterparty ?? null, 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ok(transaction);
  }
  
  DateTime? parseDateTime(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final trimmed = dateStr.trim();
    final match = RegExp(r'^(\d{4})[-/](\d{1,2})[-/](\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$').firstMatch(trimmed);
    if (match) {
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!) - 1;
    final day = int.parse(match[3]!);
    final hour = int.parse(match[4]!);
    final minute = int.parse(match[5]!);
    final second = int.parse(match[6]!);
    final date = DateTime(year, month + 1, day, hour, minute, second);
    return date.millisecondsSinceEpoch.isNaN ? null : date;
    }
    return null;
  }
  
  Decimal? parseAmount(String amountStr, String flowType) {
    if (amountStr == null) {
    return null;
    }
    var cleaned = amountStr.trim();
    if (cleaned.startsWith('¥') || cleaned.startsWith('￥')) {
    cleaned = cleaned.substring(1).trim();
    }
    cleaned = cleaned.replaceAll(RegExp(r','), '');
    try {
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return null;
    }
    if (flowType == '支出') {
    return amount.neg();
    }
    return amount;
    } catch (e) {
    return null;
    }
  }
  
  dynamic mapToCustomStatus(ReturnType<typeof categorizeWechatStatus> category, String originalStatus) {
    switch (category) {
    case 'success':
    return '支付成功';
    break;
    case 'refund':
    return '已退款';
    break;
    case 'failed':
    return '已关闭';
    break;
    default:
    if (originalStatus.contains('退款')) {
    return '已退款';
    }
    if (originalStatus.contains('关闭') || originalStatus.contains('失败')) {
    return '已关闭';
    }
    return '支付成功';
    break;
    }
  }
  
}
