// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T12:52:11.072Z
// Source: TypeScript parser
// Parser: wechat-xlsx-parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:decimal/decimal.dart' show Decimal;
import 'package:firela/parser/src/result.dart';
import 'package:firela/parser/src/types.dart' show Parser, DetectionResult, RawTransaction, WeChatCustomFields, ParseResult, ParseError, ParseWarning, createParseFailure;

import '../types/wechat.dart' show WechatCsvRow, categorizeWechatStatus, isValidWechatFlowType;
// TODO: unmapped import: XLSX

typedef WechatRawTransaction = RawTransaction<WeChatCustomFields>;

final List<String> WECHAT_XLSX_KEYWORDS = ['微信支付'];

final HEADER_IDENTIFIER = '交易时间';

final MIN_REQUIRED_COLUMNS = 11;

final NEUTRAL_FLOW_TYPE = '/';

final CLOSED_STATUS_KEYWORD = '已关闭';

final XLSX_SIGNATURE = [0x50, 0x4b];

final XLSX_EXTENSIONS = ['.xlsx', '.xls'];

class WechatXlsxParser extends Parser<WechatRawTransaction> {
  bool identify(String filename, Uint8List content) {
    final lowerFilename = filename.toLowerCase();
    final hasXlsxExtension = XLSX_EXTENSIONS.any((dynamic ext) => lowerFilename.endsWith(ext));
    if (!hasXlsxExtension) {
    return false;
    }
    final hasSignature = content.length >= 2 && content[0] == XLSX_SIGNATURE[0]! && content[1] == XLSX_SIGNATURE[1]!;
    final filenameSuggestsWechat = lowerFilename.contains('wechat') || lowerFilename.contains('weixin');
    if (filenameSuggestsWechat || hasSignature) {
    return true;
    }
    return false;
  }
  
  ParseResult<WechatRawTransaction> parse(Uint8List content) {
    if (content.isEmpty || content.isEmpty) {
    return createParseFailure('INVALID_FORMAT', 'File is empty');
    }
    final rowsResult = this.parseXlsxRows(content);
    if (!rowsResult.success) {
    return ParseFailure(errors: [rowsResult.error]);
    }
    final rows = rowsResult.value;
    List<WechatRawTransaction> transactions = [];
    List<ParseWarning> warnings = [];
    for (var i = 0; i < rows.length; i++) {
    final row = rows[i];
    final lineNum = i + 1;
    final result = this.transformRow(row, lineNum);
    if (result.success != null) {
    transactions.add(result.value);
    } else {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: result.error.message, line: lineNum, raw: row.join(','), context: result.error.context));
    }
    }
    if (rows.isEmpty) {
    warnings.add(ParseWarning(type: 'SKIPPED_ROW', message: 'No data rows found after header'));
    }
    return ParseSuccess(data: transactions, warnings: warnings.isNotEmpty ? warnings : null);
  }
  
  dynamic parseXlsxRows(Uint8List content) {
    try {
    final workbook = XLSX.read(content, {'type': 'array'});
    final sheetName = workbook.SheetNames[0];
    if (sheetName == null) {
    return err(ParseWarning(type: 'INVALID_FORMAT', message: 'XLSX file has no sheets'));
    }
    final sheet = workbook.Sheets[sheetName];
    final allRows = XLSX.utils.sheet_to_json(sheet, {'header': 1, 'defval': ''});
    var headerFound = false;
    List<List<String>> dataRows = [];
    for (final row in allRows) {
    final strRow = row.map((dynamic cell) => String.fromCharCode(cell ?? '')).toList();
    if (headerFound == null) {
    if (strRow[0] == HEADER_IDENTIFIER && strRow.length >= MIN_REQUIRED_COLUMNS) {
    headerFound = true;
    }
    continue;
    }
    if (strRow.length >= MIN_REQUIRED_COLUMNS) {
    dataRows.add(strRow);
    }
    }
    if (headerFound == null) {
    return err(ParseWarning(type: 'INVALID_FORMAT', message: 'XLSX header not found (expected transaction time as first column header)'));
    }
    return ParseSuccess(data: dataRows);
    } catch (error) {
    return err(ParseWarning(type: 'CSV_PARSE_ERROR', message: 'Failed to parse XLSX: ${error is Exception ? error.toString() : String.fromCharCode(error)}'));
    }
  }
  
  dynamic transformRow(List<String> row, num _lineNum) {
    if (row.length < MIN_REQUIRED_COLUMNS) {
    return err({'message': 'Row has insufficient columns (expected $MIN_REQUIRED_COLUMNS, got ${row.length})', 'context': {}});
    }
    final csvRow = {'transactionTime': row[0], 'transactionType': row[1], 'counterparty': row[2], 'product': row[3], 'flowType': row[4], 'amount': row[5], 'paymentMethod': row[6], 'status': row[7], 'transactionId': row[8], 'merchantOrderId': row[9], 'remarks': row[10]};
    if (csvRow.flowType == NEUTRAL_FLOW_TYPE) {
    return err({'message': 'Skipped neutral flow type: ${csvRow.flowType}', 'context': {'flowType': csvRow.flowType, 'skip': true}});
    }
    if (csvRow.status.contains(CLOSED_STATUS_KEYWORD)) {
    return err({'message': 'Skipped closed transaction: ${csvRow.status}', 'context': {'status': csvRow.status, 'skip': true}});
    }
    if (!isValidWechatFlowType(csvRow.flowType)) {
    return err({'message': 'Invalid flow type: ${csvRow.flowType}', 'context': {'flowType': csvRow.flowType}});
    }
    final date = this.parseDateTime(csvRow.transactionTime);
    if (date == null) {
    return err({'message': 'Invalid date format: ${csvRow.transactionTime}', 'context': {'input': csvRow.transactionTime}});
    }
    final amount = this.parseAmount(csvRow.amount, csvRow.flowType);
    if (amount == null) {
    return err({'message': 'Invalid amount: ${csvRow.amount}', 'context': {'input': csvRow.amount}});
    }
    final statusCategory = categorizeWechatStatus(csvRow.status);
    final customStatus = this.mapToCustomStatus(statusCategory, csvRow.status);
    final customFields = {'status': customStatus, 'transactionType': csvRow.transactionType ?? null, 'orderNo': csvRow.transactionId ?? null};
    Map<String, dynamic> metadata = {};
    if (csvRow.paymentMethod != null) {
    metadata['paymentMethod'] = csvRow.paymentMethod;
    }
    if (csvRow.merchantOrderId != null) {
    metadata['merchantOrderId'] = csvRow.merchantOrderId;
    }
    final description = csvRow.product ?? csvRow.transactionType ?? '';
    final transaction = {'currency': 'CNY', 'payee': csvRow.counterparty ?? null, 'metadata': (metadata as Map).keys.toList().isNotEmpty ? metadata : null};
    return ParseSuccess(data: transaction);
  }
  
  DateTime? parseDateTime(String dateStr) {
    if (dateStr == null) {
    return null;
    }
    final trimmed = String.fromCharCode(dateStr).trim();
    final match = RegExp(r'^(\d{4})[-/](\d{1,2})[-/](\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$').firstMatch(trimmed);
    if (match) {
    final year = int.parse(match[1]!);
    final month = int.parse(match[2]!) - 1;
    final day = int.parse(match[3]!);
    final hour = int.parse(match[4]!);
    final minute = int.parse(match[5]!);
    final second = int.parse(match[6]!);
    final date = DateTime(year, month + 1, day, hour, minute, second);
    return date.millisecondsSinceEpoch.isNaN ? null : date;
    }
    final serialNum = Number(trimmed);
    if (!serialNum.isNaN && serialNum > 30000 && serialNum < 60000) {
    final date = XLSX.SSF.parse_date_code(serialNum);
    if (date) {
    return DateTime(date.y, date.m - 1 + 1, date.d, date.H ?? 0, date.M ?? 0, date.S ?? 0);
    }
    }
    return null;
  }
  
  Decimal? parseAmount(String amountStr, String flowType) {
    if (amountStr == null) {
    return null;
    }
    var cleaned = String.fromCharCode(amountStr).trim();
    if (cleaned.startsWith('¥') || cleaned.startsWith('￥')) {
    cleaned = cleaned.substring(1).trim();
    }
    cleaned = cleaned.replaceAll(RegExp(r','), '');
    try {
    final amount = Decimal.parse(cleaned);
    if (!amount.isFinite()) {
    return null;
    }
    if (flowType == '支出') {
    return amount.neg();
    }
    return amount;
    } catch (e) {
    return null;
    }
  }
  
  dynamic mapToCustomStatus(ReturnType<typeof categorizeWechatStatus> category, String originalStatus) {
    switch (category) {
    case 'success':
    return '支付成功';
    break;
    case 'refund':
    return '已退款';
    break;
    case 'failed':
    return '已关闭';
    break;
    default:
    if (originalStatus.contains('退款')) {
    return '已退款';
    }
    if (originalStatus.contains('关闭') || originalStatus.contains('失败')) {
    return '已关闭';
    }
    return '支付成功';
    break;
    }
  }
  
}
